documentclass: scrartcl
toc: true                           # Enable the Table of Contents
toc-title: "Index"                  # Customize the title of the table of contents
toc-depth: 3                        # Include headings up to level 3 (###)
number-sections: true
sitemap: true                       # Enables sitemap generation for web crawlers
tbl-colwidths: auto
format:
  html:
    code-fold: true                 # Allow code blocks to be foldable
    self-contained: true            # Embed resources like CSS and images
  docx:
    toc-location: before-body
    toc-pagebreak: true
    data: false
