project:
  type: website
  output-dir: _site  # Default output directory, adjust if needed
  render:
    - src/index.qmd
    - src/templates/**/*.qmd  # Only render files inside src/tempaltes/

website:
  title: "Technical Library"
