project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - src/index.qmd
    - src/guidelines/*.qmd

resources:
  - assets/  # Ensure images are copied to _site/


website:
  title: "Technical Library"
  site-url: "https://eea.github.io/CLMS_documents"
  page-navigation: true
  navbar:
    background: "#a0b128"
    foreground: "#ffffff"
    search: false
    left:
      - text: "Guidelines"
        href: src/guidelines/index.qmd

format:
  html:
    output-dir: ../_site  # Moves rendered files outside src/
    include-before-body: src/styles/main-logos.html
    css: src/styles/main.css
