project:
  type: website
  output-dir: _site  # Default output directory, adjust if needed
  render:
    - src/index.qmd
    - src/templates/**/*.qmd  # Only render files inside src/tempaltes/

website:
  title: "Technical Library"
  navbar:
    left:
      - href: src/index.qmd
        text: "Home"
      - text: "Templates"
        href: src/templates/index.qmd
  sidebar:
    - id: templates
      title: "Templates"
      contents:
        - src/templates/*/*.qmd

format:
  html:
    theme: cosmo
