project:
  type: website
  output-dir: _site
  execute-dir: project

resources:
  - assets/

website:
  title: "Technical Library"
  site-url: "https://eea.github.io/CLMS_documents/main"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  navbar:
    background: "#a0b128"
    foreground: "#ffffff"
  page-footer:
    left: |
      © 2025 EEA. All rights reserved.

format:
  html:
    output-dir: ../_site # Moves rendered files outside DOCS/
    include-before-body: DOCS/includes/main-logos.html
    css: DOCS/theme/main.css
