project:
  type: website
  output-dir: _site  # Default output directory, adjust if needed
  render:
    - src/index.qmd
    - src/templates/**/*.qmd
    - src/guidelines/*.qmd

website:
  title: "Technical Library"
  navbar:
    left:
      - href: src/index.qmd
        text: "Home"
      - text: "Guidelines"
        href: src/guidelines/index.qmd
      - text: "Templates"
        href: src/templates/index.qmd

  sidebar:
    - id: templates
      title: "Templates"
      contents:
        - src/templates/*/*.qmd
    - id: guidelines
      title: "Guidelines"
      contents:
        - src/guidelines/*.qmd

format:
  html:
    theme: cosmo
