project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - src/index.qmd
    - src/templates/**/*.qmd
    - src/guidelines/*.qmd

website:
  title: "Technical Library"
  navbar:
    background: "#a0b128"
    foreground: "#ffffff"
    search: false
    left:
      - text: "Guidelines"
        href: src/guidelines/index.qmd
      - text: "Templates"
        href: src/templates/index.qmd

format:
  html:
    output-dir: ../_site  # Moves rendered files outside src/
    include-before-body: src/styles/main-logos.html
    css: src/styles/main.css
