<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2021-12-01">
<meta name="keywords" content="Natura 2000 sites, Land Cover/Land Use mapping, Grassland habitat types, Very High Resolution imagery, Minimum Mapping Unit, Thematic classification accuracy, Change detection analysis, MAES ecosystem typology, ETRS89 Lambert Azimuthal Equal Area, Product attribute definition">
<meta name="description" content="This Product User Manual provides comprehensive documentation for the Copernicus Land Monitoring Service (CLMS) Natura 2000 (N2K) product. It details the Land Cover/Land Use (LC/LU) data available for grassland-rich Natura 2000 sites across Europe, focusing on the 2006, 2012, and 2018 reference years. The manual elucidates the product’s characteristics, methodology, and potential applications, with an emphasis on the technical aspects of data production, quality assessment, and user access, aiding in effective monitoring and assessment of habitat conservation status.">

<title>N2K - Product User Manual (PUM) – Technical Library</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-de070a7b0ab54f8780927367ac907214.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a2cbf74de394fe32d7823663fb7ddea1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "ScholarlyArticle",
    "headline": "N2K - Product User Manual (PUM)",
    "description": "This Product User Manual provides comprehensive documentation for the Copernicus Land Monitoring Service (CLMS) Natura 2000 (N2K) product. It details the Land Cover/Land Use (LC/LU) data available for grassland-rich Natura 2000 sites across Europe, focusing on the 2006, 2012, and 2018 reference years. The manual elucidates the product’s characteristics, methodology, and potential applications, with an emphasis on the technical aspects of data production, quality assessment, and user access, aiding in effective monitoring and assessment of habitat conservation status.",
    "datePublished": "December 1, 2021",
    "author": {
      "@type": "Person",
      "name": "?meta:author"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Copernicus Land Monitoring Service",
      "logo": {
        "@type": "ImageObject",
        "url": "https://land.copernicus.eu/static/media/ccl-icon-land-text-2.e04af716.svg"
      }
    },
    "keywords": "?invalid meta type:keywords",
    "articleSection": "General",
    "isAccessibleForFree": "true",
    "license": "",
    "speakable": {
      "@type": "SpeakableSpecification",
      "cssSelector": "article p"
    }
  }
</script>


<link rel="stylesheet" href="../theme/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Technical Library</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Content</h2>
   
  <ul>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link active" data-scroll-target="#executive-summary"><span class="header-section-number">1</span> Executive summary</a></li>
  <li><a href="#guide-for-the-reader" id="toc-guide-for-the-reader" class="nav-link" data-scroll-target="#guide-for-the-reader"><span class="header-section-number">2</span> Guide for the reader</a>
  <ul class="collapse">
  <li><a href="#who-is-this-guide-for" id="toc-who-is-this-guide-for" class="nav-link" data-scroll-target="#who-is-this-guide-for"><span class="header-section-number">2.1</span> Who is this guide for</a></li>
  <li><a href="#content-and-structure" id="toc-content-and-structure" class="nav-link" data-scroll-target="#content-and-structure"><span class="header-section-number">2.2</span> Content and structure</a></li>
  <li><a href="#applicable-documents" id="toc-applicable-documents" class="nav-link" data-scroll-target="#applicable-documents"><span class="header-section-number">2.3</span> Applicable documents</a></li>
  </ul></li>
  <li><a href="#review-of-user-requirements" id="toc-review-of-user-requirements" class="nav-link" data-scroll-target="#review-of-user-requirements"><span class="header-section-number">3</span> Review of user requirements</a></li>
  <li><a href="#product-application-areas-andor-examples-of-use-cases" id="toc-product-application-areas-andor-examples-of-use-cases" class="nav-link" data-scroll-target="#product-application-areas-andor-examples-of-use-cases"><span class="header-section-number">4</span> Product application areas and/or examples of use cases</a>
  <ul class="collapse">
  <li><a href="#use-case-grassland-lclu-changes-and-trends-analysis-in-natura-2000-sites" id="toc-use-case-grassland-lclu-changes-and-trends-analysis-in-natura-2000-sites" class="nav-link" data-scroll-target="#use-case-grassland-lclu-changes-and-trends-analysis-in-natura-2000-sites"><span class="header-section-number">4.1</span> Use case: Grassland LC/LU changes and trends analysis in Natura 2000 sites</a></li>
  <li><a href="#measuring-the-effectiveness-of-eu-member-states-efforts-for-protecting-natura-2000-grasslands" id="toc-measuring-the-effectiveness-of-eu-member-states-efforts-for-protecting-natura-2000-grasslands" class="nav-link" data-scroll-target="#measuring-the-effectiveness-of-eu-member-states-efforts-for-protecting-natura-2000-grasslands"><span class="header-section-number">4.2</span> Measuring the effectiveness of EU Member States efforts for protecting Natura 2000 grasslands</a></li>
  <li><a href="#use-case-green-infrastructure-gi-network" id="toc-use-case-green-infrastructure-gi-network" class="nav-link" data-scroll-target="#use-case-green-infrastructure-gi-network"><span class="header-section-number">4.3</span> Use case: Green infrastructure (GI) network</a></li>
  <li><a href="#use-case-copernicus-for-natura-2000-cop4n2k" id="toc-use-case-copernicus-for-natura-2000-cop4n2k" class="nav-link" data-scroll-target="#use-case-copernicus-for-natura-2000-cop4n2k"><span class="header-section-number">4.4</span> Use case: Copernicus for Natura 2000 (COP4N2K)</a></li>
  <li><a href="#general-product-application-area" id="toc-general-product-application-area" class="nav-link" data-scroll-target="#general-product-application-area"><span class="header-section-number">4.5</span> General product application area</a></li>
  </ul></li>
  <li><a href="#product-description" id="toc-product-description" class="nav-link" data-scroll-target="#product-description"><span class="header-section-number">5</span> Product description</a>
  <ul class="collapse">
  <li><a href="#product-overview" id="toc-product-overview" class="nav-link" data-scroll-target="#product-overview"><span class="header-section-number">5.1</span> Product overview</a></li>
  <li><a href="#selection-of-natura-2000-sites" id="toc-selection-of-natura-2000-sites" class="nav-link" data-scroll-target="#selection-of-natura-2000-sites"><span class="header-section-number">5.2</span> Selection of Natura 2000 sites</a></li>
  <li><a href="#representativity-analysis" id="toc-representativity-analysis" class="nav-link" data-scroll-target="#representativity-analysis"><span class="header-section-number">5.3</span> Representativity analysis</a></li>
  <li><a href="#natura-2000-boundary-changes-and-the-impact-in-the-clms-n2k-product-area-of-interest-aoi" id="toc-natura-2000-boundary-changes-and-the-impact-in-the-clms-n2k-product-area-of-interest-aoi" class="nav-link" data-scroll-target="#natura-2000-boundary-changes-and-the-impact-in-the-clms-n2k-product-area-of-interest-aoi"><span class="header-section-number">5.4</span> Natura 2000 boundary changes and the impact in the CLMS N2K product Area of Interest (AoI)</a></li>
  <li><a href="#clms-n2k-status-layer" id="toc-clms-n2k-status-layer" class="nav-link" data-scroll-target="#clms-n2k-status-layer"><span class="header-section-number">5.5</span> CLMS N2K status layer</a></li>
  <li><a href="#clms-n2k-change-layer" id="toc-clms-n2k-change-layer" class="nav-link" data-scroll-target="#clms-n2k-change-layer"><span class="header-section-number">5.6</span> CLMS N2K change layer</a></li>
  <li><a href="#technical-specification" id="toc-technical-specification" class="nav-link" data-scroll-target="#technical-specification"><span class="header-section-number">5.7</span> Technical specification</a></li>
  <li><a href="#clms-n2k-nomenclature" id="toc-clms-n2k-nomenclature" class="nav-link" data-scroll-target="#clms-n2k-nomenclature"><span class="header-section-number">5.8</span> CLMS N2K nomenclature</a></li>
  </ul></li>
  <li><a href="#product-methodology-and-workflow" id="toc-product-methodology-and-workflow" class="nav-link" data-scroll-target="#product-methodology-and-workflow"><span class="header-section-number">6</span> Product methodology and workflow</a>
  <ul class="collapse">
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing"><span class="header-section-number">6.1</span> Data Pre-Processing</a></li>
  <li><a href="#interpretation-and-classification" id="toc-interpretation-and-classification" class="nav-link" data-scroll-target="#interpretation-and-classification"><span class="header-section-number">6.2</span> Interpretation and Classification</a></li>
  </ul></li>
  <li><a href="#quality-assessment" id="toc-quality-assessment" class="nav-link" data-scroll-target="#quality-assessment"><span class="header-section-number">7</span> Quality assessment</a>
  <ul class="collapse">
  <li><a href="#internal-thematic-validation" id="toc-internal-thematic-validation" class="nav-link" data-scroll-target="#internal-thematic-validation"><span class="header-section-number">7.1</span> Internal thematic validation</a></li>
  <li><a href="#quality-assurance-qa-and-quality-control-qc-measures" id="toc-quality-assurance-qa-and-quality-control-qc-measures" class="nav-link" data-scroll-target="#quality-assurance-qa-and-quality-control-qc-measures"><span class="header-section-number">7.2</span> Quality Assurance (QA) and Quality Control (QC) measures</a></li>
  <li><a href="#external-independent-validation" id="toc-external-independent-validation" class="nav-link" data-scroll-target="#external-independent-validation"><span class="header-section-number">7.3</span> External independent validation</a></li>
  </ul></li>
  <li><a href="#terms-of-use-and-product-technical-support" id="toc-terms-of-use-and-product-technical-support" class="nav-link" data-scroll-target="#terms-of-use-and-product-technical-support"><span class="header-section-number">8</span> Terms of use and product technical support</a>
  <ul class="collapse">
  <li><a href="#terms-of-use" id="toc-terms-of-use" class="nav-link" data-scroll-target="#terms-of-use"><span class="header-section-number">8.1</span> Terms of use</a></li>
  <li><a href="#citation" id="toc-citation" class="nav-link" data-scroll-target="#citation"><span class="header-section-number">8.2</span> Citation</a></li>
  <li><a href="#product-technical-support" id="toc-product-technical-support" class="nav-link" data-scroll-target="#product-technical-support"><span class="header-section-number">8.3</span> Product technical support</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  <li><a href="#annexes" id="toc-annexes" class="nav-link" data-scroll-target="#annexes"><span class="header-section-number">10</span> Annexes</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="N2K_Product_User_Manual.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="N2K_Product_User_Manual.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Remove link to .docx file
    //
    document.querySelectorAll("a[href$='.docx']").forEach((link) => (link.style.display = "none"));

    // Add Version to the title's metadata
    //
    const titleMetaEl = document.querySelector(".quarto-title-meta");
    const wrapperDiv = document.createElement("div");
    wrapperDiv.innerHTML = `
        <div class="quarto-title-meta-heading">Version</div>
        <div class="quarto-title-meta-contents">
          <p>1</p>
        </div>
      `;
    titleMetaEl.appendChild(wrapperDiv);
  });
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">N2K - Product User Manual (PUM)</h1>
<p class="subtitle lead">Copernicus Land Monitoring Service</p>
</div>

<div>
  <div class="description">
    This Product User Manual provides comprehensive documentation for the Copernicus Land Monitoring Service (CLMS) Natura 2000 (N2K) product. It details the Land Cover/Land Use (LC/LU) data available for grassland-rich Natura 2000 sites across Europe, focusing on the 2006, 2012, and 2018 reference years. The manual elucidates the product’s characteristics, methodology, and potential applications, with an emphasis on the technical aspects of data production, quality assessment, and user access, aiding in effective monitoring and assessment of habitat conservation status.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 1, 2021</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>Natura 2000 sites, Land Cover/Land Use mapping, Grassland habitat types, Very High Resolution imagery, Minimum Mapping Unit, Thematic classification accuracy, Change detection analysis, MAES ecosystem typology, ETRS89 Lambert Azimuthal Equal Area, Product attribute definition</p>
  </div>
</div>

</header>


<p><br>
<strong>Contact:</strong></p>
<div data-custom-style="LeftAlign">
<p>European Environment Agency (EEA)<br>
Kongens Nytorv 6<br>
1050 Copenhagen K<br>
Denmark<br>
<a href="https://land.copernicus.eu/"><strong>https://land.copernicus.eu/</strong></a></p>
</div>
<div style="page-break-after: always;"></div>
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"ItemList","itemListElement":[{"@type":"ImageObject","caption":"","url":"N2K-media/image5.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image6.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image7.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image8.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image9.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image10.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image11.png"},{"@type":"ImageObject","caption":"Figure  1:  The  CLMS  N2K  product  portfolio","url":"N2K-media/Figure1.png"},{"@type":"ImageObject","caption":"Figure  2:  Coverage  of  the  CLMS  N2K  product","url":"N2K-media/image12.png"},{"@type":"ImageObject","caption":"Figure  3:  Example  coverage  of  CLMS  N2K  product  for  a  selected  Natura  2000  site  (DE4617303  Kalkkuppen  near  Brilon,  Germany).  Green=  extent  of  Natura  2000  site,  Blue  =  CLMS  N2K  product  extent.","url":"N2K-media/image13.png"},{"@type":"ImageObject","caption":"Figure  4:  Example  of  diverging  Natura  2000  site  boundaries  (red  2015  version,  blue  2019  version,  grey  N2K  product  coverage  incl. the  2km  buffer)","url":"N2K-media/image14.png"},{"@type":"ImageObject","caption":"Figure  5  -  Example  of  N2K  AoI  (red)  covering  multiple  N2K  sites  (black)","url":"N2K-media/image15.png"},{"@type":"ImageObject","caption":"Figure  6  -  Example  of  multi-part  Natura  2000  site  (AT3210001)  only  partially  covered  by  N2K  AOI","url":"N2K-media/image16.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image17.jpeg"},{"@type":"ImageObject","caption":"Figure  7  -  Example  of  changed  site  codes  and  geometries  from  2015  (top)  to  2018  (bottom)  Natura  2000  DB  version","url":"N2K-media/image18.jpeg"},{"@type":"ImageObject","caption":"","url":"N2K-media/image19.jpeg"},{"@type":"ImageObject","caption":"Figure  8  -  Example  of  Natura  2000  DB  site  changes  from  2015  (top)  to  2018  (bottom).  Background  N2K  AOI","url":"N2K-media/image20.jpeg"},{"@type":"ImageObject","caption":"","url":"N2K-media/image21.jpeg"},{"@type":"ImageObject","caption":"Figure  9  -  More  examples  of  Natura  2000  DB  site  changes  from  2015  (top)  to  2018  (bottom).  Background  N2K  AOI","url":"N2K-media/image22.jpeg"},{"@type":"ImageObject","caption":"Figure  10  -  Example  of  Natura  2000  DB  site  overlap.  The  site  codes  IT6020025,  IT7120201  and  IT5340010  overlay  the  area  of  site  code  IT7110128.","url":"N2K-media/image23.jpeg"},{"@type":"ImageObject","caption":"Figure  11  –  Example  of  a  Natura  2000  site  change  in  extent  (enlargement):  the  green  buffer  follows  the  shape  of  the  site  in  2012,  but  in  the  2018  Natura  2000  database  the  site  has  been  enlarged  therefore  not  anymore  totally  covered  by  the  N2K  AoI","url":"N2K-media/image24.png"},{"@type":"ImageObject","caption":"Figure  12:  CLMS  N2K  status  product  2018.  Example  for  a  selected  Natura  2000  site  (DE4617303  Kalkkuppen  near  Brilon,  Germany).","url":"N2K-media/image25.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/image26.png"},{"@type":"ImageObject","caption":"Figure  13:  CLMS  N2K  Change  product  2006-2012  (top)  and  2012-2018  (bottom).  Example  for  a  selected  Natura  2000  site  (DE4617303  Kalkkuppen  bei  Brilon,  Germany).  Yellow  =  LC/LU  changes  mapped  between  reference  years,  Blue  =  CLMS  N2K  site  extent","url":"N2K-media/image27.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/Table1.png"},{"@type":"ImageObject","caption":"","url":"N2K-media/Table2.png"},{"@type":"ImageObject","caption":"Table  10:  CLMS  N2K  nomenclature  overview  (v1.4,  dated  03.05.2021)","url":"N2K-media/Table3.png"},{"@type":"ImageObject","caption":"Figure  14:  Production  workflow  for  CMLS  N2K  products","url":"N2K-media/image28.png"},{"@type":"ImageObject","caption":"Figure  15:  Simple  change  mapping","url":"N2K-media/image29.png"},{"@type":"ImageObject","caption":"Figure  16:  Complex  change  mapping.  Individual  changes  with  each  MMU  <  0.5  ha  make  up  a  change  area  of  0.5  ha.","url":"N2K-media/image30.png"},{"@type":"ImageObject","caption":"Figure  17:  New  established  feature  with  splitted  change.","url":"N2K-media/image31.png"},{"@type":"ImageObject","caption":"Figure  18:  Area  related  to  change  within  road  relocation.","url":"N2K-media/image32.png"}]}
</script>
<section id="executive-summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Executive summary</h1>
<p>Copernicus is the European Union's Earth Observation Programme. It offers information services based on satellite Earth observation and in situ (non-space) data. These information services are <strong>freely</strong> and <strong>openly</strong> accessible to its users through six thematic Copernicus services (atmosphere monitoring, marine environment monitoring, land monitoring, climate change, emergency management and security).</p>
<p>The Copernicus Land Monitoring Service (CLMS) provides geographical information on land cover and its changes, land use, vegetation state, water cycle and earth surface energy variables to a broad range of users in Europe and across the world in the field of environmental terrestrial applications.</p>
<p>CLMS is jointly implemented by the European Environment Agency and the European Commission DG Joint Research Centre (JRC).</p>
<p>The local component as part of the CLMS is coordinated by the European Environment Agency and aims to provide specific and more detailed information that is complementary to the information obtained through the Pan-European component. The local component focuses on different hotspots, i.e.&nbsp;areas that are prone to specific environmental challenges and problems. It is based on very high-resolution imagery in combination with other available datasets (high and medium resolution images) over the pan-European area.</p>
<p>Natura 2000 sites are important hotspots for nature conservation therefore, the objective of the <strong>N2K product of CLMS</strong> is to provide detailed Land Cover / Land Use (LC/LU ) mapping results, covering a large number (4.790) of grassland-rich Natura 2000 sites. The selection of Natura 2000 sites to be mapped has been prioritized on the basis of occurrence of 32 different grassland habitat types across Europe, as defined by Annex I of the Habitats Directive (Council Directive 92/43/EEC).</p>
<p>The aim of the N2K product is to assess whether those selected sites are being effectively preserved and if a decline of certain grassland habitat types is being halted.</p>
<p>The service covers 631,820 km2 of land surface across Europe for three reference years: 2006, 2012 and 2018. The reference year 2018 was released together with a revised version of the 2006 and 2012 databases. For each Natura 2000 site, the mapping also covers a 2 km buffer zone.</p>
<p>This is a unique product with a high level of detail (Minimum Mapping Unit (MMU) is 0.5 ha), based on Very High Resolution (VHR) satellite data. The classification provides 55 distinct thematic classes and the class definitions follow a pre-defined nomenclature based on the Mapping and Assessment of Ecosystems and their Services typology of ecosystems (at level 1) and are further harmonised with Corine Land Cover and adapted to the specific characteristics of grasslands habitats (levels 2 to 4). It offers two types of products: status maps for the three reference years and two change products for the two reference periods.</p>
<p>The N2K product offers a good basis to analyse the LC/LU situation in grassland-rich Natura 2000 sites and furthermore allows to devise the general trends and change factors within the sites through the observation periods, as well as within the buffer zone surrounding those.</p>
<p>Hereinafter referred to as “<strong>CLMS N2K</strong>”, a LC/LU product in a selection of Natura 2000 sites.</p>
</section>
<section id="guide-for-the-reader" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Guide for the reader</h1>
<section id="who-is-this-guide-for" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="who-is-this-guide-for"><span class="header-section-number">2.1</span> Who is this guide for</h2>
<p>This Product User Manual is the primary document that users are recommended to read before using the N2K product. It provides an overview of the product characteristics, product methodology and workflows, user requirements and example/potential use cases, information about the quality assessment checks and their results as well as product technical support.</p>
</section>
<section id="content-and-structure" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="content-and-structure"><span class="header-section-number">2.2</span> Content and structure</h2>
<p>The document is structured as follows:</p>
<ul>
<li><p>Chapter 3 recalls the user requirements</p></li>
<li><p>Chapter 4 presents potential application areas and/or use cases examples</p></li>
<li><p>Chapter 5 presents the product description (product content and characteristics, file naming convention and format(s))</p></li>
<li><p>Chapter 6 provides a description of the methodology and production workflows</p></li>
<li><p>Chapter 7 summarizes the quality assessment and/or validation procedure and results</p></li>
<li><p>Chapter 8 provides information about product access and use conditions as well as the technical product support</p></li>
<li><p>Chapter 9 lists references to the cited literature</p></li>
<li><p>Chapter 10 provides annexes</p></li>
</ul>
</section>
<section id="applicable-documents" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="applicable-documents"><span class="header-section-number">2.3</span> Applicable documents</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>ID</strong></th>
<th><strong>Document Name / Content</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AD 01</td>
<td><p>CLMS N2K Nomenclature and Mapping Guideline (Issue 1.4, Date Issued: 03/05/2021)</p>
<p><a href="https://land.copernicus.eu/user-corner/technical-library/nmg_n2k_status_2018_change_2012_2018">NOMENCLATURE and MAPPING GUIDELINE (copernicus.eu)</a></p></td>
</tr>
<tr class="even">
<td>AD 02</td>
<td><p>N2K validation report (2006 and 2012 databases)</p>
<p><a href="https://land.copernicus.eu/user-corner/technical-library/n2k-validation-report">Framework service contract for the GMES Initial Operations / Copernicus Land monitoring services – Validation of products</a></p></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="review-of-user-requirements" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Review of user requirements</h1>
<p>The European Commission has been systematically collecting user needs for Copernicus products and services, expressed in different policy areas. Information on specific aspects of land cover, land use and changes such as provided by this CLMS N2K product are an essential prerequisite to support many policies, reporting and monitoring obligations (EC 2019).</p>
<p>The reference baseline for mapping land cover and land use (LC/LU ) on the European scale has been the Corine Land Cover classification (Coordination of Information on the Environment Land Cover, CLC) (EEA 1995). It provides a LC/LU time series starting in 1990 at an original scale of 1: 100 000, a minimum spatial resolution of 25ha (5ha for LC/LU changes) and using 44 classes of the 3-level Corine nomenclature. It is supported by additional thematic High Resolution Layers (HRL) providing raster based information at 20 and recently at 10m pixel size on various aspects of the European land cover (e.g.&nbsp;imperviousness degree, forest and grassland cover).</p>
<p>The CLMS N2K supplements these reference mapping products with higher thematic details and spatial resolution. It focuses on a selection of the Natura 2000 network of sites and provides a LC/LU time series at 0.5ha resolution, expressed in a detailed nomenclature of 55 classes.</p>
<p>The central aim of the Natura 2000 protected areas network is to ensure the long-term survival of Europe's most valuable and threatened species and habitats. Information is still lacking on the effectiveness of conservation measures in Europe’s protected areas and how well biodiversity is protected there (EEA 2019, p.79). The CLMS N2K helps to fill these gaps through objective and European-wide harmonised information on LC/LU trends within and in the vicinity of grassland-rich Natura 2000 sites. It directly supports the analysis of trends and progress in stopping the ongoing loss of biodiversity in Europe.</p>
<p>Particularly grasslands are affected by changing agricultural management and land conversion (EEA 2019). Land cover changes can be monitored with this product for the existing time series 2006-2012-2018. This can help to monitor biodiversity health as proposed by the GEOBON working group of the Group on Earth Observation (GEO). The CLMS N2K product can provide information for indicators such as land abandonment, intensification/extensification within agriculture as well as landscape context maps indicating overall landscape configuration or fragmentation.</p>
<p>The new EU Biodiversity Strategy for 2030 makes it clear that for the good of our environment and our economy additional efforts are needed, to deal with the five main direct drivers of biodiversity loss – changes in land and sea use, overexploitation, climate change, pollution, and invasive alien species.</p>
<p>The CLMS N2K products supports the EU Biodiversity Strategy 2030 with specific focus on areas of very high biodiversity value or potential.</p>
</section>
<section id="product-application-areas-andor-examples-of-use-cases" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Product application areas and/or examples of use cases</h1>
<section id="use-case-grassland-lclu-changes-and-trends-analysis-in-natura-2000-sites" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="use-case-grassland-lclu-changes-and-trends-analysis-in-natura-2000-sites"><span class="header-section-number">4.1</span> Use case: Grassland LC/LU changes and trends analysis in Natura 2000 sites</h2>
<p>Established under the EU Habitats and Birds Directives, Natura 2000 is the world's largest ecological network of protected areas, a network of key breeding and resting places for rare and endangered species. In addition to the focus on species, the network also aims at protecting more than 200 different Natural habitat types. The network covers about 18% of the EU's land area throughout all 27 EU Member States. It is not a system of strict nature reserves from which all human activities would be excluded. While it includes strictly protected areas, most of the land remains privately owned and managed. EU Member States must ensure that the sites are managed in a sustainable manner to prevent significant impacts on species and habitats for which the sites have been designated. It is part of the policy strategy to conserve Europe's biodiversity and was established on the legal requirements of the Habitats Directive and the Birds Directive.</p>
<p>Grassland ecosystems are highly biodiverse and species-rich vegetation types, providing a range of ecosystem services. The selection of Natura 2000 sites mapped was prioritized on the basis of occurrence of 32 different grassland habitat types across Europe, as defined by Annex I of the Habitats Directive (Council Directive 92/43/EEC).</p>
<p>Based on a comparative assessment of the N2K product, reference years 2006, 2012 and 2018, LC/LU changes and trends were analysed within the selected Natura 2000 sites and their two km buffer zone.</p>
<p>Due to the known strong decrease of grassland habitats, the focus of the analysis relied especially on semi-Natural and Natural grasslands, as they are vulnerable to different pressures such as intensification of agriculture and grassland management, land abandonment, shrub encroachment, afforestation, urbanisation and several more.</p>
<p>The assessment was based on the mapping of land cover/land use as well as changes between the three reference years 2006, 2012 and 2018 of the selected Natura 2000 sites, including a 2 km buffer zone around each site, to form the total N2K product coverage of around 631.820 km² across Europe.</p>
<p>The assessment of the Grassland Habitat Types concentrated on the grassland areas and its changes. LC/LU changes are associated with the following Land Cover Change Groups (LCGs), defined in close cooperation with representatives from DG ENV and EEA:</p>
<ul>
<li><p>Urbanisation</p></li>
<li><p>De-urbanisation</p></li>
<li><p>Agricultural intensification</p></li>
<li><p>Agricultural extensification</p></li>
<li><p>Agricultural conversion to managed grassland</p></li>
<li><p>Agricultural conversion to cropland</p></li>
<li><p>Agricultural abandonment</p></li>
<li><p>Forest increase - Natural succession</p></li>
<li><p>Forest increase – Plantation</p></li>
<li><p>Tree encroachment</p></li>
<li><p>Deforestation</p></li>
<li><p>Forest degradation</p></li>
<li><p>Regeneration</p></li>
<li><p>Intensification of grassland use</p></li>
<li><p>Extensification of grassland use</p></li>
<li><p>Decline of woody plants</p></li>
<li><p>Woody plant encroachment</p></li>
<li><p>Shift of tree line</p></li>
<li><p>Colonization by marginal grasses</p></li>
<li><p>Expansion of grassland</p></li>
<li><p>Grassland degradation</p></li>
<li><p>Scrub encroachment</p></li>
<li><p>Scrub retreat</p></li>
<li><p>Sedimentation / Plant succession</p></li>
<li><p>Drainage</p></li>
<li><p>Deconstruction and reNaturation</p></li>
<li><p>Hydrological restoration</p></li>
</ul>
<p>The mapped area covers a substantial part of the Natura 2000 sites and the European territory and includes, to different degrees, all MS and most Biogeographical Regions. Some biogeographical zones and MS are better represented than others and therefore the analysis should be read in the context of this representativeness.</p>
<p>The figure below (Distribution of Level 1 classes in the mapped N2K AoI (Natura 2000 sites and buffer zone) for the reference years 2006, 2012 and 2018.) gives an overview of the eight Level 1 classes, their area coverage and N2K AoI proportion for the three-time steps 2006, 2012 and 2018. The highest share is taken up by <em>Woodland and forests</em>, followed by <em>Cropland</em> and <em>Grassland</em>. <em>Wetlands</em> are by far the rarest class, followed by <em>Water</em> and <em>Open spaces with little or no vegetation</em>.</p>
<p><img src="./N2K-media/image5.png" class="img-fluid"></p>
<p>A look at the changes between the time steps 2006 – 2012 and 2012 – 2018 shown in the figure below (Overview total gains and losses per Level 1 class in ha and % for the periods 2006-2012 and 2012-2018 on European Level) reveals high dynamics in the classes Urban and Grassland, both in total numbers and percentage share. The observation period 2006 – 2012 indicates a considerable high increase of Urban areas (2,64%) whereas Grasslands decreased to a similar total area but a lesser percentage. A percentual high loss was also experienced by Wetlands and Heathland and moorlands.</p>
<p>The period 2012 – 2018 is dominated by the high decrease of the Grassland class, with even 0,21 percentage points more than the previous period, and a high increase of Urban area, even though to a lesser extent than in 2006 – 2012.</p>
<p>Comparing the two periods of observation, the decrease of Cropland between 2006 and 2012 is compensated by an increase in the following six years. Both classes, Urban and Grassland, continued their trend in opposite directions. Heathland and moorlands as well as Wetlands continue to loose area, even if to a slower ratio than in the subsequent period. The Open spaces with little or no vegetation class has experienced a reverse trend from an area gain between 2006-2012 to area loss in 2012-2018. One reason behind this may be the recovery of landscape after fire events. The figure also shows the declining area of No Data areas which reached zero in 2018. Since this cannot be considered a real change but is only resulting from a significant improvement in satellite data availability, it appears without bar in the graph.</p>
<p><img src="./N2K-media/image6.png" class="img-fluid"></p>
<p>The figure below shows the most important pressures on grassland habitats for the 2012 – 2018 period. This helps to better understand the changes in the mapped area. The percentage of each pressure is related to the total area of changes.</p>
<p>The most prominent pressures are ‘Agricultural intensification’ (16%), Tree encroachment (16%) and ‘Agricultural conversion to cropland’ (14%) and followed by ‘Urbanization’ (13%). ‘Expansion of grassland’ (9%) remains the most important change process related to a grassland gain.</p>
<p><img src="./N2K-media/image7.png" class="img-fluid"></p>
</section>
<section id="measuring-the-effectiveness-of-eu-member-states-efforts-for-protecting-natura-2000-grasslands" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="measuring-the-effectiveness-of-eu-member-states-efforts-for-protecting-natura-2000-grasslands"><span class="header-section-number">4.2</span> Measuring the effectiveness of EU Member States efforts for protecting Natura 2000 grasslands</h2>
<p>In addition to the previous general assessment, Copernicus Land Monitoring Service is helping to support and measure the effectiveness of EU Member States and their efforts for protecting the increasingly important Natura 2000 grasslands.</p>
<p>When looking at the LC/LU inside the Natura 2000 sites, as compared to the 2 km buffer surrounding the sites, and as expected, the more anthropogenic land uses, such as urban and cropland, cover larger areas in the buffer zones as shown in the table below. In contrast, Natural and semi-Natural land cover is more abundant inside the sites. Grasslands are found to an almost equal extent in both areas because the class includes not only Natural and semi-Natural (species-rich) but also intensely managed (species-poor) grasslands, which are more comparable in their use to croplands.</p>
<p>Overall, a continuous loss of grasslands can be observed, and the trend is visible both in the buffer zone and the sites themselves, even though it is to a lesser amount in the latter.</p>
<p><img src="./N2K-media/image8.png" class="img-fluid"></p>
<p>Other key findings (shown in the table below) include:</p>
<ul>
<li><p>Grasslands showed a decline for two of the four different classes distinguished in the mapping. Managed grassland (class 4100) and Semi-Natural grassland with woody plants (class 4212) have the highest losses.</p></li>
<li><p>Alpine areas (4220) as the only type being more or less stable.</p></li>
<li><p>Semi-Natural grassland without woody plants (4211) experienced a gain for both reference periods.</p></li>
</ul>
<p><img src="./N2K-media/image9.png" class="img-fluid"></p>
<p>Looking at the data for Natura 2000 sites and buffer zones separately (Figure below), the grassland classes inside the Natura 2000 network can be seen to still be declining in area, apart from class 4211, which experienced slight gains in both periods, the reason for this most likely being land abandonment leading to shrub encroachment. In the buffer zone, classes 4100, 4212 and 4220 all decline more severely than inside the sites. The graph clearly shows once again that grassland cover seems overall to be subject to bigger changes outside Natura 2000 sites (i.e.&nbsp;in the buffer).</p>
<p><img src="./N2K-media/image10.png" class="img-fluid"></p>
<p><img src="./N2K-media/image11.png" class="img-fluid"></p>
<p>The N2K product allows us to recognise that good work is being done within Natura 2000 areas to lessen the decline of grasslands areas. However, it also tells us more work is required to protect these valuable areas, in particular with the continual monitoring of changing agricultural practices.</p>
<p>The Copernicus Land Monitoring Service (implemented by the European Environment Agency) is committed to the continual improvement of such monitoring schemes to address these challenges collectively. In particular, it is hoped that grasslands can not only be effectively preserved with N2K, but that the monitoring and assessment of biodiversity in line with the objectives of the EU Biodiversity Strategy to 2030 can also be achieved to the highest level. All of which will help ensure the continual protection of the vitally important Natura 2000 grasslands.</p>
</section>
<section id="use-case-green-infrastructure-gi-network" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="use-case-green-infrastructure-gi-network"><span class="header-section-number">4.3</span> Use case: Green infrastructure (GI) network</h2>
<p>The European Topic Centre on Urban, Land and Soil Systems (ETC-ULS) uses the CLMS N2K data for their study on assessing the contribution of GI to improving the conservation status of species of Community interest and the delivery of ecosystem services in Europe (ETC-ULS 2020). An integrated assessment on the distribution of GI, its multifunctional areas and the conservation status of a particular set of mammal species enable a mapping and prioritisation of where GI should be preserved, restored or further deployed, both within and outside of the Natura 2000 network. Thus, the work presented in their report is intended to improve and strengthen the information about GI mapping and contributes to several political strategies.</p>
</section>
<section id="use-case-copernicus-for-natura-2000-cop4n2k" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="use-case-copernicus-for-natura-2000-cop4n2k"><span class="header-section-number">4.4</span> Use case: Copernicus for Natura 2000 (COP4N2K)</h2>
<p>The project <a href="http://cop4n2k.eu/">COP4N2K</a> aims at developing a prototype to support monitoring and management of Natura2000 sites habitats with Copernicus. To guide the processing of the EO data and hold the results of the analysis a number of reference datasets were used. One of those datasets was the CLMS N2K, whose objects were used to hold the results of the EO analysis.</p>
</section>
<section id="general-product-application-area" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="general-product-application-area"><span class="header-section-number">4.5</span> General product application area</h2>
<p>The CLMS N2K product provides highly detailed and consistent information on Land Cover / Land Use (LC/LU ) for approximately 631.000 km² across Europe. It has a thematic depth of 55 different LC/LU classes with a Minimum Mapping Unit (MMU) and Minimum Mapping Width (MMW), i.e.&nbsp;the smallest area to be distinguished, of 0.5ha and 10m, respectively.</p>
<p>The product is available for the reference years 2006, 2012 and 2018 and allows due to its technical setup a direct analysis of LC/LU changes across time using a homogenous data source across Europe.</p>
<p>The hierarchical CLMS N2K LC/LU nomenclature is highly compatible to the CLMS Local Component Coastal Zone (CZ) and Riparian Zone (RZ) products. Depending on the LC/LU under investigation, these products could be jointly used to analyse LC/LC trends and changes. </p><div style="page-break-after: always;"></div><p></p>
</section>
</section>
<section id="product-description" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Product description</h1>
<section id="product-overview" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="product-overview"><span class="header-section-number">5.1</span> Product overview</h2>
<p>The CLMS N2K product contains two specific information layers for each reference year (Figure 1). The status layer describes the LC/LU situation in the relevant reference year. The change layer describes LC/LU change areas between two reference years. Currently status layers for the reference years 2006, 2012 and 2018 are available, with corresponding change layers for 2006-2012 and 2012-2018. The CLMS N2K product covers an area of 631.820 km² (Figure 2).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/Figure1.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1: The CLMS N2K product portfolio</figcaption>
</figure>
</div>
<p>The CLMS N2K layers are provided as polygon vector data. They cover 4.790 Natura 2000 sites across Europe (Figure 2), including a 2km buffer zone around each site (Figure 3).</p>
<p>The LC/LU classification is based on visual image interpretation and delineation from Very High Resolution (VHR) satellite imagery. The characteristics of the product are the following:</p>
<ul>
<li><p>LC/LU is encoded following a detailed mapping nomenclature and guideline (AD01) into 55 different classes using a hierarchical LC/LU encoding structure ranging from 8 LC/LU classes at Code level 1 to the full 55 classes at Code level 4</p></li>
<li><p>LC/LU classes are:</p>
<ul>
<li><p>based on the MAES (Mapping and Assessment of Ecosystems and their Services) ecosystem types specification at Code level 1</p></li>
<li><p>largely compatible with CORINE Land Cover (CLC) and Urban Atlas and adapted to the specific characteristics of grasslands habitats (Code levels 2 to 4)</p></li>
<li><p>harmonized with CLMS Riparian Zones and Coastal Zones products.</p></li>
</ul></li>
<li><p>Minimum Mapping Unit is 0.5ha</p></li>
<li><p>Minimum Mapping Width is 10m</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image12.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2: Coverage of the CLMS N2K product</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image13.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3: Example coverage of CLMS N2K product for a selected Natura 2000 site (DE4617303 Kalkkuppen near Brilon, Germany). Green= extent of Natura 2000 site, Blue = CLMS N2K product extent.</figcaption>
</figure>
</div>
</section>
<section id="selection-of-natura-2000-sites" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="selection-of-natura-2000-sites"><span class="header-section-number">5.2</span> Selection of Natura 2000 sites</h2>
<p>The selection of Natura 2000 sites to be mapped by the N2K product is based on the occurrence of grassland habitats within the sites. They cover 31 natural and semi-natural grassland formations as defined by Annex I of the Habitats Directive (Council Directive 92/43/EEC) (Table 1).</p>
<table class="caption-top table">
<caption>Table 1: List of grassland habitat types relevant for the Natura 2000 site selection</caption>
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">6110 Rupicolous calcareous or basophilic grasslands of the Alysso-Sedion albi</td>
</tr>
<tr class="even">
<td style="text-align: left;">6120 Xeric sand calcareous grasslands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6130 Calaminarian grasslands of the Violetalia calaminariae</td>
</tr>
<tr class="even">
<td style="text-align: left;">6140 Siliceous Pyrenean Festuca eskia grasslands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6150 Siliceous alpine and boreal grasslands</td>
</tr>
<tr class="even">
<td style="text-align: left;">6160 Oro-Iberian Festuca indigesta grasslands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6170 Alpine and subalpine calcareous grasslands</td>
</tr>
<tr class="even">
<td style="text-align: left;">6180 Macaronesian mesophile grasslands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6190 Rupicolous pannonic grasslands (Stipo-Festucetalia pallentis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6210 Semi-Natural dry grasslands and scrubland facies on calcareous substrates (Festuco-Brometalia) (* important orchid sites)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6220 Pseudo-steppe with grasses and annuals of the Thero-Brachypodietea</td>
</tr>
<tr class="even">
<td style="text-align: left;">6230 Species-rich Nardus grasslands, on silicious substrates in mountain areas (and submountain areas in Continental Europe)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6240 Sub-Pannonic steppic grasslands</td>
</tr>
<tr class="even">
<td style="text-align: left;">6250 Pannonic loess steppic grasslands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6260 Pannonic sand steppes</td>
</tr>
<tr class="even">
<td style="text-align: left;">6270 Fennoscandian lowland species-rich dry to mesic grasslands</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6280 Nordic alvar and precambrian calcareous flatrocks</td>
</tr>
<tr class="even">
<td style="text-align: left;">62A0 Eastern sub-Mediterranean dry grasslands (Scorzoneratalia villosae)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">62B0 Serpentinophilous grassland of Cyprus</td>
</tr>
<tr class="even">
<td style="text-align: left;">62C0 Ponto-Sarmatic steppes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">62D0 Oro-Moesian acidophilous grasslands</td>
</tr>
<tr class="even">
<td style="text-align: left;">6310 Dehesas with evergreen Quercus spp.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6410 Molinia meadows on calcareous, peaty or clayey-silt-laden soils (Molinion caeruleae)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6420 Mediterranean tall humid grasslands of the Molinio-Holoschoenion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6430 Hydrophilous tall herb fringe communities of plains and of the montane to alpine levels</td>
</tr>
<tr class="even">
<td style="text-align: left;">6440 Alluvial meadows of river valleys of the Cnidion dubii</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6450 Northern boreal alluvial meadows</td>
</tr>
<tr class="even">
<td style="text-align: left;">6460 Peat grasslands of Troodos*</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6510 Lowland hay meadows (Alopecurus pratensis, Sanguisorba officinalis)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6520 Mountain hay meadows</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6530 Fennoscandian wooded meadows</td>
</tr>
<tr class="even">
<td style="text-align: left;">6540 Sub-Mediterranean grasslands of the Molinio-Hordeion secalini</td>
</tr>
</tbody>
</table>
<p>* grassland habitat type not covered in the N2K product within the 32 types listed in Annex I of the Habitats Directive</p>
</section>
<section id="representativity-analysis" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="representativity-analysis"><span class="header-section-number">5.3</span> Representativity analysis</h2>
<p>The final selection of Natura 2000 sites depended to a large extent also on the satellite data availability for 2006 and 2012 in order to avoid data gaps as much as possible. That led to the fact that the mapped Natura 2000 sites are neither equally distributed across Europe nor equally representative of the Member States or the Biogeographical regions: the distribution of the selected sites with a high representation are in South, South-western, Central and Eastern Europe whereas the Nordic countries and the British and Irish Isles are underrepresented.</p>
<p>Moreover, a considerable number of sites without designated grassland habitats and which were therefore not specifically selected for the mapping, <strong><u>still overlap with, or lie completely within</u></strong> the LC/LU mapping boundary (the designated AoI) that is defined by the outline of the selected N2K sites plus a 2 km buffer.</p>
<p>The boundaries of Member States with coastlines were extended 10km to the sea in order to assure full coverage of all the Natura 2000 sites chosen for the mapping. The additional area of coastal waters is included in every MS with marine area.</p>
<p>In a first assessment step, the number of sites per MS which are completely covered by the mapping area was compared to the total number of Natura 2000 sites of each MS.</p>
<p>The mapping area (Natura 2000 sites and buffer) includes sites which are completely covered, as well as some which are only partly covered by the N2K AoI. The number of completely mapped Natura 2000 sites was determined by the N2K LC/LU mapping boundaries. The intention is to show to what degree the Natura 2000 sites with designated grassland habitats of every MS are represented in the CLMS N2K mapping products.</p>
<p>Some sites, however, where not counted as completely mapped, if the GIS operation identified parts of non-coverage. This is often the case along the coastline, where the sea area has been cut out of the N2K AoI even though the Natura 2000 boundary actually extends a bit further into the open water. Further, the area mapped in every MS (Natura 2000 sites + buffer) is compared and put into relation with the calculated area, which may also include a 10km buffer of coastal waters, if applicable.</p>
<p>The first part of the assessment indicates a considerable high representation of Natura 2000 sites (disregarding their designated habitat types) for Hungary (44,38%), Italy (38,04%) and Bulgaria (37,46%) and very low representation of Finland (0,32%), United Kingdom (0,96%) and Ireland (0,99%), with an EU average of 17,17%.</p>
<p>When comparing the area of each MS national territory with the mapped area, Slovenia (42,19%) and Luxembourg (37,76%) as very small countries are at the top of the list but closely followed by large MS like Bulgaria (37,46%) and Spain (31,41%). Again, Finland (0,18%), the United Kingdom (0,33%) and Ireland (0,86%) are only covered to a fraction compared to the EU average of 13,52% (Table 2).</p>
<table class="caption-top table">
<caption>Table 2: Representativeness of CLMS N2K mapping for all Natura 2000 site types within each MS</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Member state (MS)</th>
<th>Natura 2000 sites (total)</th>
<th>Natura 2000 sites completely mapped</th>
<th>Share of mapped sites</th>
<th>Total area mapped (km²)</th>
<th>Area MS (km²)</th>
<th>% of MS area</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Austria</td>
<td>350</td>
<td>53</td>
<td>15.14%</td>
<td>8295.83</td>
<td>83927.63</td>
<td>9.88%</td>
</tr>
<tr class="even">
<td>Belgium</td>
<td>310</td>
<td>51</td>
<td>16.45%</td>
<td>6152.43</td>
<td>31349.53</td>
<td>19.63%</td>
</tr>
<tr class="odd">
<td>Bulgaria</td>
<td>339</td>
<td>127</td>
<td>37.46%</td>
<td>40686.90</td>
<td>113948.15</td>
<td>35.71%</td>
</tr>
<tr class="even">
<td>Croatia</td>
<td>779</td>
<td>157</td>
<td>20.15%</td>
<td>13312.80</td>
<td>75603.23</td>
<td>17.61%</td>
</tr>
<tr class="odd">
<td>Cyprus</td>
<td>63</td>
<td>3</td>
<td>4.76%</td>
<td>440.94</td>
<td>15931.60</td>
<td>2.77%</td>
</tr>
<tr class="even">
<td>Czech Republic</td>
<td>1153</td>
<td>160</td>
<td>13.88%</td>
<td>8587.88</td>
<td>78869.90</td>
<td>10.89%</td>
</tr>
<tr class="odd">
<td>Denmark</td>
<td>384</td>
<td>20</td>
<td>5.21%</td>
<td>2750.28</td>
<td>71628.43</td>
<td>3.84%</td>
</tr>
<tr class="even">
<td>Estonia</td>
<td>567</td>
<td>120</td>
<td>21.16%</td>
<td>12385.10</td>
<td>62545.91</td>
<td>19.80%</td>
</tr>
<tr class="odd">
<td>Finland</td>
<td>1859</td>
<td>6</td>
<td>0.32%</td>
<td>683.41</td>
<td>384010.79</td>
<td>0.18%</td>
</tr>
<tr class="even">
<td>France</td>
<td>1779</td>
<td>394</td>
<td>22.15%</td>
<td>63840.30</td>
<td>585899.90</td>
<td>10.90%</td>
</tr>
<tr class="odd">
<td>Germany</td>
<td>5200</td>
<td>767</td>
<td>14.75%</td>
<td>47540.00</td>
<td>372524.70</td>
<td>12.76%</td>
</tr>
<tr class="even">
<td>Greece</td>
<td>446</td>
<td>34</td>
<td>7.62%</td>
<td>12010.60</td>
<td>236245.66</td>
<td>5.08%</td>
</tr>
<tr class="odd">
<td>Hungary</td>
<td>525</td>
<td>233</td>
<td>44.38%</td>
<td>26189.30</td>
<td>94022.25</td>
<td>27.85%</td>
</tr>
<tr class="even">
<td>Ireland</td>
<td>604</td>
<td>6</td>
<td>0.99%</td>
<td>786.51</td>
<td>91139.82</td>
<td>0.86%</td>
</tr>
<tr class="odd">
<td>Italy</td>
<td>2613</td>
<td>994</td>
<td>38.04%</td>
<td>78436.60</td>
<td>365392.96</td>
<td>21.47%</td>
</tr>
<tr class="even">
<td>Latvia</td>
<td>333</td>
<td>29</td>
<td>8.71%</td>
<td>3418.80</td>
<td>73070.45</td>
<td>4.68%</td>
</tr>
<tr class="odd">
<td>Lithuania</td>
<td>559</td>
<td>61</td>
<td>10.91%</td>
<td>2565.31</td>
<td>72943.46</td>
<td>3.52%</td>
</tr>
<tr class="even">
<td>Luxembourg</td>
<td>66</td>
<td>20</td>
<td>30.30%</td>
<td>980.15</td>
<td>2595.77</td>
<td>37.76%</td>
</tr>
<tr class="odd">
<td>Malta</td>
<td>52</td>
<td>3</td>
<td>5.77%</td>
<td>114.79</td>
<td>1717.87</td>
<td>6.68%</td>
</tr>
<tr class="even">
<td>Netherlands</td>
<td>196</td>
<td>9</td>
<td>4.59%</td>
<td>1918.43</td>
<td>44292.10</td>
<td>4.33%</td>
</tr>
<tr class="odd">
<td>Poland</td>
<td>984</td>
<td>242</td>
<td>24.59%</td>
<td>45526.40</td>
<td>326678.13</td>
<td>13.94%</td>
</tr>
<tr class="even">
<td>Portugal</td>
<td>166</td>
<td>22</td>
<td>13.25%</td>
<td>10444.80</td>
<td>113707.07</td>
<td>9.19%</td>
</tr>
<tr class="odd">
<td>Romania</td>
<td>606</td>
<td>105</td>
<td>17.33%</td>
<td>38392.70</td>
<td>249883.33</td>
<td>15.36%</td>
</tr>
<tr class="even">
<td>Slovakia</td>
<td>683</td>
<td>161</td>
<td>23.57%</td>
<td>9635.40</td>
<td>49665.16</td>
<td>19.40%</td>
</tr>
<tr class="odd">
<td>Slovenia</td>
<td>355</td>
<td>80</td>
<td>22.54%</td>
<td>8637.47</td>
<td>20473.70</td>
<td>42.19%</td>
</tr>
<tr class="even">
<td>Spain</td>
<td>1863</td>
<td>569</td>
<td>30.54%</td>
<td>174763.00</td>
<td>556466.17</td>
<td>31.41%</td>
</tr>
<tr class="odd">
<td>Sweden</td>
<td>4087</td>
<td>352</td>
<td>8.61%</td>
<td>9476.23</td>
<td>495428.75</td>
<td>1.91%</td>
</tr>
<tr class="even">
<td>Switzerland</td>
<td>37</td>
<td>3</td>
<td>8.11%</td>
<td>938.88</td>
<td>41280.13</td>
<td>2.27%</td>
</tr>
<tr class="odd">
<td>United Kingdom</td>
<td>935</td>
<td>9</td>
<td>0.96%</td>
<td>1078.16</td>
<td>326416.02</td>
<td>0.33%</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td><strong>27893</strong></td>
<td><strong>4790</strong></td>
<td><strong>17.17%</strong></td>
<td><strong>629989.41</strong></td>
<td><strong>5037658.58</strong></td>
<td><strong>13.52%</strong>*</td>
</tr>
</tbody>
</table>
<p><em>²MS size is overestimated due to the sea buffer calculation. Since the Eastern European countries, which are not member of the EEA 39, are not included in the layer, the neighbouring countries were treated as sea and buffered with 10km into the neighbouring country.</em></p>
<p><em>*Average taken from all MS. The percentage of comparing the sum of all calculated MS areas with the total mapped area would be roughly 8%.</em></p>
<p>The focus of the CLMS N2K mapping was put on sites with grassland habitats. These are considered as especially rich in biodiversity and face a declining trend in most parts of the Member States. Table 3 below gives an overview of the number of sites which contain at least one declared type of grassland type (according to the Natura 2000 <a href="https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32011D0484&amp;from=EN">Standard Data Forms)</a> and its coverage by the LC/LU mapping.</p>
<p>The assessment of the representativeness of sites with grassland habitats produces a high number for Slovenia (71,64%), Croatia (57,97%) and Bulgaria (56,50%). A low representativeness of grassland habitats is found in Finland (1,85%), the United Kingdom (3,93%) and Ireland (6,76%). In some MS, also a considerable high number of sites with grassland habitats is partly mapped and, in some MS, the percentage of these sites which are not mapped at all is comparably high, e.g.&nbsp;Austria, Cyprus, Denmark, Sweden and the Netherlands. Note that this table includes all sites which were listed in the year 2018 and the number of grassland sites may have been lower when the sites were chosen for the 2006-2012 mapping.</p>
<p>Grassland sites:</p>
<table class="caption-top table">
<caption>Table 3: Representativeness of Natura 2000 sites with grassland habitat types per MS.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 18%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Member State</th>
<th>Total</th>
<th>Not Mapped</th>
<th>Partly Mapped</th>
<th>Completely Mapped</th>
<th>% of Completely Mapped Sites</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Austria</td>
<td>199</td>
<td>141</td>
<td>19</td>
<td>39</td>
<td>19,60%</td>
</tr>
<tr class="even">
<td>Belgium</td>
<td>263</td>
<td>139</td>
<td>75</td>
<td>49</td>
<td>18,63%</td>
</tr>
<tr class="odd">
<td>Bulgaria</td>
<td>177</td>
<td>28</td>
<td>49</td>
<td>100</td>
<td>56,50%</td>
</tr>
<tr class="even">
<td>Croatia</td>
<td>138</td>
<td>41</td>
<td>17</td>
<td>80</td>
<td>57,97%</td>
</tr>
<tr class="odd">
<td>Cyprus</td>
<td>27</td>
<td>24</td>
<td>0</td>
<td>3</td>
<td>11,11%</td>
</tr>
<tr class="even">
<td>Czech Republic</td>
<td>303</td>
<td>161</td>
<td>38</td>
<td>104</td>
<td>34,32%</td>
</tr>
<tr class="odd">
<td>Denmark</td>
<td>175</td>
<td>132</td>
<td>29</td>
<td>14</td>
<td>8,00%</td>
</tr>
<tr class="even">
<td>Estonia</td>
<td>243</td>
<td>85</td>
<td>54</td>
<td>104</td>
<td>42,80%</td>
</tr>
<tr class="odd">
<td>Finland</td>
<td>271</td>
<td>256</td>
<td>10</td>
<td>5</td>
<td>1,85%</td>
</tr>
<tr class="even">
<td>France</td>
<td>1103</td>
<td>557</td>
<td>219</td>
<td>327</td>
<td>29,65%</td>
</tr>
<tr class="odd">
<td>Germany</td>
<td>3001</td>
<td>1761</td>
<td>602</td>
<td>638</td>
<td>21,26%</td>
</tr>
<tr class="even">
<td>Greece</td>
<td>120</td>
<td>72</td>
<td>20</td>
<td>28</td>
<td>23,33%</td>
</tr>
<tr class="odd">
<td>Hungary</td>
<td>410</td>
<td>110</td>
<td>76</td>
<td>224</td>
<td>54,63%</td>
</tr>
<tr class="even">
<td>Ireland</td>
<td>74</td>
<td>68</td>
<td>1</td>
<td>5</td>
<td>6,76%</td>
</tr>
<tr class="odd">
<td>Italy</td>
<td>1932</td>
<td>638</td>
<td>343</td>
<td>951</td>
<td>49,22%</td>
</tr>
<tr class="even">
<td>Latvia</td>
<td>130</td>
<td>99</td>
<td>7</td>
<td>24</td>
<td>18,46%</td>
</tr>
<tr class="odd">
<td>Lithuania</td>
<td>179</td>
<td>112</td>
<td>15</td>
<td>52</td>
<td>29,05%</td>
</tr>
<tr class="even">
<td>Luxembourg</td>
<td>48</td>
<td>16</td>
<td>14</td>
<td>18</td>
<td>37,50%</td>
</tr>
<tr class="odd">
<td>Malta</td>
<td>5</td>
<td>1</td>
<td>4</td>
<td>0</td>
<td>0,00%²</td>
</tr>
<tr class="even">
<td>Netherlands</td>
<td>100</td>
<td>79</td>
<td>14</td>
<td>7</td>
<td>7,00%</td>
</tr>
<tr class="odd">
<td>Poland</td>
<td>522</td>
<td>237</td>
<td>74</td>
<td>211</td>
<td>40,42%</td>
</tr>
<tr class="even">
<td>Portugal</td>
<td>83</td>
<td>49</td>
<td>12</td>
<td>22</td>
<td>26,51%</td>
</tr>
<tr class="odd">
<td>Romania</td>
<td>197</td>
<td>77</td>
<td>44</td>
<td>76</td>
<td>38,58%</td>
</tr>
<tr class="even">
<td>Slovakia</td>
<td>437</td>
<td>219</td>
<td>84</td>
<td>134</td>
<td>30,66%</td>
</tr>
<tr class="odd">
<td>Slovenia</td>
<td>67</td>
<td>7</td>
<td>12</td>
<td>48</td>
<td>71,64%</td>
</tr>
<tr class="even">
<td>Spain</td>
<td>1152</td>
<td>346</td>
<td>316</td>
<td>490</td>
<td>42,53%</td>
</tr>
<tr class="odd">
<td>Sweden</td>
<td>1480</td>
<td>1101</td>
<td>79</td>
<td>300</td>
<td>20,27%</td>
</tr>
<tr class="even">
<td>Switzerland</td>
<td>n/a</td>
<td>n/a</td>
<td>n/a</td>
<td>n/a</td>
<td>n/a</td>
</tr>
<tr class="odd">
<td>United Kingdom</td>
<td>178</td>
<td>165</td>
<td>6</td>
<td>7</td>
<td>3,93%</td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td><strong>13014</strong></td>
<td><strong>6721</strong></td>
<td><strong>2233</strong></td>
<td><strong>4060</strong></td>
<td><strong>31,20%</strong></td>
</tr>
</tbody>
</table>
<p><em>² Four sites were chosen for LC/LU mapping but due to spatial query settings, those were registered as “partly mapped”. Manual checks produced a coverage of 4 out of the 5 grasslands sites, resulting in an 80% grassland site coverage.</em></p>
<p>Switzerland as non-EU state is listed in the table because of three Emerald sites there located which are included in the N2K product however it was not included in the representativeness assessment. The Emerald network have some similarities to Natura 2000 network but do not follow exactly the same criteria.</p>
<p>The low numbers of some MS in the two sections of the representativeness assessment are seen as an important indicator for how the results related to these MS can be assessed. In these cases, a projection of the results which derived from a small number of sites, may not represent the situation on the national level.</p>
<p>In conclusion, the mapped Natura 2000 sites are neither equally distributed across Europe nor equally representative of the MS or the Biogeographical regions. The distribution of the selected sites with a high representation are in South, South-western, Central and Eastern Europe whereas the Nordic countries and the British and Irish Isles are underrepresented.</p>
</section>
<section id="natura-2000-boundary-changes-and-the-impact-in-the-clms-n2k-product-area-of-interest-aoi" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="natura-2000-boundary-changes-and-the-impact-in-the-clms-n2k-product-area-of-interest-aoi"><span class="header-section-number">5.4</span> Natura 2000 boundary changes and the impact in the CLMS N2K product Area of Interest (AoI)</h2>
<p>The AoI for mapping the LC/LU was setup, changed and extended throughout the evolution of the CLMS N2K product, in three different phases:</p>
<p><strong><u>First</u></strong>, during the initial setup of the N2K AoI under the GIO project phase (GMES Initial Operation Phase in 2014) a selection of Natura 2000 grassland-rich sites (representing five grassland habitats types, namely, 6210, 6240, 6250, 6510 and 6520) as identified in Annex I of the Habitats Directive was used;</p>
<p>A list of Natura 2000 sites was proposed by EC DG ENV on the basis of their representativeness and relative importance for the given habitat types. The information for selecting sites on the basis of the above criteria has been taken from the Natura 2000 sites’ Standard Data Forms in the most recent version of the EU-wide Natura 2000 database at the time;</p>
<p>Based on this list of Natura 2000 site codes the corresponding site boundaries were extracted from the Natura 2000 Database (version: Natura 2000 v2013). This led to an AOI area of around 150.800 km²;</p>
<p>A GIS- and EO data analysis was then performed to:</p>
<ol type="a">
<li><p>Buffer the Natura 2000 sites by 2km, which increased the N2K AOI area to around 252.600 km²)</p></li>
<li><p>Identify existing VHR satellite coverage for the reference years 2006 +/- 1 year (with extension to +/- 2 years for gap-filling) and 2012 +/- 2 years within defined seasonal windows, so that in combination they reach &gt; 80% coverage of the full (buffered) N2000 site size (i.e.&nbsp;in the same areas, for both time steps). This reduced the AOI to around 162.600 km² - 173.800 km²</p></li>
</ol>
<p>The finally mapped N2K product during the GIO Phase covered 160.443 km².</p>
<p>In the <strong><u>second</u></strong> production phase (started in 2016) the N2K AOI was enlarged. Additional Natura 2000 sites were selected, now based on a list of 32 different Annex 1 grassland habitat types as defined under the Habitats Directive. The additional Natura 2000 site boundaries were again taken from the Natura 2000 Database (this time from version: end2015). The buffer was applied to the newly selected sites and minor adaptations to the N2K AoI were made to correct imprecisions and omission errors. This changed the AoI size and geometry in a way that:</p>
<ul>
<li><p>Missing 2km buffers were included, for mainly buffers around islands were missing</p></li>
<li><p>Wrongly clipped buffers of selected N2K sites were included</p></li>
<li><p>Existing gaps between N2K sites shapefile and EEA39 member states boundary shapefile were filled. Regarding water areas, those gaps over water appeared if EEA39 boundaries do not coincide with N2K site boundaries along coastlines and had also to be corrected and included</p></li>
<li><p>Minor gaps and spikes between the AoIs of the first and second phases were corrected and included</p></li>
<li><p>Small angles (&lt;20°) were checked and corrected where feasible.</p></li>
</ul>
<p>In the end of the second production phase, the existing 160.443km² were complemented by 471.377 km² leading to the N2K product covering 631.820 km² for the reference years 2006 and 2012.</p>
<p>In the <strong><u>third</u></strong> production phase (started in 2020 and finished in May 2021) the N2K product is updated to the reference year 2018, including the change layer 2012-2018. No changes were applied to the geographic coverage of the product.</p>
<p>The option taken for the N2K product was to have a stable AoI so that the change mapping exercise could be done within the same area and that the derived statistics were not affected by changing AoI’s.</p>
<p>As can be seen from the above “<em>history</em>” of the N2K AoI creation process, there were several input data sets used as well as several geospatial corrections applied to generate the currently used N2K coverage of 631.820km². As stated above there are several factors which prevent a 1:1 relation between the N2K AoI and Natura 2000 site boundaries:</p>
<ul>
<li><p>Different Natura 2000 database versions were applied to generate the unbuffered N2K site selection (version Natura 2000 v2013 and later version end2015). Changes in the yearly updated Natura 2000 site definitions were not adapted for already mapped N2K sites (Figure 4)</p></li>
<li><p>N2K AoI adaptations to achieve a technically “clean” dataset may have led to deviations from a strict 2km buffer zone around each selected Natura 2000 site.</p></li>
<li><p>The availability of archived VHR satellite data for the reference years 2006 and 2012 required a threshold to produce N2K LC/LU information also for Natura 2000 sites covered by up to a minimum of 80% satellite data.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image14.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4: Example of diverging Natura 2000 site boundaries (red 2015 version, blue 2019 version, grey N2K product coverage incl.&nbsp;the 2km buffer)</figcaption>
</figure>
</div>
<p>Also, due to the buffering of the Natura 2000 sites by 2km, the N2K sites may actually cover more than one Natura 2000 site (Figure 5). This has been one the reasons for the removal of the Natura 2000 <strong><u>Site code</u></strong> from the N2K AoI, to avoid a misinterpretation of the data. Because within the same N2K polygon there could be reference to more than one Natura 2000 site.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image15.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5 - Example of N2K AoI (red) covering multiple N2K sites (black)</figcaption>
</figure>
</div>
<p>To quantify the effects of the changing Natura 2000 Database on the N2K products a spatial analysis of the Natura 2000 database changes between 2015 and 2018 was performed.</p>
<p>During the data preparation it became evident, that the Natura 2000 databases are more complex than expected. The Natura 2000 sites are very often defined as “multi-part” polygons (Figure 6). This means that multiple detached areas form together one Natura 2000 site. Due to the above described N2K AoI creation process, Natura 2000 sites are not always covered by the N2K product for all their single areas. This is an important fact, if N2K products are related to Standard Data Form (SDF) information, e.g.&nbsp;Habitat coverage within site, which relates to the complete Natura 2000 site.</p>
<p>For this all Natura 2000 sites affected by the full N2K AoI were selected from the 2015 Natura 2000 Database (version: end2015). This resulted in 3872 different site codes. Performing the same process to the 2018 Natura 2000 Database (version: end2018) led to 3868 site codes. Four site codes have changed between 2015 and 2018. Here the Natura 2000 sites had a newer release data. This was for example the case for the Danish site code DK00BX044 in 2015, which was split up into two new site codes DK00BB396 and DK00BB380 (Figure 7). The four changed site codes were also included in the spatial analysis of the 2018 data.</p>
<p>Other Natura 2000 DB changes led to a partial coverage of 2018 geometries of formerly fully covered in 2015 (Figure 8). Partially these changes might still be covered by the N2K AoI, but initially the original 2km buffer around the site is no longer valid for the complete site (Figure 9).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image16.png" class="img-fluid figure-img"></p>
<figcaption>Figure 6 - Example of multi-part Natura 2000 site (AT3210001) only partially covered by N2K AOI</figcaption>
</figure>
</div>
<p><img src="N2K-media/image17.jpeg" class="img-fluid"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image18.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 7 - Example of changed site codes and geometries from 2015 (top) to 2018 (bottom) Natura 2000 DB version</figcaption>
</figure>
</div>
<p><img src="N2K-media/image19.jpeg" class="img-fluid"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image20.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 8 - Example of Natura 2000 DB site changes from 2015 (top) to 2018 (bottom). Background N2K AOI</figcaption>
</figure>
</div>
<p><img src="N2K-media/image21.jpeg" class="img-fluid"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image22.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 9 - More examples of Natura 2000 DB site changes from 2015 (top) to 2018 (bottom). Background N2K AOI</figcaption>
</figure>
</div>
<p>The Natura 2000 site boundaries were intersected with the N2K AoI for both years to analyse the total area covered by the Natura 2000 sites, and their spatial overlap with the N2K AoI. Due to the fact that there are overlapping geometries in the Natura 2000 sites DB (Figure 10), the analysis was performed also with the Natura 2000 sites merged to one analysis extent.</p>
<p>The results showed that more than 98% of the area covered by the selected grassland-rich Natura 2000 sites is covered by the N2K product in for both Natura 2000 site definitions, version end2015 and end2018 (Figure 5).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image23.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 10 - Example of Natura 2000 DB site overlap. The site codes IT6020025, IT7120201 and IT5340010 overlay the area of site code IT7110128.</figcaption>
</figure>
</div>
<table class="caption-top table">
<caption>Table 4 - Spatial coverage of Natura 2000 DB sites by N2K AOI in 2015 and 2018</caption>
<colgroup>
<col style="width: 57%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: left;"><strong>2015</strong></th>
<th style="text-align: left;"><strong>2018</strong></th>
<th style="text-align: left;"><strong>Difference 2015-2018</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total area of Natura 2000 sites (with overlaps) [km²]</td>
<td style="text-align: left;">284.195,48</td>
<td style="text-align: left;">284.977,85</td>
<td style="text-align: left;">+ 782,37</td>
</tr>
<tr class="even">
<td>Total area of Natura 2000 sites (without overlaps) [km²]</td>
<td style="text-align: left;">272.483,95</td>
<td style="text-align: left;">273.266,93</td>
<td style="text-align: left;">+ 782,98</td>
</tr>
<tr class="odd">
<td>Area of Natura 2000 sites (without overlap) covered by N2K AOI [km²]</td>
<td style="text-align: left;">267.820,37</td>
<td style="text-align: left;">268.167,05</td>
<td style="text-align: left;">+ 346,68</td>
</tr>
<tr class="even">
<td>Percentage of Natura 2000 area covered by N2K AOI (without overlaps) [%]</td>
<td style="text-align: left;">98,3</td>
<td style="text-align: left;">98,1</td>
<td style="text-align: left;">- 0,2</td>
</tr>
</tbody>
</table>
<p>Comparing the spatial dynamics of the 2015 and 2018 Natura 2000 site boundaries in comparison to the current N2K AOU showed that the selected sites in the 2018 Natura 2000 DB had around 537 km² area removed, which was still contained in the 2015 DB version, whereas around 1.320 km² were newly added in the 2018 DB version. Of this newly added area, 66% was still covered by the unchanged N2K AOI (Figure 6).</p>
<table class="caption-top table">
<caption>Table 5 - Area changes for Natura 2000 DB sites from 2015 to 2018</caption>
<colgroup>
<col style="width: 40%">
<col style="width: 35%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Natura 2000 area changes 2015-2018</strong></th>
<th></th>
<th style="text-align: right;"><strong>Value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Common area in 2015 and 2018</td>
<td></td>
<td style="text-align: right;">271.946,91 km²</td>
</tr>
<tr class="even">
<td style="text-align: left;">Area only in 2015 data (removed)</td>
<td></td>
<td style="text-align: right;">537,04 km²</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Area only in 2018 data (new)</td>
<td></td>
<td style="text-align: right;">1320,02 km²</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td>covered by N2K AOI (Inside)</td>
<td style="text-align: right;">871,79 km² (66 %)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td>not covered by N2K AOI (Outside)</td>
<td style="text-align: right;">448,23 km² (44 %)</td>
</tr>
</tbody>
</table>
<p>The boundaries of Natura 2000 may change from year to year but usually those are not dramatic changes and are usually covered by the 2km buffer zone. There are however a few occasions when a change in extent may have gone over the N2K established AoI. Extreme situation illustrated below (Figure 11)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image24.png" class="img-fluid figure-img"></p>
<figcaption>Figure 11 – Example of a Natura 2000 site change in extent (enlargement): the green buffer follows the shape of the site in 2012, but in the 2018 Natura 2000 database the site has been enlarged therefore not anymore totally covered by the N2K AoI</figcaption>
</figure>
</div>
<p>This was one of the reasons why it was decided to <strong><u>remove the Natura 2000 site boundary from the N2K product:</u></strong> to allow users to use the N2K LC/LU product in combination with the Natura 2000 latest boundary, if they wish so in their dedicated assessments therefore not being bound by an outdated outline that may change on a yearly basis.</p>
</section>
<section id="clms-n2k-status-layer" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="clms-n2k-status-layer"><span class="header-section-number">5.5</span> CLMS N2K status layer</h2>
<p>The N2K status layer represents the LC/LU status identified on the available satellite images for the specific reference year (Figure 12).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/image25.png" class="img-fluid figure-img"></p>
<figcaption>Figure 12: CLMS N2K status product 2018. Example for a selected Natura 2000 site (DE4617303 Kalkkuppen near Brilon, Germany).</figcaption>
</figure>
</div>
</section>
<section id="clms-n2k-change-layer" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="clms-n2k-change-layer"><span class="header-section-number">5.6</span> CLMS N2K change layer</h2>
<p>The CLMS N2K change layer represents the LC/LU changes between the specific reference years and identifiable on the satellite images (Figure 13).</p>
<p><img src="N2K-media/image26.png" class="img-fluid"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./N2K-media/image27.png" class="img-fluid figure-img"></p>
<figcaption>Figure 13: CLMS N2K Change product 2006-2012 (top) and 2012-2018 (bottom). Example for a selected Natura 2000 site (DE4617303 Kalkkuppen bei Brilon, Germany). Yellow = LC/LU changes mapped between reference years, Blue = CLMS N2K site extent</figcaption>
</figure>
</div>
</section>
<section id="technical-specification" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="technical-specification"><span class="header-section-number">5.7</span> Technical specification</h2>
<p>Table 6 summarizes the technical specifications of the N2K product.</p>
<table class="caption-top table">
<caption>Table 6: Product overview sheet</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 34%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th>LC/LU status 2018</th>
<th>LC/LU status 2012 (revised)</th>
<th>LC/LU status 2006 (revised)</th>
<th>LC/LU change 2006–2012 (revised)</th>
<th>LC/LU change 2012–2018</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Temporal description (VHR coverage reference dates)</td>
<td>2018 (± 1 year)</td>
<td>2012 (± 2 years, due to data availability)</td>
<td>2006 (± 2 years, due to data availability)</td>
<td>2006 and 2012</td>
<td>2012 and 2018</td>
</tr>
<tr class="even">
<td>Overall thematic classification accuracy: LC/LU status and change layers</td>
<td>≥ 85 % overall accuracy</td>
<td>≥ 85 % overall accuracy</td>
<td>≥ 85 % overall accuracy</td>
<td>≥ 85 % overall accuracy</td>
<td>≥ 80 % overall accuracy</td>
</tr>
<tr class="odd">
<td></td>
<td>≥ 80 % for class specific user and producer accuracies</td>
<td>≥ 80 % for class specific user and producer accuracies</td>
<td></td>
<td>≥ 80 % for class specific user and producer accuracies</td>
<td></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th>Applicable to all LC/LU statuses</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geographic Coverage</td>
<td>~ 631 820 km² across EU27 and the UK and Switzerland (N2K sites including 2km buffer); including three Emerald sites in Switzerland</td>
</tr>
<tr class="even">
<td>Minimum Mapping Unit (MMU)</td>
<td>0.5 ha*</td>
</tr>
<tr class="odd">
<td>Minimum Mapping Width (MMW)</td>
<td>10 m**</td>
</tr>
<tr class="even">
<td>Nomenclature</td>
<td>CLMS N2K Nomenclature and Mapping Guideline (Issue 1.4)</td>
</tr>
<tr class="odd">
<td>Projection</td>
<td>ETRS89 Lambert Azimuthal Equal Area (LAEA) (EPSG 3035)</td>
</tr>
<tr class="even">
<td>Delivery format</td>
<td>LC/LU data: ESRI file geodatabase and GeoPackage, containing the three status (2006,2012,2018) and two change layers (2006–2012, 2012–2018)</td>
</tr>
<tr class="odd">
<td>Ancillary information layer</td>
<td>Parent Scene Identification Layer (PSIL); vector file containing spatial reference information on the satellite images used for producing the LC/LU map (on demand – send email to copernicus@eea.europa.eu)</td>
</tr>
<tr class="even">
<td>Positional accuracy</td>
<td>RMSE ≤ 5 meters</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>* Some exceptions are allowed for polygons at the product boundary and polygons inside the boundary related to linear networks or urban areas and for change polygons in very specific cases.</p>
<p>** Exceptions of 10m over a distance of up to 100m are allowed to maintain continuity of features with mostly linear nature.</p>
</blockquote>
<p>The CLMS N2K products are delivered as polygon vector data for the reference years over the selected sites across Europe. Each product is delivered as a separate data set, following a uniform technical specification. The content of a download package is explained below:</p>
<p>Each download package is a *.zip file which contains three folders:</p>
<ul>
<li><p><strong><u>DATA</u></strong> (contains the data files in fgdb and geoPackage formats):</p>
<ul>
<li><p>LC/LU status map 2006: LC/LU based on the analysis of satellite images from the reference year period 2006.</p>
<ul>
<li><span data-custom-style="NormalLine">File name: N2K_2006_3035_v010</span><br>
</li>
</ul></li>
<li><p>LC/LU status map 2012: LC/LU based on the analysis of satellite images from the reference year period 2012.</p>
<ul>
<li><span data-custom-style="NormalLine">File name: N2K_2012_3035_v010</span><br>
</li>
</ul></li>
<li><p>LC/LU status map 2018: LC and LU classification based on the analysis of satellite images from the reference year period 2018.</p>
<ul>
<li><span data-custom-style="NormalLine">File name: N2K_2018_3035_v010</span><br>
</li>
</ul></li>
<li><p>LC/LU change map 2006-2012: based on the outputs of the 2012 and 2006 status layers.</p>
<ul>
<li><span data-custom-style="NormalLine">File name: N2K_Change_2006_2012_3035_v010</span><br>
</li>
</ul></li>
<li><p>LC/LU change map 2012-2018: LC/LU change information based on the comparison of satellite images from the reference year periods 2012 and 2018. The production of this product is the basis for the status map for 2018 as well as for the revision of the previous time steps 2012 and 2006.</p>
<ul>
<li><span data-custom-style="NormalLine">File name: N2K_Change_2012_2018_3035_v010</span><br>
</li>
</ul></li>
</ul></li>
<li><p><strong><u>SYMBOLOGY</u></strong></p></li>
</ul>
<p>Contains symbology files in three formats: lyr, sld and qml</p>
<ul>
<li><strong><u>METADATA</u></strong></li>
</ul>
<p>Contains metadata file in XML format</p>
<p>FILE NAMING CONVENTION:</p>
<p>The filename is composed of a combination of information about the data theme, the reference year/reference period, EPSG code and version number.</p>
<p>| THEME| REFERENCE YEAR/REFERENCE PERIOD | EPSG CODE | VERSION</p>
<p>THEME:</p>
<ul>
<li>theme refers to specific layer type: N2K - refers to status layer, N2K_Change - refers to change layer</li>
</ul>
<p>REFERENCE YEAR:</p>
<ul>
<li>reference year refers to the year for which N2K information included in the file were mapped: 2006, 2012, 2018,</li>
</ul>
<p>REFERENCE PERIOD:</p>
<ul>
<li>reference period refers to the period for which N2K change information were mapped: 2006-2012, 2012-2018</li>
</ul>
<p>All products contain information on the LC/LU class as well as auxiliary information (e.g.&nbsp;on temporal dynamics of the mapped polygon, or change related area size exceptions). The attribute information is given per polygon following a standardized attribution scheme (Table 7 and Table 8).</p>
<table class="caption-top table">
<caption>Table 7: Product attribute definition for the table LC_LU (ESRI GDB representation)</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 55%">
<col style="width: 7%">
<col style="width: 22%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Description</th>
<th>Type</th>
<th>Value(s)</th>
<th>Applicable Products</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>[OBJECTID]</td>
<td>Dynamic Feature Identifier</td>
<td>Object ID</td>
<td>0 to 2.147.483.647</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[Shape]</td>
<td>Polygon (default by ESRI)</td>
<td>Geometry</td>
<td>Polygon</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[UID]</td>
<td>Unique Identifier of the feature geometry, generated as combination of OBJECTID and DeliveryUnit-ID in the form of “ID_OBJECTID+1”</td>
<td>String, Length 20</td>
<td>Starting from 1_1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_1_18]</td>
<td>Class code of LC/LU Level 1 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>1 to 10</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_2_18]</td>
<td>Class code of LC/LU Level 2 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>11 to 101</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_3_18]</td>
<td>Class code of LC/LU Level 3 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>111 to 1011</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_4_18]</td>
<td>Class code of LC/LU Level 4 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>1111 to 10111</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[COMMENT_18]</td>
<td>Comment field for additional information for LC/LU 2018</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>[NODATA_18]</td>
<td>Unclassifiable area due to clouds, shadows, snow, haze or missing data (no satellite data available)</td>
<td>Long, Precision 9</td>
<td>0,1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_1_12]</td>
<td>Class code of LC/LU Level 1 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>1 to 10</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_2_12]</td>
<td>Class code of LC/LU Level 2 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>11 to 101</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_3_12]</td>
<td>Class code of LC/LU Level 3 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>111 to 1011</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_4_12]</td>
<td>Class code of LC/LU Level 4 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>1111 to 10111</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[COMMENT_12]</td>
<td>Comment field for additional information for LC/LU 2012</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>[NODATA_12]</td>
<td>Unclassifiable area due to clouds, shadows, snow, haze or missing data (no satellite data available)</td>
<td>Long, Precision 9</td>
<td>0,1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_1_06]</td>
<td>Class code of LC/LU Level 1 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>1 to 10</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_2_06]</td>
<td>Class code of LC/LU Level 2 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>11 to 101</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_3_06]</td>
<td>Class code of LC/LU Level 3 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>111 to 1011</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_4_06]</td>
<td>Class code of LC/LU Level 4 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>1111 to 10111</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[COMMENT_06]</td>
<td>Comment field for additional information for LC/LU 2006</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>[NODATA_06]</td>
<td>Unclassifiable area due to clouds, shadows, snow, haze or missing data (no satellite data available)</td>
<td>Long, Precision 9</td>
<td>0,1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CHANGECODE]</td>
<td>Change Class code of LC/LU Level 4 for LC/LU 2006–2012 (<em>CODE_4_06_CODE_4_12</em>) or 2012–2018 (<em>CODE_4_12_CODE_4_18</em>)</td>
<td>String, Length 11</td>
<td>1111_1111 to 10111_10111</td>
<td>Change</td>
</tr>
<tr class="odd">
<td>[COMMENT]</td>
<td>Comment field for additional information for change products LC/LU 2006–2012, 2012–2018</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Change</td>
</tr>
<tr class="even">
<td>[AREA_HA]</td>
<td>Area in hectare [ha]</td>
<td>Double</td>
<td>0.001 to 1.8E308</td>
<td>Status, Change</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<caption>Table 8: Product attribute definition for the table LC_LU (GeoPackage .gpkg representation)</caption>
<colgroup>
<col style="width: 7%">
<col style="width: 61%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Description</th>
<th>Type</th>
<th>Value(s)</th>
<th>Status, Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>[OBJECTID]</td>
<td>Dynamic Feature Identifier</td>
<td>Object ID</td>
<td>0 to 2.147.483.647</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[Shape]</td>
<td>Polygon (default by ESRI)</td>
<td>Geometry</td>
<td>Polygon</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[UID]</td>
<td>Unique Identifier of the feature geometry, generated as combination of OBJECTID and DeliveryUnit-ID in the form of “ID_OBJECTID+1”</td>
<td>String, Length 20</td>
<td>Starting from 1_1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_1_18]</td>
<td>Class code of LC/LU Level 1 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>1 to 10</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_2_18]</td>
<td>Class code of LC/LU Level 2 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>11 to 101</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_3_18]</td>
<td>Class code of LC/LU Level 3 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>111 to 1011</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_4_18]</td>
<td>Class code of LC/LU Level 4 for LC/LU 2018</td>
<td>Long, Precision 9</td>
<td>1111 to 10111</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[COMMENT_18]</td>
<td>Comment field for additional information for LC/LU 2018</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>[NODATA_18]</td>
<td>Unclassifiable area due to clouds, shadows, snow, haze or missing data (no satellite data available)</td>
<td>Long, Precision 9</td>
<td>0,1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_1_12]</td>
<td>Class code of LC/LU Level 1 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>1 to 10</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_2_12]</td>
<td>Class code of LC/LU Level 2 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>11 to 101</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_3_12]</td>
<td>Class code of LC/LU Level 3 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>111 to 1011</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_4_12]</td>
<td>Class code of LC/LU Level 4 for LC/LU 2012</td>
<td>Long, Precision 9</td>
<td>1111 to 10111</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[COMMENT_12]</td>
<td>Comment field for additional information for LC/LU 2012</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>[NODATA_12]</td>
<td>Unclassifiable area due to clouds, shadows, snow, haze or missing data (no satellite data available)</td>
<td>Long, Precision 9</td>
<td>0,1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_1_06]</td>
<td>Class code of LC/LU Level 1 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>1 to 10</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_2_06]</td>
<td>Class code of LC/LU Level 2 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>11 to 101</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CODE_3_06]</td>
<td>Class code of LC/LU Level 3 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>111 to 1011</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>[CODE_4_06]</td>
<td>Class code of LC/LU Level 4 for LC/LU 2006</td>
<td>Long, Precision 9</td>
<td>1111 to 10111</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[COMMENT_06]</td>
<td>Comment field for additional information for LC/LU 2006</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>[NODATA_06]</td>
<td>Unclassifiable area due to clouds, shadows, snow, haze or missing data (no satellite data available)</td>
<td>Long, Precision 9</td>
<td>0,1</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>[CHANGECODE]</td>
<td>Change Class code of LC/LU Level 4 for LC/LU 2006–2012 (<em>CODE_4_06_CODE_4_12</em>) or 2012–2018 (<em>CODE_4_12_CODE_4_18</em>)</td>
<td>String, Length 11</td>
<td>1111_1111 to 10111_10111</td>
<td>Change</td>
</tr>
<tr class="odd">
<td>[COMMENT]</td>
<td>Comment field for additional information for change products LC/LU 2006–2012, 2012–2018</td>
<td>String, Length 254</td>
<td>Standardized text comments, separated by Semicolon</td>
<td>Change</td>
</tr>
<tr class="even">
<td>[AREA_HA]</td>
<td>Area in hectare [ha]</td>
<td>Double</td>
<td>0.001 to 1.8E308</td>
<td>Status, Change</td>
</tr>
</tbody>
</table>
<p>The standardized entries for [COMMENT], [COMMENT_18], [COMMENT_12] and [COMMENT_06] are separated by a semicolon in increasing order following their “Order No” (Table 9).</p>
<table class="caption-top table">
<caption>Table 9: List of allowed [COMMENT] and [COMMENT_XX] entries</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 15%">
<col style="width: 76%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>Order No</th>
<th>Entry Value</th>
<th>Description / Note</th>
<th>Applicable Products</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Area size exception (at Natura2000 AoI boundary)</td>
<td>Polygons &lt; 0.5 ha at outer AoI site boundary, that have an apparent continuation outside the AoI boundary, which is visible on the image data.</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>2</td>
<td>Area size exception (inside Natura2000 AoI boundary)</td>
<td>Polygons &lt; 0.5 ha inside AoI site boundary, that are allowed due to nomenclature guideline rules e.g.&nbsp;to represent changes, to ensure continuity of road/rail/river network at intersections of these classes, to mark urban objects confined by roads or railways ≥ 0.25 ha up to &lt; 0.5 ha</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Splitted change</td>
<td>Changes over several classes. Each change is &lt; 0.5 ha but overall change (=sum of individual change areas) is &gt; 0.5 ha.</td>
<td>Change</td>
</tr>
<tr class="even">
<td>4</td>
<td>Areas related to change</td>
<td>Polygons &lt; 0.5 ha with no change but connected to change polygons (same code at a neighbouring polygon in one of the two years).</td>
<td>Status</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Temporal fluctuation of water level</td>
<td>Different water levels in comparison of image data taken during dry/wet season and conditions. The water level situation of the reference year 2012 should be used for delineation. A flood event is not considered as a “Temporal fluctuation of water level”.</td>
<td>Status, Change</td>
</tr>
<tr class="even">
<td>6</td>
<td>Flooded area</td>
<td>Used for extraordinary flooding events where non-water land cover features are covered (partly or fully) by water. Comment is applied only in the year of the flooding event.</td>
<td>Status, Change</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Braided River</td>
<td>For river banks that are crossed by side arms of a river. Only valid for MAES_4 Code 6213 (river banks).</td>
<td>Status, Change</td>
</tr>
</tbody>
</table>
</section>
<section id="clms-n2k-nomenclature" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="clms-n2k-nomenclature"><span class="header-section-number">5.8</span> CLMS N2K nomenclature</h2>
<p>The Nomenclature for the LC/LU dataset is structured into four levels (Code level 1- Code level 4). There are 55 different LC/LU classes (Table 10). The detailed description of each class is given in the N2K nomenclature and mapping guideline (AD01). The LC/LU code levels were designed to correspond to the Mapping and Assessment of Ecosystems and their Services (MAES) typology Level 2 (EU 2013).</p>
<p><img src="N2K-media/Table1.png" class="img-fluid"></p>
<p><img src="N2K-media/Table2.png" class="img-fluid"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="N2K-media/Table3.png" class="img-fluid figure-img"></p>
<figcaption>Table 10: CLMS N2K nomenclature overview (v1.4, dated 03.05.2021)</figcaption>
</figure>
</div>
</section>
</section>
<section id="product-methodology-and-workflow" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Product methodology and workflow</h1>
<p>The CLMS N2K production is based on a three-tier approach (Figure 14). The presented workflow is valid for the 2018 production update cycle. Core to the project is the step visual <em>Interpretation and Classification</em> of LC/LU changes with respect to new VHR satellite information for the reference year 2018.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./N2K-media/image28.png" class="img-fluid figure-img"></p>
<figcaption>Figure 14: Production workflow for CMLS N2K products</figcaption>
</figure>
</div>
<section id="data-pre-processing" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="data-pre-processing"><span class="header-section-number">6.1</span> Data Pre-Processing</h2>
<p>During the <em>Data Pre-Processing</em> almost cloud-free VHR optical datasets covering EEA39 (VHR_IMAGE_2018, VHR 2018 Enhanced), are prepared for the status layer 2018 production. This VHR imagery has been acquired within predefined time windows corresponding to the vegetation season 2018 (±1 year), with a spectral resolution comprising visible and NIR bands.</p>
<p>It is a mix of primary satellite missions (Pléiades 1A &amp; 1B, SuperView-1, KOMPSat-3/3-A and PlanetScope) and backup missions (SPOT-6/-7, TripleSat and Deimos-2) at a spatial resolution of 2-4m. Additional in-situ and ancillary datasets relevant for the CLMS N2K production are also integrated into the production workflow to support the LC/LU analysis.</p>
<p>For the change mapping 2012-2018 and the revision of the formerly produced 2006 and 2012 data, the following ESA data sources are used for the reference years 2006 (± 2 years) and 2012 (±2 years):</p>
<ul>
<li><p>D2_MG2b_LOLA_011b</p></li>
<li><p>DAP_MG2b_01</p></li>
<li><p>DWH_MG2_CORE_02</p></li>
<li><p>DWH_MG2b_CORE_03</p></li>
<li><p>Natura 2000_Data_Procurement</p></li>
<li><p>VHR_IMAGE_2015</p></li>
<li><p>D2_MG2b_NARA_011b</p></li>
</ul>
<p>The satellite data provided via these ESA data sources include different sensor types:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 66%">
</colgroup>
<tbody>
<tr class="odd">
<td><ul>
<li>Deimos-02</li>
</ul></td>
<td><ul>
<li>SPOT-4</li>
</ul></td>
</tr>
<tr class="even">
<td><ul>
<li>Planet DOVE</li>
</ul></td>
<td><ul>
<li>SPOT-5</li>
</ul></td>
</tr>
<tr class="odd">
<td><ul>
<li>Quickbird 02</li>
</ul></td>
<td><ul>
<li>SPOT-6</li>
</ul></td>
</tr>
<tr class="even">
<td><ul>
<li>GeoEye 01</li>
</ul></td>
<td><ul>
<li>SPOT-7</li>
</ul></td>
</tr>
<tr class="odd">
<td><ul>
<li>IRS-P6-LISS III</li>
</ul></td>
<td><ul>
<li>SuperView</li>
</ul></td>
</tr>
<tr class="even">
<td><ul>
<li>Kompsat 03/04</li>
</ul></td>
<td><ul>
<li>TripleSat</li>
</ul></td>
</tr>
<tr class="odd">
<td><ul>
<li>Pleiades 1A</li>
</ul></td>
<td><ul>
<li>WorldView 1</li>
</ul></td>
</tr>
<tr class="even">
<td><ul>
<li>Pleiades 1B</li>
</ul></td>
<td><ul>
<li>WorldView 2</li>
</ul></td>
</tr>
</tbody>
</table>
<p>Additionally, to overcome cloud problems in restricted areas Sentinel 2 from ESA for 2018 and Landsat 5 and Landsat 8 data from USGS (United States Geological Survey) are used for the reference dates 2006 and 2012 respectively.</p>
</section>
<section id="interpretation-and-classification" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="interpretation-and-classification"><span class="header-section-number">6.2</span> Interpretation and Classification</h2>
<p>The <em>Interpretation and Classification</em> procedures follow the mapping rules and principles as stated in the CLMS N2K Nomenclature and Mapping Guideline (AD01). This documentation refers specifically to object delineation; MMU and MMW; feature extraction priority rules; water level mapping rules; handling of geometric inconsistencies between the reference years; inclusion of additional data sources and the application of standardized data attributes. Feature delineation is applied at a 1:5.000 mapping scale.</p>
<p><strong>Mapping LC/LU Status</strong></p>
<p>The LC/LU status is mapped through a visual interpretation and object delineation using the above specified VHR data as primary data source. The type of LC/LU is classified according to the CLMS N2K Nomenclature and Mapping Guideline document (AD01). A minimum mapping unit (MMU) of ≥ 0.5 ha for all objects applies. A minimum width (MMW) of ≥ 10 m is defined. MMU exceptions are allowed for:</p>
<ul>
<li><p>Objects located at a CLMS N2K product border: If an object is cut at a border, the feature is mapped, if the whole object (inside and outside the border) would amount to ≥ 0.5 ha. However, the MMU of those divided features lying inside the site shall have a MMU of at least ≥ 0.1 ha. Smaller objects will be generalized.</p></li>
<li><p>Complex changes (see changes examples below).</p></li>
<li><p>Linear features (roads, railways, rivers) that are split in two or more polygons by other linear elements (e.g.&nbsp;the road/railway network) will be mapped even if the resulting segments are smaller than the MMU in order to preserve the network. However, features &lt; 0.1 ha will be generalized.</p></li>
<li><p>Urban objects which are confined by roads or railways. Features &lt; 0.25 ha will be generalized.</p></li>
</ul>
<p>MMW exceptions are allowed:</p>
<ul>
<li>To maintain continuity of features with mostly linear nature (Codes 1.2.1, 1.2.2, 6.2.1, 6.2.2, 8.1.1 and 8.1.2), the MMW may fall below the limit of 10 m over a distance of up to 100 m.</li>
</ul>
<p><strong>Mapping LC/LU Changes</strong></p>
<p>Land Cover Changes (LCC) are changes that occur between the different reference timespans 2006 (+/- 2 years), 2012 (+/- 2 years) and the timespan 2018 (+/-&nbsp;1 year). Differences resulting from different interpretations of the same subject are not considered as change. A change is mapped if it covers over a Minimum Mapping Unit (MMU) of &gt;0.5ha. The mapping is carried out by visual interpretation and comparison of two subsequent reference years (2006-2012, 2012-2018) and their corresponding LC/LU vector data and satellite imagery. Changed areas are directly delineated. In CLMS N2K changes are provided as separate vector products (2006-2012 and 2012-2018).</p>
<p>Possible prone to change areas are, for example:</p>
<ul>
<li><p>Construction sites;</p></li>
<li><p>Abandoned land/grassland/cropland near urban areas;</p></li>
<li><p>Damaged forest indicates that a regrowth of forest should appear;</p></li>
<li><p>Transitional woodland indicates that a regrowth of forest should appear.</p></li>
</ul>
<p>Interpreters must be aware that not every change visible on the images should be treated as changes, e.g.:</p>
<ul>
<li><p>transient phenomena such as floods and temporary water-logging;</p></li>
<li><p>seasonal changes in Natural vegetation;</p></li>
<li><p>seasonal changes in agriculture, such as effects of crop rotation on arable land;</p></li>
<li><p>forest plantation growth, still not reaching the height and/or canopy closure of forest;</p></li>
<li><p>seasonal changes of water level;</p></li>
<li><p>temporal changes in water cover of fishpond cassettes being part of their management;</p></li>
<li><p>seasonal changes of snow spots in high mountains.</p></li>
</ul>
<p>The introduction of false changes must also be avoided. Many of these can and should be excluded by pure logics. These vary from country to country (e.g.&nbsp;while normally sea water do not change into pasture, it might happen in the Netherlands), thus following examples are not exhaustive and not binding for all cases. However, in most cases they can be considered valid.</p>
<p>Highly non-probable changes are for example:</p>
<ul>
<li><p>Urban areas to non-urban classes (1.1.1 🡺 2.-8.x.x): urban areas seldomly disappear</p></li>
<li><p>Conversion of a highly modified water course (e.g.&nbsp;canal) to a new class (8.1.2 🡺 X.X.X)</p></li>
</ul>
<p>Being the most frequently occurring change type, changes &gt; 0.5 ha connected to an existing CLMS N2K polygon are always mapped. In the following example scheme an existing urban site has been enlarged by more than 0.5ha between the reference year t0 (1.1.1) and the reference year t+1.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./N2K-media/image29.png" class="img-fluid figure-img"></p>
<figcaption>Figure 15: Simple change mapping</figcaption>
</figure>
</div>
<p>Although the MMU for change mapping is 0.5 ha, in some cases single changes &lt; 0.5 ha are also mapped together. When a polygon, existing for the reference year t0, is split at the later t1 reference into several other areas (e.g.&nbsp;a road construction, urban growth, …), the individually connected change parts can be mapped together, if they make up a ≥ 0.5 ha complex change polygon. Resulting polygons in the database &lt;0.5ha receive the COMMENT attribute “Area size exception (inside Natura2000 AoI boundary)” (see chapter Technical specification and AD01).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./N2K-media/image30.png" class="img-fluid figure-img"></p>
<figcaption>Figure 16: Complex change mapping. Individual changes with each MMU &lt; 0.5 ha make up a change area of 0.5 ha.</figcaption>
</figure>
</div>
<p>“Splitted” changes can also lead to change polygons &lt;0.5ha. In the example scheme below, an existing industrial site exists in the image t0, but is not mapped in the CLMS N2K product for t0, because it is below the MMU (&lt;0.5ha). The site has enlarged between t0 and t+1 and now forms together an area &gt;0.5ha. The small industrial area from t0 “changes” now as well and forms together with the actual change a complex change area. The formerly too small area receives the COMMENT “Splitted change”.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./N2K-media/image31.png" class="img-fluid figure-img"></p>
<figcaption>Figure 17: New established feature with splitted change.</figcaption>
</figure>
</div>
<p>Exceptions for a polygon &lt;0.5 ha are also allowed for unchanged areas in relation to a change situation. In the following example, an existing road in t0 is relocated. Previous road sections change to an urban class (1.1.1) and previous urban area changes to new road (1.2.1) in t+1. A small road section (&lt;0.5 ha) remains as road over the years and does not change. It gets the comment “Areas related to change” in the CLMS N2K product.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./N2K-media/image32.png" class="img-fluid figure-img"></p>
<figcaption>Figure 18: Area related to change within road relocation.</figcaption>
</figure>
</div>
</section>
</section>
<section id="quality-assessment" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Quality assessment</h1>
<section id="internal-thematic-validation" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="internal-thematic-validation"><span class="header-section-number">7.1</span> Internal thematic validation</h2>
<p>For each CLMS N2K product a thematic validation was performed by the service providers (internal thematic validation). The assessment is based on a scientifically and statistically sound stratification and sampling scheme, tailored to assessing the thematic accuracy of the N2K LC/LU status and change layers.</p>
<p>During the production phase of the 2018 update the following accuracies applied to these products:</p>
<ul>
<li><p>CLMS N2K LC/LU status map 2012 and 2018: ≥ 85 % overall accuracy and ≥ 80 % for class-specific user’s and producer’s accuracies</p></li>
<li><p>CLMS N2K LC/LU change map 2012-2018: ≥ 85 % overall accuracy and ≥ 80 % for class-specific user’s and producer’s accuracies</p></li>
</ul>
<p>The 2012 and 2006 products have been validated after the production phase by an independent service provider (see AD 02).</p>
<p><strong>Sampling Design and Stratification</strong></p>
<p>The thematic accuracy assessment for the CLMS N2K is based on a stratified random point sampling scheme, in which all areas have a known non-zero probability of sampling. To assess overall and class-specific accuracies, stratifications are conducted on the LC/LU code level 4 (status layer), as well as on omission and commission strata (change layer).</p>
<p><strong>Response Design</strong></p>
<p>All sample points were re-interpreted at Code level 4 during the validation. This step was performed as a visual interpretation by independent, well-trained operators, who were not involved in the production itself, using the applicable Very High-Resolution (VHR) satellite data defined in the production. When re-interpreting the LC/LU sample points, the response design had to respect the latest product specifications and N2K nomenclature guidelines.</p>
<p><strong>Validation results</strong></p>
<p>To keep full statistical rigor and representativeness, and account for unequal inclusion probabilities and the relative occurrence of classes, area related weights were applied according to the area ratio for each class compared to the overall area. To deal with very imbalanced and skewed ratios between changed and unchanged areas at class level 1, an area restriction was implemented to reduce the area weight of polygons &gt; 100ha.</p>
<p>The results of the internal validation proved the sufficient thematic quality of CLMS N2K products, as can be seen in the following tables.</p>
<p>Full details on the class specific user and producer accuracy results can be found in the ANNEX of this document.</p>
<table class="caption-top table">
<caption>Table 11: LC/LU internal <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>accuracy assessment - unweighted results per product</caption>
<colgroup>
<col style="width: 39%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"><strong>Thematic accuracy [%]</strong></th>
<th style="text-align: left;"><strong>Confidence* Interval</strong></th>
<th style="text-align: left;"><strong>No.&nbsp;of assessed sample points</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LC/LU 2012 overall unweighted accuracy</td>
<td style="text-align: left;">96.52 %</td>
<td style="text-align: left;">0.20 %</td>
<td style="text-align: left;">30 203</td>
</tr>
<tr class="even">
<td style="text-align: left;">LC/LU 2018 overall unweighted accuracy</td>
<td style="text-align: left;">96.22 %</td>
<td style="text-align: left;">0.21 %</td>
<td style="text-align: left;">30 203</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">LC/LU change 2012-2018 overall unweighted accuracy for level 4</td>
<td style="text-align: left;">97.85 %</td>
<td style="text-align: left;">0.16 %</td>
<td style="text-align: left;">29 088</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LC/LU change 2012-2018 overall unweighted accuracy for level 1</td>
<td style="text-align: left;">98.61 %</td>
<td style="text-align: left;">0.13 %</td>
<td style="text-align: left;">29 088</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><em>*at a 95% confidence level</em></p>
</blockquote>
<table class="caption-top table">
<caption>Table 12: LC/LU internal<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> accuracy assessment - weighted results per product</caption>
<colgroup>
<col style="width: 38%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"><strong>Thematic accuracy [%]</strong></th>
<th style="text-align: left;"><strong>Confidence* Interval</strong></th>
<th style="text-align: left;"><strong>No.&nbsp;of assessed sample points</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LC/LU 2012 overall weighted accuracy</td>
<td style="text-align: left;">96.80 %</td>
<td style="text-align: left;">0.21 %</td>
<td style="text-align: left;">30 203</td>
</tr>
<tr class="even">
<td style="text-align: left;">LC/LU 2018 overall weighted accuracy</td>
<td style="text-align: left;">96.67 %</td>
<td style="text-align: left;">0.21 %</td>
<td style="text-align: left;">30 203</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">LC/LU change 2012-2018 overall weighted accuracy for level 4</td>
<td style="text-align: left;">98.64 %</td>
<td style="text-align: left;">0.12 %</td>
<td style="text-align: left;">29 088</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LC/LU change 2012-2018 overall weighted accuracy for level 1</td>
<td style="text-align: left;">99.33 %</td>
<td style="text-align: left;">0.08 %</td>
<td style="text-align: left;">29 088</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><em>*at a 95% confidence level</em></p>
</blockquote>
<table class="caption-top table">
<caption>Table 13: Unweighted User’s and Producer’s Accuracies for the Change Layer 2012 – 2018</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th colspan="4" style="text-align: center;"><strong>User’s Accuracy</strong></th>
<th colspan="4" style="text-align: center;"><strong>Producer’s Accuracy</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Code Level 1</strong></td>
<td style="text-align: center;"><strong>Non-Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Non-Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 1</td>
<td style="text-align: center;">99.56</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">95.47</td>
<td style="text-align: center;">1.29</td>
<td style="text-align: center;">98.78</td>
<td style="text-align: center;">0.34</td>
<td style="text-align: center;">98.34</td>
<td style="text-align: center;">0.80</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 2</td>
<td style="text-align: center;">99.66</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">96.57</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">98.89</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">98.93</td>
<td style="text-align: center;">0.63</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 3</td>
<td style="text-align: center;">99.95</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">94.95</td>
<td style="text-align: center;">1.33</td>
<td style="text-align: center;">98.82</td>
<td style="text-align: center;">0.31</td>
<td style="text-align: center;">99.80</td>
<td style="text-align: center;">0.28</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 4</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">92.94</td>
<td style="text-align: center;">1.37</td>
<td style="text-align: center;">94.56</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 5</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">96.30</td>
<td style="text-align: center;">1.20</td>
<td style="text-align: center;">97.83</td>
<td style="text-align: center;">0.69</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 6</td>
<td style="text-align: center;">99.41</td>
<td style="text-align: center;">0.32</td>
<td style="text-align: center;">95.11</td>
<td style="text-align: center;">1.50</td>
<td style="text-align: center;">98.24</td>
<td style="text-align: center;">0.53</td>
<td style="text-align: center;">98.31</td>
<td style="text-align: center;">0.90</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 7</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">93.76</td>
<td style="text-align: center;">2.28</td>
<td style="text-align: center;">98.12</td>
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 8</td>
<td style="text-align: center;">99.68</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">96.64</td>
<td style="text-align: center;">1.53</td>
<td style="text-align: center;">99.53</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">97.73</td>
<td style="text-align: center;">1.25</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<caption>Table 14: Area-weighted User’s and Producer’s Accuracies for the Change Layer 2012 – 2018 with area-restriction applied</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th colspan="4" style="text-align: center;"><strong>User’s Accuracy</strong></th>
<th colspan="4" style="text-align: center;"><strong>Producer’s Accuracy</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Code Level 1</strong></td>
<td style="text-align: center;"><strong>Non-Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Non-Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 1</td>
<td style="text-align: center;">99.56</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">95.47</td>
<td style="text-align: center;">1.29</td>
<td style="text-align: center;">99.72</td>
<td style="text-align: center;">0.08</td>
<td style="text-align: center;">93.07</td>
<td style="text-align: center;">3.15</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 2</td>
<td style="text-align: center;">99.66</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">96.57</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">99.63</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">96.82</td>
<td style="text-align: center;">1.82</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 3</td>
<td style="text-align: center;">99.95</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">94.95</td>
<td style="text-align: center;">1.33</td>
<td style="text-align: center;">99.31</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">99.65</td>
<td style="text-align: center;">0.48</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 4</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">92.94</td>
<td style="text-align: center;">1.37</td>
<td style="text-align: center;">98.18</td>
<td style="text-align: center;">0.35</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 5</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">96.30</td>
<td style="text-align: center;">1.20</td>
<td style="text-align: center;">99.78</td>
<td style="text-align: center;">0.07</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 6</td>
<td style="text-align: center;">99.41</td>
<td style="text-align: center;">0.32</td>
<td style="text-align: center;">95.11</td>
<td style="text-align: center;">1.50</td>
<td style="text-align: center;">99.61</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">92.72</td>
<td style="text-align: center;">3.66</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 7</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">93.76</td>
<td style="text-align: center;">2.28</td>
<td style="text-align: center;">99.68</td>
<td style="text-align: center;">0.12</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 8</td>
<td style="text-align: center;">99.68</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">96.64</td>
<td style="text-align: center;">1.53</td>
<td style="text-align: center;">99.91</td>
<td style="text-align: center;">0.04</td>
<td style="text-align: center;">89.19</td>
<td style="text-align: center;">5.45</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<caption>Table 15: Area-weighted User’s and Producer’s Accuracies for the Change Layer 2012 – 2018 without area-restriction applied</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th colspan="4" style="text-align: center;"><strong>User’s Accuracy</strong></th>
<th colspan="4" style="text-align: center;"><strong>Producer’s Accuracy</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Code Level 1</strong></td>
<td style="text-align: center;"><strong>Non-Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Non-Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
<td style="text-align: center;"><strong>Change</strong></td>
<td style="text-align: center;"><strong>CI [%]</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 1</td>
<td style="text-align: center;">99.56</td>
<td style="text-align: center;">0.21</td>
<td style="text-align: center;">95.47</td>
<td style="text-align: center;">1.29</td>
<td style="text-align: center;">99.95</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">80.47</td>
<td style="text-align: center;">10.18</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 2</td>
<td style="text-align: center;">99.66</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">96.57</td>
<td style="text-align: center;">1.10</td>
<td style="text-align: center;">99.98</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">62.30</td>
<td style="text-align: center;">13.86</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 3</td>
<td style="text-align: center;">99.95</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">94.95</td>
<td style="text-align: center;">1.33</td>
<td style="text-align: center;">99.93</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">96.70</td>
<td style="text-align: center;">4.43</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 4</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">92.94</td>
<td style="text-align: center;">1.37</td>
<td style="text-align: center;">99.94</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 5</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">96.30</td>
<td style="text-align: center;">1.20</td>
<td style="text-align: center;">99.95</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 6</td>
<td style="text-align: center;">99.41</td>
<td style="text-align: center;">0.32</td>
<td style="text-align: center;">95.11</td>
<td style="text-align: center;">1.50</td>
<td style="text-align: center;">99.93</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">78.89</td>
<td style="text-align: center;">11.62</td>
</tr>
<tr class="even">
<td style="text-align: center;">Class 7</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
<td style="text-align: center;">93.76</td>
<td style="text-align: center;">2.28</td>
<td style="text-align: center;">99.97</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Class 8</td>
<td style="text-align: center;">99.68</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">96.64</td>
<td style="text-align: center;">1.53</td>
<td style="text-align: center;">99.99</td>
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">53.48</td>
<td style="text-align: center;">14.06</td>
</tr>
</tbody>
</table>
</section>
<section id="quality-assurance-qa-and-quality-control-qc-measures" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="quality-assurance-qa-and-quality-control-qc-measures"><span class="header-section-number">7.2</span> Quality Assurance (QA) and Quality Control (QC) measures</h2>
<p>All CLMS N2K products have been produced by service providers with accredited ISO 9001:2015 quality standard management systems. All QA/QC procedures comprise dedicated ongoing quality checks for the various stages of the production workflow, to keep permanent control over the processes and ensure that all quality requirements are constantly met. This includes checks on:</p>
<ul>
<li><p>Data validity &amp; readability</p></li>
<li><p>Thematic &amp; Geometric accuracy &amp; consistency</p></li>
<li><p>Logical / topologic consistency</p></li>
<li><p>Radiometric quality, cloud coverage, haze, shadows, snow and other data gaps of EO data</p></li>
<li><p>Thematic coding/attributes</p></li>
<li><p>Seamless geographic coverage / data completeness</p></li>
<li><p>Impossible, or unlikely change combination</p></li>
<li><p>Processing infrastructure performance and backup functionality</p></li>
<li><p>Metadata completeness and output compliance to INSPIRE</p></li>
<li><p>EAGLE compliance of the data model</p></li>
</ul>
<p>Besides these internal QA/QC checks by the producing service providers all CLMS N2K products underwent a QC check and approval via the EEA Copernicus Quality tools, a web-based online system designed to quality-check map layers to be submitted to the EEA (<a href="https://github.com/eea/copernicus_quality_tools" class="uri">https://github.com/eea/copernicus_quality_tools</a>).</p>
</section>
<section id="external-independent-validation" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="external-independent-validation"><span class="header-section-number">7.3</span> External independent validation</h2>
<p>The objective of the external independent validation of CLMS N2K data is to derive thematic accuracy figures, to assess if dataset has reached the accuracy targets.</p>
<p>Its main goal is to inform users of the databases about quality in quantitative terms. Validation must be based on independent, very-high resolution in-situ data as reference. The date of in-situ data should coincide as much as possible with the acquisition date of satellite images used to derive the N2K product. In-situ data used in the validation should be independent, i.e.&nbsp;must not have been used in compilation of the N2K databases. Experts working on validation also should be independent, not having participated in the mapping exercise.</p>
<p>Validation in the N2K context means thematic validation.</p>
<p>Not yet performed at the time of writing this report.</p>
</section>
</section>
<section id="terms-of-use-and-product-technical-support" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Terms of use and product technical support</h1>
<section id="terms-of-use" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="terms-of-use"><span class="header-section-number">8.1</span> Terms of use</h2>
<p>The product(s) described in this document is/are created in the frame of the Copernicus programme of the European Union by the European Environment Agency (product custodian) and is/are owned by the European Union. The product(s) can be used following Copernicus full free and open data policy, which allows the use of the product(s) also for any commercial purpose. Derived products created by end users from the product(s) described in this document are owned by the end users, who have all intellectual rights to the derived products.</p>
</section>
<section id="citation" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="citation"><span class="header-section-number">8.2</span> Citation</h2>
<p>In cases of re-dissemination of the product(s) described in this document or when the product(s) is/are used to create a derived product it is required to provide a reference to the source. A template is provided below:</p>
<p><em>“© European Union, Copernicus Land Monitoring Service &lt;year&gt;, European Environment Agency (EEA)"</em></p>
</section>
<section id="product-technical-support" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="product-technical-support"><span class="header-section-number">8.3</span> Product technical support</h2>
<p>Product technical support is provided by the product custodian through Copernicus Land Monitoring Service helpdesk at <a href="mailto:copernicus@eea.europa.eu" class="email">copernicus@eea.europa.eu</a>. Product technical support doesn’t include software specific user support or general GIS or remote sensing support.</p>
</section>
</section>
<section id="references" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> References</h1>
<p>EC 2019: The European Commission, information. COMMISSION STAFF WORKING DOCUMENT. Expression of User Needs for the Copernicus Programme. Information available at under: <a href="https://knowledge4policy.ec.europa.eu/publication/commission-staff-working-document-expression-user-needs-copernicus-programme_en" class="uri">https://knowledge4policy.ec.europa.eu/publication/commission-staff-working-document-expression-user-needs-copernicus-programme_en</a></p>
<p>EC 2020: EU Biodiversity Strategy for 2030. Bringing nature back into our lives. COM(2020) 380 final. Information available at <a href="https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1590574123338&amp;uri=CELEX%3A52020DC0380" class="uri">https://eur-lex.europa.eu/legal-content/EN/TXT/?qid=1590574123338&amp;uri=CELEX%3A52020DC0380</a></p>
<p>EEA 1995: European Environment Agency, Corine Land Cover, 01 January 1995. Information available at <a href="https://www.eea.europa.eu/publications/COR0-landcover" class="uri">https://www.eea.europa.eu/publications/COR0-landcover</a>.</p>
<p>EEA 2019: The European environment — state and outlook 2020. Knowledge for transition to a sustainable Europe. Information available at <a href="https://www.eea.europa.eu/publications/soer-2020" class="uri">https://www.eea.europa.eu/publications/soer-2020</a></p>
<p>ETC-ULS 2020: Contributions to building a coherent Trans-European Nature Network. Information available at <a href="https://www.eea.europa.eu/themes/biodiversity/green-infrastructure/building-a-coherent-trans-european/contributions-to-building-a-coherent/view" class="uri">https://www.eea.europa.eu/themes/biodiversity/green-infrastructure/building-a-coherent-trans-european/contributions-to-building-a-coherent/view</a></p>
<p>EU 2013: Mapping and Assessment of Ecosystems and their Services. An analytical framework for ecosystem assessments under Action 5 of the EU Biodiversity Strategy to 2020. Information available at https://ec.europa.eu/environment/nature/knowledge/ecosystem_assessment/pdf/MAESWorkingPaper2013.pdf</p>
</section>
<section id="annexes" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Annexes</h1>
<p>Class specific thematic validation results for the 2018 update production phase</p>
<table class="caption-top table">
<caption>Area-weighted User's and Producer's Accuracies for status LC/LU 2018 on code level 4</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Code Level 4</strong></th>
<th colspan="2" style="text-align: left;"><strong>User’s Accuracy</strong></th>
<th style="text-align: left;"><strong>No.&nbsp;of assessed sample points</strong></th>
<th colspan="2" style="text-align: left;"><strong>Producer’s Accuracy</strong></th>
<th style="text-align: left;"><strong>No.&nbsp;of assessed sample points</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Accuracy [%]</strong></td>
<td style="text-align: left;"><strong>Confidence Interval [%]</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Accuracy [%]</strong></td>
<td style="text-align: left;"><strong>Confidence Interval [%]</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">1110</td>
<td style="text-align: left;">97.86</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">561</td>
<td style="text-align: left;">97.31</td>
<td style="text-align: left;">1.27</td>
<td style="text-align: left;">561</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1120</td>
<td style="text-align: left;">98.06</td>
<td style="text-align: left;">1.01</td>
<td style="text-align: left;">721</td>
<td style="text-align: left;">96.21</td>
<td style="text-align: left;">1.31</td>
<td style="text-align: left;">721</td>
</tr>
<tr class="even">
<td style="text-align: left;">1210</td>
<td style="text-align: left;">98.57</td>
<td style="text-align: left;">0.93</td>
<td style="text-align: left;">629</td>
<td style="text-align: left;">99.20</td>
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">629</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1220</td>
<td style="text-align: left;">98.37</td>
<td style="text-align: left;">1.12</td>
<td style="text-align: left;">490</td>
<td style="text-align: left;">98.71</td>
<td style="text-align: left;">1.29</td>
<td style="text-align: left;">490</td>
</tr>
<tr class="even">
<td style="text-align: left;">1230</td>
<td style="text-align: left;">98.68</td>
<td style="text-align: left;">1.28</td>
<td style="text-align: left;">304</td>
<td style="text-align: left;">98.60</td>
<td style="text-align: left;">1.92</td>
<td style="text-align: left;">304</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1240</td>
<td style="text-align: left;">99.52</td>
<td style="text-align: left;">0.66</td>
<td style="text-align: left;">418</td>
<td style="text-align: left;">99.34</td>
<td style="text-align: left;">0.91</td>
<td style="text-align: left;">418</td>
</tr>
<tr class="even">
<td style="text-align: left;">1310</td>
<td style="text-align: left;">96.76</td>
<td style="text-align: left;">1.04</td>
<td style="text-align: left;">1111</td>
<td style="text-align: left;">93.93</td>
<td style="text-align: left;">1.69</td>
<td style="text-align: left;">1111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1320</td>
<td style="text-align: left;">86.78</td>
<td style="text-align: left;">3.26</td>
<td style="text-align: left;">416</td>
<td style="text-align: left;">98.01</td>
<td style="text-align: left;">1.51</td>
<td style="text-align: left;">416</td>
</tr>
<tr class="even">
<td style="text-align: left;">1400</td>
<td style="text-align: left;">94.57</td>
<td style="text-align: left;">1.92</td>
<td style="text-align: left;">534</td>
<td style="text-align: left;">98.65</td>
<td style="text-align: left;">0.94</td>
<td style="text-align: left;">534</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2110</td>
<td style="text-align: left;">98.48</td>
<td style="text-align: left;">0.58</td>
<td style="text-align: left;">1711</td>
<td style="text-align: left;">94.19</td>
<td style="text-align: left;">1.07</td>
<td style="text-align: left;">1711</td>
</tr>
<tr class="even">
<td style="text-align: left;">2120</td>
<td style="text-align: left;">92.08</td>
<td style="text-align: left;">2.77</td>
<td style="text-align: left;">366</td>
<td style="text-align: left;">99.59</td>
<td style="text-align: left;">0.81</td>
<td style="text-align: left;">366</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2210</td>
<td style="text-align: left;">98.36</td>
<td style="text-align: left;">0.96</td>
<td style="text-align: left;">670</td>
<td style="text-align: left;">98.33</td>
<td style="text-align: left;">0.76</td>
<td style="text-align: left;">670</td>
</tr>
<tr class="even">
<td style="text-align: left;">2220</td>
<td style="text-align: left;">98.57</td>
<td style="text-align: left;">1.13</td>
<td style="text-align: left;">421</td>
<td style="text-align: left;">99.31</td>
<td style="text-align: left;">0.70</td>
<td style="text-align: left;">421</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2310</td>
<td style="text-align: left;">88.43</td>
<td style="text-align: left;">3.84</td>
<td style="text-align: left;">268</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">268</td>
</tr>
<tr class="even">
<td style="text-align: left;">2320</td>
<td style="text-align: left;">93.81</td>
<td style="text-align: left;">2.27</td>
<td style="text-align: left;">436</td>
<td style="text-align: left;">98.16</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">436</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2330</td>
<td style="text-align: left;">93.78</td>
<td style="text-align: left;">2.20</td>
<td style="text-align: left;">466</td>
<td style="text-align: left;">98.81</td>
<td style="text-align: left;">0.98</td>
<td style="text-align: left;">466</td>
</tr>
<tr class="even">
<td style="text-align: left;">2340</td>
<td style="text-align: left;">90.25</td>
<td style="text-align: left;">3.07</td>
<td style="text-align: left;">359</td>
<td style="text-align: left;">99.61</td>
<td style="text-align: left;">0.56</td>
<td style="text-align: left;">359</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3110</td>
<td style="text-align: left;">99.03</td>
<td style="text-align: left;">0.67</td>
<td style="text-align: left;">828</td>
<td style="text-align: left;">94.71</td>
<td style="text-align: left;">1.17</td>
<td style="text-align: left;">828</td>
</tr>
<tr class="even">
<td style="text-align: left;">3120</td>
<td style="text-align: left;">96.09</td>
<td style="text-align: left;">1.94</td>
<td style="text-align: left;">384</td>
<td style="text-align: left;">98.37</td>
<td style="text-align: left;">1.64</td>
<td style="text-align: left;">384</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3210</td>
<td style="text-align: left;">98.99</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">693</td>
<td style="text-align: left;">94.69</td>
<td style="text-align: left;">1.36</td>
<td style="text-align: left;">693</td>
</tr>
<tr class="even">
<td style="text-align: left;">3220</td>
<td style="text-align: left;">93.40</td>
<td style="text-align: left;">2.80</td>
<td style="text-align: left;">303</td>
<td style="text-align: left;">98.63</td>
<td style="text-align: left;">2.65</td>
<td style="text-align: left;">303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3310</td>
<td style="text-align: left;">96.91</td>
<td style="text-align: left;">1.54</td>
<td style="text-align: left;">486</td>
<td style="text-align: left;">99.14</td>
<td style="text-align: left;">0.63</td>
<td style="text-align: left;">486</td>
</tr>
<tr class="even">
<td style="text-align: left;">3320</td>
<td style="text-align: left;">83.78</td>
<td style="text-align: left;">8.46</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3400</td>
<td style="text-align: left;">95.56</td>
<td style="text-align: left;">0.91</td>
<td style="text-align: left;">1984</td>
<td style="text-align: left;">87.86</td>
<td style="text-align: left;">1.63</td>
<td style="text-align: left;">1984</td>
</tr>
<tr class="even">
<td style="text-align: left;">3500</td>
<td style="text-align: left;">97.78</td>
<td style="text-align: left;">1.36</td>
<td style="text-align: left;">450</td>
<td style="text-align: left;">99.34</td>
<td style="text-align: left;">0.90</td>
<td style="text-align: left;">450</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3600</td>
<td style="text-align: left;">68.60</td>
<td style="text-align: left;">5.67</td>
<td style="text-align: left;">258</td>
<td style="text-align: left;">99.19</td>
<td style="text-align: left;">1.12</td>
<td style="text-align: left;">258</td>
</tr>
<tr class="even">
<td style="text-align: left;">4100</td>
<td style="text-align: left;">97.77</td>
<td style="text-align: left;">1.02</td>
<td style="text-align: left;">808</td>
<td style="text-align: left;">96.30</td>
<td style="text-align: left;">1.15</td>
<td style="text-align: left;">808</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4211</td>
<td style="text-align: left;">88.93</td>
<td style="text-align: left;">3.87</td>
<td style="text-align: left;">253</td>
<td style="text-align: left;">89.36</td>
<td style="text-align: left;">3.30</td>
<td style="text-align: left;">253</td>
</tr>
<tr class="even">
<td style="text-align: left;">4212</td>
<td style="text-align: left;">95.25</td>
<td style="text-align: left;">1.14</td>
<td style="text-align: left;">1348</td>
<td style="text-align: left;">92.27</td>
<td style="text-align: left;">1.39</td>
<td style="text-align: left;">1348</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4220</td>
<td style="text-align: left;">99.11</td>
<td style="text-align: left;">1.01</td>
<td style="text-align: left;">336</td>
<td style="text-align: left;">97.29</td>
<td style="text-align: left;">1.39</td>
<td style="text-align: left;">336</td>
</tr>
<tr class="even">
<td style="text-align: left;">5100</td>
<td style="text-align: left;">97.50</td>
<td style="text-align: left;">1.17</td>
<td style="text-align: left;">680</td>
<td style="text-align: left;">98.13</td>
<td style="text-align: left;">0.92</td>
<td style="text-align: left;">680</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5200</td>
<td style="text-align: left;">97.33</td>
<td style="text-align: left;">1.43</td>
<td style="text-align: left;">487</td>
<td style="text-align: left;">98.72</td>
<td style="text-align: left;">0.84</td>
<td style="text-align: left;">487</td>
</tr>
<tr class="even">
<td style="text-align: left;">5300</td>
<td style="text-align: left;">96.68</td>
<td style="text-align: left;">1.15</td>
<td style="text-align: left;">933</td>
<td style="text-align: left;">96.71</td>
<td style="text-align: left;">1.14</td>
<td style="text-align: left;">933</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6100</td>
<td style="text-align: left;">92.37</td>
<td style="text-align: left;">1.74</td>
<td style="text-align: left;">891</td>
<td style="text-align: left;">96.34</td>
<td style="text-align: left;">1.35</td>
<td style="text-align: left;">891</td>
</tr>
<tr class="even">
<td style="text-align: left;">6210</td>
<td style="text-align: left;">92.34</td>
<td style="text-align: left;">2.44</td>
<td style="text-align: left;">457</td>
<td style="text-align: left;">97.36</td>
<td style="text-align: left;">2.52</td>
<td style="text-align: left;">457</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6220</td>
<td style="text-align: left;">95.43</td>
<td style="text-align: left;">1.63</td>
<td style="text-align: left;">635</td>
<td style="text-align: left;">98.73</td>
<td style="text-align: left;">1.22</td>
<td style="text-align: left;">635</td>
</tr>
<tr class="even">
<td style="text-align: left;">6310</td>
<td style="text-align: left;">96.04</td>
<td style="text-align: left;">1.62</td>
<td style="text-align: left;">555</td>
<td style="text-align: left;">98.78</td>
<td style="text-align: left;">0.63</td>
<td style="text-align: left;">555</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6320</td>
<td style="text-align: left;">92.50</td>
<td style="text-align: left;">2.21</td>
<td style="text-align: left;">547</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">547</td>
</tr>
<tr class="even">
<td style="text-align: left;">6330</td>
<td style="text-align: left;">98.14</td>
<td style="text-align: left;">2.10</td>
<td style="text-align: left;">161</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">161</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7110</td>
<td style="text-align: left;">97.63</td>
<td style="text-align: left;">1.38</td>
<td style="text-align: left;">465</td>
<td style="text-align: left;">96.51</td>
<td style="text-align: left;">1.39</td>
<td style="text-align: left;">465</td>
</tr>
<tr class="even">
<td style="text-align: left;">7121</td>
<td style="text-align: left;">96.04</td>
<td style="text-align: left;">3.82</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">101</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7122</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">168</td>
<td style="text-align: left;">98.92</td>
<td style="text-align: left;">1.24</td>
<td style="text-align: left;">168</td>
</tr>
<tr class="even">
<td style="text-align: left;">7210</td>
<td style="text-align: left;">98.43</td>
<td style="text-align: left;">1.15</td>
<td style="text-align: left;">446</td>
<td style="text-align: left;">99.77</td>
<td style="text-align: left;">0.45</td>
<td style="text-align: left;">446</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7220</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">408</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">408</td>
</tr>
<tr class="even">
<td style="text-align: left;">7230</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">202</td>
<td style="text-align: left;">97.92</td>
<td style="text-align: left;">2.89</td>
<td style="text-align: left;">202</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8110</td>
<td style="text-align: left;">98.97</td>
<td style="text-align: left;">0.76</td>
<td style="text-align: left;">681</td>
<td style="text-align: left;">97.57</td>
<td style="text-align: left;">0.90</td>
<td style="text-align: left;">681</td>
</tr>
<tr class="even">
<td style="text-align: left;">8120</td>
<td style="text-align: left;">97.62</td>
<td style="text-align: left;">1.39</td>
<td style="text-align: left;">462</td>
<td style="text-align: left;">99.83</td>
<td style="text-align: left;">0.34</td>
<td style="text-align: left;">462</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8130</td>
<td style="text-align: left;">94.21</td>
<td style="text-align: left;">2.30</td>
<td style="text-align: left;">397</td>
<td style="text-align: left;">98.48</td>
<td style="text-align: left;">2.07</td>
<td style="text-align: left;">397</td>
</tr>
<tr class="even">
<td style="text-align: left;">8210</td>
<td style="text-align: left;">97.71</td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">959</td>
<td style="text-align: left;">97.85</td>
<td style="text-align: left;">0.64</td>
<td style="text-align: left;">959</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8220</td>
<td style="text-align: left;">95.39</td>
<td style="text-align: left;">1.84</td>
<td style="text-align: left;">499</td>
<td style="text-align: left;">96.11</td>
<td style="text-align: left;">2.85</td>
<td style="text-align: left;">499</td>
</tr>
<tr class="even">
<td style="text-align: left;">8230</td>
<td style="text-align: left;">91.24</td>
<td style="text-align: left;">3.05</td>
<td style="text-align: left;">331</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">331</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8240</td>
<td style="text-align: left;">98.24</td>
<td style="text-align: left;">1.08</td>
<td style="text-align: left;">567</td>
<td style="text-align: left;">97.08</td>
<td style="text-align: left;">2.26</td>
<td style="text-align: left;">567</td>
</tr>
<tr class="even">
<td style="text-align: left;">8310</td>
<td style="text-align: left;">99.65</td>
<td style="text-align: left;">0.68</td>
<td style="text-align: left;">287</td>
<td style="text-align: left;">98.69</td>
<td style="text-align: left;">1.03</td>
<td style="text-align: left;">287</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8320</td>
<td style="text-align: left;">99.63</td>
<td style="text-align: left;">0.72</td>
<td style="text-align: left;">273</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">273</td>
</tr>
<tr class="even">
<td style="text-align: left;">8400</td>
<td style="text-align: left;">97.86</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">525</td>
<td style="text-align: left;">98.01</td>
<td style="text-align: left;">0.76</td>
<td style="text-align: left;">525</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<caption>Area-weighted User's and Producer's Accuracies for status LC/LU 2012 on code level 4</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Code Level 4</strong></th>
<th colspan="2" style="text-align: left;"><strong>User’s Accuracy</strong></th>
<th style="text-align: left;"><strong>No.&nbsp;of assessed sample points</strong></th>
<th colspan="2" style="text-align: left;"><strong>Producer’s Accuracy</strong></th>
<th style="text-align: left;"><strong>No.&nbsp;of assessed sample points</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Accuracy [%]</strong></td>
<td style="text-align: left;"><strong>Confidence Interval [%]</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Accuracy [%]</strong></td>
<td style="text-align: left;"><strong>Confidence Interval [%]</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">1110</td>
<td style="text-align: left;">98.26</td>
<td style="text-align: left;">1.19</td>
<td style="text-align: left;">461</td>
<td style="text-align: left;">97.09</td>
<td style="text-align: left;">1.34</td>
<td style="text-align: left;">461</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1120</td>
<td style="text-align: left;">97.66</td>
<td style="text-align: left;">1.37</td>
<td style="text-align: left;">470</td>
<td style="text-align: left;">96.79</td>
<td style="text-align: left;">1.29</td>
<td style="text-align: left;">470</td>
</tr>
<tr class="even">
<td style="text-align: left;">1210</td>
<td style="text-align: left;">99.42</td>
<td style="text-align: left;">0.66</td>
<td style="text-align: left;">514</td>
<td style="text-align: left;">98.85</td>
<td style="text-align: left;">0.67</td>
<td style="text-align: left;">514</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1220</td>
<td style="text-align: left;">98.30</td>
<td style="text-align: left;">1.17</td>
<td style="text-align: left;">470</td>
<td style="text-align: left;">99.11</td>
<td style="text-align: left;">1.02</td>
<td style="text-align: left;">470</td>
</tr>
<tr class="even">
<td style="text-align: left;">1230</td>
<td style="text-align: left;">98.65</td>
<td style="text-align: left;">1.31</td>
<td style="text-align: left;">297</td>
<td style="text-align: left;">98.14</td>
<td style="text-align: left;">2.53</td>
<td style="text-align: left;">297</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1240</td>
<td style="text-align: left;">99.50</td>
<td style="text-align: left;">0.69</td>
<td style="text-align: left;">399</td>
<td style="text-align: left;">99.24</td>
<td style="text-align: left;">1.05</td>
<td style="text-align: left;">399</td>
</tr>
<tr class="even">
<td style="text-align: left;">1310</td>
<td style="text-align: left;">96.72</td>
<td style="text-align: left;">0.90</td>
<td style="text-align: left;">1523</td>
<td style="text-align: left;">95.59</td>
<td style="text-align: left;">1.42</td>
<td style="text-align: left;">1523</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1320</td>
<td style="text-align: left;">85.40</td>
<td style="text-align: left;">3.64</td>
<td style="text-align: left;">363</td>
<td style="text-align: left;">96.08</td>
<td style="text-align: left;">3.31</td>
<td style="text-align: left;">363</td>
</tr>
<tr class="even">
<td style="text-align: left;">1400</td>
<td style="text-align: left;">94.21</td>
<td style="text-align: left;">2.01</td>
<td style="text-align: left;">518</td>
<td style="text-align: left;">98.66</td>
<td style="text-align: left;">1.05</td>
<td style="text-align: left;">518</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2110</td>
<td style="text-align: left;">97.91</td>
<td style="text-align: left;">0.66</td>
<td style="text-align: left;">1816</td>
<td style="text-align: left;">91.29</td>
<td style="text-align: left;">1.27</td>
<td style="text-align: left;">1816</td>
</tr>
<tr class="even">
<td style="text-align: left;">2120</td>
<td style="text-align: left;">92.51</td>
<td style="text-align: left;">2.83</td>
<td style="text-align: left;">334</td>
<td style="text-align: left;">99.49</td>
<td style="text-align: left;">1.00</td>
<td style="text-align: left;">334</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2210</td>
<td style="text-align: left;">90.16</td>
<td style="text-align: left;">2.37</td>
<td style="text-align: left;">610</td>
<td style="text-align: left;">97.97</td>
<td style="text-align: left;">0.92</td>
<td style="text-align: left;">610</td>
</tr>
<tr class="even">
<td style="text-align: left;">2220</td>
<td style="text-align: left;">98.50</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">399</td>
<td style="text-align: left;">98.86</td>
<td style="text-align: left;">0.93</td>
<td style="text-align: left;">399</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2310</td>
<td style="text-align: left;">88.43</td>
<td style="text-align: left;">3.84</td>
<td style="text-align: left;">268</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">268</td>
</tr>
<tr class="even">
<td style="text-align: left;">2320</td>
<td style="text-align: left;">93.85</td>
<td style="text-align: left;">2.25</td>
<td style="text-align: left;">439</td>
<td style="text-align: left;">98.17</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">439</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2330</td>
<td style="text-align: left;">93.58</td>
<td style="text-align: left;">2.19</td>
<td style="text-align: left;">483</td>
<td style="text-align: left;">98.91</td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">483</td>
</tr>
<tr class="even">
<td style="text-align: left;">2340</td>
<td style="text-align: left;">90.74</td>
<td style="text-align: left;">2.93</td>
<td style="text-align: left;">378</td>
<td style="text-align: left;">99.36</td>
<td style="text-align: left;">0.76</td>
<td style="text-align: left;">378</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3110</td>
<td style="text-align: left;">98.72</td>
<td style="text-align: left;">0.62</td>
<td style="text-align: left;">1247</td>
<td style="text-align: left;">95.68</td>
<td style="text-align: left;">1.03</td>
<td style="text-align: left;">1247</td>
</tr>
<tr class="even">
<td style="text-align: left;">3120</td>
<td style="text-align: left;">96.08</td>
<td style="text-align: left;">1.95</td>
<td style="text-align: left;">383</td>
<td style="text-align: left;">99.51</td>
<td style="text-align: left;">0.96</td>
<td style="text-align: left;">383</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3210</td>
<td style="text-align: left;">99.07</td>
<td style="text-align: left;">0.54</td>
<td style="text-align: left;">1189</td>
<td style="text-align: left;">95.89</td>
<td style="text-align: left;">1.15</td>
<td style="text-align: left;">1189</td>
</tr>
<tr class="even">
<td style="text-align: left;">3220</td>
<td style="text-align: left;">93.13</td>
<td style="text-align: left;">2.91</td>
<td style="text-align: left;">291</td>
<td style="text-align: left;">91.18</td>
<td style="text-align: left;">11.23</td>
<td style="text-align: left;">291</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3310</td>
<td style="text-align: left;">97.83</td>
<td style="text-align: left;">1.22</td>
<td style="text-align: left;">553</td>
<td style="text-align: left;">99.17</td>
<td style="text-align: left;">0.63</td>
<td style="text-align: left;">553</td>
</tr>
<tr class="even">
<td style="text-align: left;">3320</td>
<td style="text-align: left;">83.78</td>
<td style="text-align: left;">8.46</td>
<td style="text-align: left;">74</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3400</td>
<td style="text-align: left;">96.31</td>
<td style="text-align: left;">1.30</td>
<td style="text-align: left;">812</td>
<td style="text-align: left;">88.52</td>
<td style="text-align: left;">1.76</td>
<td style="text-align: left;">812</td>
</tr>
<tr class="even">
<td style="text-align: left;">3500</td>
<td style="text-align: left;">97.78</td>
<td style="text-align: left;">1.36</td>
<td style="text-align: left;">451</td>
<td style="text-align: left;">98.84</td>
<td style="text-align: left;">1.30</td>
<td style="text-align: left;">451</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3600</td>
<td style="text-align: left;">87.39</td>
<td style="text-align: left;">4.23</td>
<td style="text-align: left;">238</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">238</td>
</tr>
<tr class="even">
<td style="text-align: left;">4100</td>
<td style="text-align: left;">97.52</td>
<td style="text-align: left;">0.98</td>
<td style="text-align: left;">969</td>
<td style="text-align: left;">97.52</td>
<td style="text-align: left;">0.86</td>
<td style="text-align: left;">969</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4211</td>
<td style="text-align: left;">91.32</td>
<td style="text-align: left;">3.40</td>
<td style="text-align: left;">265</td>
<td style="text-align: left;">92.04</td>
<td style="text-align: left;">2.86</td>
<td style="text-align: left;">265</td>
</tr>
<tr class="even">
<td style="text-align: left;">4212</td>
<td style="text-align: left;">95.10</td>
<td style="text-align: left;">1.14</td>
<td style="text-align: left;">1388</td>
<td style="text-align: left;">93.28</td>
<td style="text-align: left;">1.32</td>
<td style="text-align: left;">1388</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4220</td>
<td style="text-align: left;">98.56</td>
<td style="text-align: left;">1.26</td>
<td style="text-align: left;">347</td>
<td style="text-align: left;">97.19</td>
<td style="text-align: left;">1.43</td>
<td style="text-align: left;">347</td>
</tr>
<tr class="even">
<td style="text-align: left;">5100</td>
<td style="text-align: left;">97.95</td>
<td style="text-align: left;">0.97</td>
<td style="text-align: left;">828</td>
<td style="text-align: left;">98.19</td>
<td style="text-align: left;">0.95</td>
<td style="text-align: left;">828</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5200</td>
<td style="text-align: left;">97.58</td>
<td style="text-align: left;">1.30</td>
<td style="text-align: left;">537</td>
<td style="text-align: left;">98.71</td>
<td style="text-align: left;">0.89</td>
<td style="text-align: left;">537</td>
</tr>
<tr class="even">
<td style="text-align: left;">5300</td>
<td style="text-align: left;">97.11</td>
<td style="text-align: left;">0.99</td>
<td style="text-align: left;">1108</td>
<td style="text-align: left;">96.16</td>
<td style="text-align: left;">1.22</td>
<td style="text-align: left;">1108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6100</td>
<td style="text-align: left;">91.80</td>
<td style="text-align: left;">1.86</td>
<td style="text-align: left;">841</td>
<td style="text-align: left;">96.69</td>
<td style="text-align: left;">1.37</td>
<td style="text-align: left;">841</td>
</tr>
<tr class="even">
<td style="text-align: left;">6210</td>
<td style="text-align: left;">97.59</td>
<td style="text-align: left;">1.48</td>
<td style="text-align: left;">415</td>
<td style="text-align: left;">94.54</td>
<td style="text-align: left;">2.90</td>
<td style="text-align: left;">415</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6220</td>
<td style="text-align: left;">96.93</td>
<td style="text-align: left;">1.40</td>
<td style="text-align: left;">586</td>
<td style="text-align: left;">98.78</td>
<td style="text-align: left;">1.21</td>
<td style="text-align: left;">586</td>
</tr>
<tr class="even">
<td style="text-align: left;">6310</td>
<td style="text-align: left;">96.08</td>
<td style="text-align: left;">1.61</td>
<td style="text-align: left;">561</td>
<td style="text-align: left;">98.97</td>
<td style="text-align: left;">0.56</td>
<td style="text-align: left;">561</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6320</td>
<td style="text-align: left;">96.53</td>
<td style="text-align: left;">1.58</td>
<td style="text-align: left;">519</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">519</td>
</tr>
<tr class="even">
<td style="text-align: left;">6330</td>
<td style="text-align: left;">98.20</td>
<td style="text-align: left;">2.02</td>
<td style="text-align: left;">167</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">167</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7110</td>
<td style="text-align: left;">97.90</td>
<td style="text-align: left;">1.18</td>
<td style="text-align: left;">572</td>
<td style="text-align: left;">97.51</td>
<td style="text-align: left;">1.22</td>
<td style="text-align: left;">572</td>
</tr>
<tr class="even">
<td style="text-align: left;">7121</td>
<td style="text-align: left;">98.31</td>
<td style="text-align: left;">1.91</td>
<td style="text-align: left;">177</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">177</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7122</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">164</td>
<td style="text-align: left;">99.66</td>
<td style="text-align: left;">0.67</td>
<td style="text-align: left;">164</td>
</tr>
<tr class="even">
<td style="text-align: left;">7210</td>
<td style="text-align: left;">95.92</td>
<td style="text-align: left;">1.67</td>
<td style="text-align: left;">539</td>
<td style="text-align: left;">99.74</td>
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">539</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7220</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">396</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">396</td>
</tr>
<tr class="even">
<td style="text-align: left;">7230</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">201</td>
<td style="text-align: left;">98.69</td>
<td style="text-align: left;">2.53</td>
<td style="text-align: left;">201</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8110</td>
<td style="text-align: left;">98.99</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">693</td>
<td style="text-align: left;">99.08</td>
<td style="text-align: left;">0.61</td>
<td style="text-align: left;">693</td>
</tr>
<tr class="even">
<td style="text-align: left;">8120</td>
<td style="text-align: left;">97.36</td>
<td style="text-align: left;">1.54</td>
<td style="text-align: left;">416</td>
<td style="text-align: left;">99.84</td>
<td style="text-align: left;">0.31</td>
<td style="text-align: left;">416</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8130</td>
<td style="text-align: left;">94.32</td>
<td style="text-align: left;">2.17</td>
<td style="text-align: left;">440</td>
<td style="text-align: left;">99.25</td>
<td style="text-align: left;">1.45</td>
<td style="text-align: left;">440</td>
</tr>
<tr class="even">
<td style="text-align: left;">8210</td>
<td style="text-align: left;">99.25</td>
<td style="text-align: left;">0.65</td>
<td style="text-align: left;">671</td>
<td style="text-align: left;">98.04</td>
<td style="text-align: left;">0.60</td>
<td style="text-align: left;">671</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8220</td>
<td style="text-align: left;">95.08</td>
<td style="text-align: left;">1.92</td>
<td style="text-align: left;">488</td>
<td style="text-align: left;">99.81</td>
<td style="text-align: left;">0.37</td>
<td style="text-align: left;">488</td>
</tr>
<tr class="even">
<td style="text-align: left;">8230</td>
<td style="text-align: left;">93.01</td>
<td style="text-align: left;">2.76</td>
<td style="text-align: left;">329</td>
<td style="text-align: left;">99.19</td>
<td style="text-align: left;">1.24</td>
<td style="text-align: left;">329</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8240</td>
<td style="text-align: left;">97.52</td>
<td style="text-align: left;">1.33</td>
<td style="text-align: left;">525</td>
<td style="text-align: left;">98.65</td>
<td style="text-align: left;">2.01</td>
<td style="text-align: left;">525</td>
</tr>
<tr class="even">
<td style="text-align: left;">8310</td>
<td style="text-align: left;">99.62</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">263</td>
<td style="text-align: left;">98.30</td>
<td style="text-align: left;">1.33</td>
<td style="text-align: left;">263</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8320</td>
<td style="text-align: left;">99.63</td>
<td style="text-align: left;">0.72</td>
<td style="text-align: left;">273</td>
<td style="text-align: left;">100.00</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">273</td>
</tr>
<tr class="even">
<td style="text-align: left;">8400</td>
<td style="text-align: left;">99.62</td>
<td style="text-align: left;">0.53</td>
<td style="text-align: left;">521</td>
<td style="text-align: left;">99.48</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">521</td>
</tr>
</tbody>
</table>


</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Performed by the Service provider after production and before delivery to the EEA<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Performed by the Service provider after production and before delivery to the EEA<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div>EUPL (&gt;= 1.2)</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/eea\.github\.io\/CLMS_documents\/main");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2025 EEA. All rights reserved.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>