project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - ./**/*.qmd
    - "!includes/**"
    - "!theme/**"
    - "!templates/**"
    - "!assets/**"
    - "!.quarto/**"
    - "!_site/**"

resources:
  - assets/

website:
  title: "Technical Library"
  site-url: "https://library.land.copernicus.eu"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  search: 
    type: textbox
  navbar:
    background: "#a0b128"
    foreground: "#ffffff"
  page-footer:
    left: |
      2025 EEA. All rights reserved.

language: 
  search-text-placeholder: Search ...        

metadata-files:
  - includes/default.yml

format:
  html:
    output-dir: _site # Moves rendered files outside src/
    page-layout: full
    include-before-body: includes/main-logos.html
    css: theme/main.css
