name: Quarto Markdown Render, Generate Sitemap, and Deploy

on:
  push:
    paths:
      - 'src/**/*'  # Trigger the action only when .qmd files are modified or pushed
  pull_request:
    paths:
      - 'src/**/*'  # Also trigger on pull requests that modify .qmd files
  workflow_dispatch:

jobs:
  build:
    runs-on: mckeea/quarto-doc-builder:latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup default _quarto.yaml
        run: mv _quarto_not_used.yaml _quarto.yaml

      - name: Install Python dependencies
        run: |
          python3 -m pip install --break-system-packages \
          keybert \
          ruamel.yaml \
          pyyaml \
          transformers==4.37.2 \
          accelerate==0.27.2

      - name: Generate keywords
        run: python3 scripts/generate_keywords.py

      - name: Render all documents into to HTML/DOCX
        run: |
          rm -rf _site
          sudo cp /usr/bin/chromium /usr/bin/chromium-browser
          QUARTO_CHROMIUM_HEADLESS_MODE=new quarto render --to html
          QUARTO_CHROMIUM_HEADLESS_MODE=new quarto render --to docx --no-clean
          find _site -type f -name 'index.docx' -delete

      - name: Convert DOCX to PDF with Soffice
        run: |
          chmod +x scripts/convert_docx_to_pdf.sh
          timeout 3s ./scripts/convert_docx_to_pdf.sh || true
          timeout 10m ./scripts/convert_docx_to_pdf.sh

      - name: Deploy to GitHub Pages (gh-pages-test branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-test  # Push to gh-pages-test before approved go-live
          folder: _site
          clean: true
          force: true
