<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="European Environment Agency (EEA)">
<meta name="dcterms.date" content="2026-06-09">

<title>Medium Resolution Vegetation Phenology and Productivity (MR-VPP) – Algorithm Theoretical Basis Document (ATBD) – Technical Library</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-81606b2d085324eee7eb30ab52c42792.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "Search ...",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "ScholarlyArticle",
    "headline": "Medium Resolution Vegetation Phenology and Productivity (MR-VPP) – Algorithm Theoretical Basis Document (ATBD)",
    "description": "?meta:description",
    "datePublished": "June 9, 2026",
    "author": {
      "@type": "Person",
      "name": "European Environment Agency (EEA)
"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Copernicus Land Monitoring Service",
      "logo": {
        "@type": "ImageObject",
        "url": "https://land.copernicus.eu/static/media/ccl-icon-land-text-2.e04af716.svg"
      }
    },
    "articleSection": "General",
    "isAccessibleForFree": "true",
    "license": "",
    "speakable": {
      "@type": "SpeakableSpecification",
      "cssSelector": "article p"
    }
  }
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../_meta/theme/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Technical Library</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Index</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#mr-vpp-products-summary" id="toc-mr-vpp-products-summary" class="nav-link" data-scroll-target="#mr-vpp-products-summary"><span class="header-section-number">1.1</span> MR-VPP products summary</a></li>
  <li><a href="#scope-and-objectives" id="toc-scope-and-objectives" class="nav-link" data-scroll-target="#scope-and-objectives"><span class="header-section-number">1.2</span> Scope and objectives</a></li>
  <li><a href="#document-structure" id="toc-document-structure" class="nav-link" data-scroll-target="#document-structure"><span class="header-section-number">1.3</span> Document structure</a></li>
  <li><a href="#related-documents" id="toc-related-documents" class="nav-link" data-scroll-target="#related-documents"><span class="header-section-number">1.4</span> Related documents</a>
  <ul class="collapse">
  <li><a href="#applicable-documents" id="toc-applicable-documents" class="nav-link" data-scroll-target="#applicable-documents"><span class="header-section-number">1.4.1</span> Applicable documents</a></li>
  <li><a href="#reference-documents" id="toc-reference-documents" class="nav-link" data-scroll-target="#reference-documents"><span class="header-section-number">1.4.2</span> Reference documents</a></li>
  </ul></li>
  <li><a href="#terminology" id="toc-terminology" class="nav-link" data-scroll-target="#terminology"><span class="header-section-number">1.5</span> Terminology</a>
  <ul class="collapse">
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">1.5.1</span> Terms</a></li>
  <li><a href="#abbreviations-and-acronyms" id="toc-abbreviations-and-acronyms" class="nav-link" data-scroll-target="#abbreviations-and-acronyms"><span class="header-section-number">1.5.2</span> Abbreviations and acronyms</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#input-data-and-plant-phenology-index-for-mr-vpp" id="toc-input-data-and-plant-phenology-index-for-mr-vpp" class="nav-link" data-scroll-target="#input-data-and-plant-phenology-index-for-mr-vpp"><span class="header-section-number">2</span> Input data and plant phenology index for MR-VPP</a>
  <ul class="collapse">
  <li><a href="#input-data" id="toc-input-data" class="nav-link" data-scroll-target="#input-data"><span class="header-section-number">2.1</span> Input data</a></li>
  <li><a href="#calculation-of-ppi" id="toc-calculation-of-ppi" class="nav-link" data-scroll-target="#calculation-of-ppi"><span class="header-section-number">2.2</span> Calculation of PPI</a></li>
  <li><a href="#calculation-of-ppi-quality-flag-qa-values-for-timesat-processing" id="toc-calculation-of-ppi-quality-flag-qa-values-for-timesat-processing" class="nav-link" data-scroll-target="#calculation-of-ppi-quality-flag-qa-values-for-timesat-processing"><span class="header-section-number">2.3</span> Calculation of PPI Quality flag (QA) values for TIMESAT processing</a></li>
  <li><a href="#specification-of-output-ppi-data" id="toc-specification-of-output-ppi-data" class="nav-link" data-scroll-target="#specification-of-output-ppi-data"><span class="header-section-number">2.4</span> Specification of output PPI data</a></li>
  </ul></li>
  <li><a href="#the-vpp-retrieval-algorithm" id="toc-the-vpp-retrieval-algorithm" class="nav-link" data-scroll-target="#the-vpp-retrieval-algorithm"><span class="header-section-number">3</span> The VPP retrieval Algorithm</a>
  <ul class="collapse">
  <li><a href="#outline" id="toc-outline" class="nav-link" data-scroll-target="#outline"><span class="header-section-number">3.1</span> Outline</a></li>
  <li><a href="#basic-underlying-assumptions" id="toc-basic-underlying-assumptions" class="nav-link" data-scroll-target="#basic-underlying-assumptions"><span class="header-section-number">3.2</span> Basic underlying assumptions</a></li>
  <li><a href="#related-and-previous-applications" id="toc-related-and-previous-applications" class="nav-link" data-scroll-target="#related-and-previous-applications"><span class="header-section-number">3.3</span> Related and previous applications</a>
  <ul class="collapse">
  <li><a href="#time-series-smoothing" id="toc-time-series-smoothing" class="nav-link" data-scroll-target="#time-series-smoothing"><span class="header-section-number">3.3.1</span> Time-series smoothing</a></li>
  <li><a href="#output-product" id="toc-output-product" class="nav-link" data-scroll-target="#output-product"><span class="header-section-number">3.3.2</span> Output product</a></li>
  <li><a href="#evaluation-of-short-time-series-processing-for-operational-phenology-retrieval" id="toc-evaluation-of-short-time-series-processing-for-operational-phenology-retrieval" class="nav-link" data-scroll-target="#evaluation-of-short-time-series-processing-for-operational-phenology-retrieval"><span class="header-section-number">3.3.3</span> Evaluation of Short Time-Series Processing for Operational Phenology Retrieval</a></li>
  </ul></li>
  <li><a href="#detailed-algorithm-description" id="toc-detailed-algorithm-description" class="nav-link" data-scroll-target="#detailed-algorithm-description"><span class="header-section-number">3.4</span> Detailed algorithm description</a>
  <ul class="collapse">
  <li><a href="#extraction-of-phenology-and-productivity-parameters-using-timesat" id="toc-extraction-of-phenology-and-productivity-parameters-using-timesat" class="nav-link" data-scroll-target="#extraction-of-phenology-and-productivity-parameters-using-timesat"><span class="header-section-number">3.4.1</span> Extraction of phenology and productivity parameters using TIMESAT</a></li>
  <li><a href="#pre-processing" id="toc-pre-processing" class="nav-link" data-scroll-target="#pre-processing"><span class="header-section-number">3.4.2</span> Pre-processing</a></li>
  <li><a href="#ppi-fitting-to-daily-data" id="toc-ppi-fitting-to-daily-data" class="nav-link" data-scroll-target="#ppi-fitting-to-daily-data"><span class="header-section-number">3.4.3</span> PPI fitting to daily data</a></li>
  <li><a href="#extraction-of-phenology-and-productivity-parameters" id="toc-extraction-of-phenology-and-productivity-parameters" class="nav-link" data-scroll-target="#extraction-of-phenology-and-productivity-parameters"><span class="header-section-number">3.4.4</span> Extraction of phenology and productivity parameters</a></li>
  <li><a href="#defining-growing-season-thresholds" id="toc-defining-growing-season-thresholds" class="nav-link" data-scroll-target="#defining-growing-season-thresholds"><span class="header-section-number">3.4.5</span> Defining growing season thresholds</a></li>
  <li><a href="#assigning-seasons-to-years" id="toc-assigning-seasons-to-years" class="nav-link" data-scroll-target="#assigning-seasons-to-years"><span class="header-section-number">3.4.6</span> Assigning seasons to years</a></li>
  <li><a href="#defining-thresholds-for-omitting-seasons-and-regions" id="toc-defining-thresholds-for-omitting-seasons-and-regions" class="nav-link" data-scroll-target="#defining-thresholds-for-omitting-seasons-and-regions"><span class="header-section-number">3.4.7</span> Defining thresholds for omitting seasons and regions</a></li>
  <li><a href="#vpp-qa" id="toc-vpp-qa" class="nav-link" data-scroll-target="#vpp-qa"><span class="header-section-number">3.4.8</span> VPP QA</a></li>
  </ul></li>
  <li><a href="#limitations-of-the-algorithm" id="toc-limitations-of-the-algorithm" class="nav-link" data-scroll-target="#limitations-of-the-algorithm"><span class="header-section-number">3.5</span> Limitations of the algorithm</a></li>
  <li><a href="#risk-of-failure-and-mitigation-measures" id="toc-risk-of-failure-and-mitigation-measures" class="nav-link" data-scroll-target="#risk-of-failure-and-mitigation-measures"><span class="header-section-number">3.6</span> Risk of failure and mitigation measures</a></li>
  </ul></li>
  <li><a href="#post-processing-and-file-naming" id="toc-post-processing-and-file-naming" class="nav-link" data-scroll-target="#post-processing-and-file-naming"><span class="header-section-number">4</span> Post processing and file naming</a>
  <ul class="collapse">
  <li><a href="#post-processing" id="toc-post-processing" class="nav-link" data-scroll-target="#post-processing"><span class="header-section-number">4.1</span> Post processing</a></li>
  <li><a href="#file-naming" id="toc-file-naming" class="nav-link" data-scroll-target="#file-naming"><span class="header-section-number">4.2</span> File naming</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">5</span> References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">6</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#comparison-of-tprod-using-version-5.0-and-4.0" id="toc-comparison-of-tprod-using-version-5.0-and-4.0" class="nav-link" data-scroll-target="#comparison-of-tprod-using-version-5.0-and-4.0"><span class="header-section-number">6.1</span> Comparison of TPROD using Version 5.0 and 4.0</a></li>
  <li><a href="#comparison-of-mr-vpp-naming-scheme-in-version-5.0-and-4.0" id="toc-comparison-of-mr-vpp-naming-scheme-in-version-5.0-and-4.0" class="nav-link" data-scroll-target="#comparison-of-mr-vpp-naming-scheme-in-version-5.0-and-4.0"><span class="header-section-number">6.2</span> Comparison of MR-VPP naming scheme in Version 5.0 and 4.0</a></li>
  <li><a href="#detailed-comparison-of-2025-mr-vpp-v5.0-issue-2.0-results-from-short-and-long-input-time-series" id="toc-detailed-comparison-of-2025-mr-vpp-v5.0-issue-2.0-results-from-short-and-long-input-time-series" class="nav-link" data-scroll-target="#detailed-comparison-of-2025-mr-vpp-v5.0-issue-2.0-results-from-short-and-long-input-time-series"><span class="header-section-number">6.3</span> Detailed Comparison of 2025 MR-VPP V5.0 Issue 2.0 Results from Short and Long Input Time Series</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="MRVPP_MRVPP_ATBD_v2.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Add Version to the title's metadata
    //
    // Skip when there's no version (e.g. document-type with version off) so we
    // don't render an empty "Version" heading, and when the doc has no
    // title-meta block at all (nothing to append to). Quarto renders an unset
    // meta key as the placeholder "?meta:version", so treat that as empty too.
    const raw = `2.0.0`.trim();
    const version = raw.startsWith("?meta:") ? "" : raw;
    const titleMetaEl = document.querySelector(".quarto-title-meta");
    if (!version || !titleMetaEl) return;
    const wrapperDiv = document.createElement("div");
    wrapperDiv.innerHTML = `
        <div class="quarto-title-meta-heading">Version</div>
        <div class="quarto-title-meta-contents">
          <p>2.0.0</p>
        </div>
      `;
    titleMetaEl.appendChild(wrapperDiv);
  });
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Medium Resolution Vegetation Phenology and Productivity (MR-VPP) – Algorithm Theoretical Basis Document (ATBD)</h1>
<p class="subtitle lead">Copernicus Land Monitoring Service</p>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>European Environment Agency (EEA) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><br>
<strong>Contact:</strong></p>
<div data-custom-style="LeftAlign">
<p>European Environment Agency (EEA)<br>
Kongens Nytorv 6<br>
1050 Copenhagen K<br>
Denmark<br>
<a href="https://land.copernicus.eu/"><strong>https://land.copernicus.eu/</strong></a></p>
</div>
<p>Reference Document for <strong>Version 5.0 Issue 2.0</strong></p>
<p><strong>Lead service providers for production (SC#5 MR-VPP 2025 Extension):</strong> Flemish Institute for Technological Research, Belgium (VITO), Lund University, Sweden.</p>
<p><strong>Produced by:</strong> Hongxiao Jin<sup>1</sup>, Zhanzhang Cai<sup>1</sup>, Lars Eklundh<sup>1</sup>, Else Swinnen<sup>2</sup>, Walter Horsten<sup>2</sup>, Tim Ng<sup>2</sup></p>
<p><sup>1</sup> Lund University, Lund, Sweden<br>
<sup>2</sup> VITO</p>
<p><strong>Disclaimer:</strong> © European Union, Copernicus Land Monitoring Service 2026, European Environment Agency (EEA) All Rights Reserved. No parts of this document may be photocopied, reproduced, stored in retrieval system, or transmitted, in any form or by any means whether electronic, mechanical, or otherwise without the prior written permission of the European Environment Agency.</p>
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"ItemList","itemListElement":[{"@type":"ImageObject","caption":"Figure  1.  MODIS  tile  layout:  23  tiles  covering  the  EEA-39  extent  and  Ukraine  (h20v03).","url":"MRVPP_MRVPP_ATBD_v2-media/img-ed65a43813c9f8636ab49e9a99041236.png"},{"@type":"ImageObject","caption":"Figure  2.  Processing  flowchart  for  Plant  Phenology  Index  (PPI)  calculation","url":"MRVPP_MRVPP_ATBD_v2-media/img-9b74f7681b6cb6837197dad9dc3be062.png"},{"@type":"ImageObject","caption":"Figure  3.  Processing  overview  of  VPP  and  PPI  time  series,  illustrated  as  a  flowchart.","url":"MRVPP_MRVPP_ATBD_v2-media/img-d83e527495e21e29642a0fa3fb6686a7.png"},{"@type":"ImageObject","caption":"Figure  4.  TIMESAT  processing  overview  illustrated  as  a  flowchart.","url":"MRVPP_MRVPP_ATBD_v2-media/img-584e4dfd6ae1178e149b1991921e7e93.png"},{"@type":"ImageObject","caption":"Figure  5.  TIMESAT  module  for  extracting  phenological  parameters.","url":"MRVPP_MRVPP_ATBD_v2-media/img-95c01c5f9bd858e2d5cfeb660289d497.png"},{"@type":"ImageObject","caption":"Figure  6.  Illustration  of  season  identification  based  on  coarse-season  peaks  (A-D)  and  corresponding  loca  minima  (a-d).  Red  markers  indicate  season  start  and  end  points.","url":"MRVPP_MRVPP_ATBD_v2-media/img-6bec814ea766febc6cde5d7bfd808050.png"},{"@type":"ImageObject","caption":"Figure  7.  Illustration  of  VPP  parameter  quality  assurance  (QA)  determination.","url":"MRVPP_MRVPP_ATBD_v2-media/img-b1a39741ad3489a9ede924eceb8b60ab.png"},{"@type":"ImageObject","caption":"Figure  8.  Structure  of  the  8-bit  quality  flags  used  for  phenology  retrieval  over  a  season.","url":"MRVPP_MRVPP_ATBD_v2-media/img-07c8b38d2e9c4aa2768a258a1f8e3986.png"},{"@type":"ImageObject","caption":"Figure  9.  Pan-European  TPROD  (Season  1,  2018)  from  MR-VPP  Versions  4.0  and  5.0,  showing  correction  of  artifacts  in  desert/barren  areas,  in  particular  in  N.  Africa:  (a)  MR-VPP  version  4.0,  (b)  MR-VPP  version  5.0.","url":"MRVPP_MRVPP_ATBD_v2-media/img-9b6bf208da4a290a31d1d20e7cd36dd9.png"},{"@type":"ImageObject","caption":"","url":"MRVPP_MRVPP_ATBD_v2-media/img-4e7996f2eab8c321fb188c0c010123ef.png"},{"@type":"ImageObject","caption":"","url":"MRVPP_MRVPP_ATBD_v2-media/img-2c5e4c7e031a5a7b445d1d6e2fae3030.png"},{"@type":"ImageObject","caption":"Figure  10.  Comparison  of  representative  vegetation  phenology  and  productivity  (VPP)  metrics  derived  using  long  time  series  inputs  and  short  time  series  inputs  for  the  2025  growing  season  over  Europe.  Panels  show  spatial  distributions  of  (a,  b)  start  of  season  date  (SOSD),  (c,  d)  end  of  season  date  (EOSD),  (e,  f)  seasonal  amplitude  (AMPL),  and  (g,  h)  total  productivity  (TPROD)  generated  from  the  long  time  series  (2000-2026)  and  short  time  series  (2024-2026)  processing  approaches.","url":"MRVPP_MRVPP_ATBD_v2-media/img-7cf817c6c6a0fb7dfba709884fbdfc62.png"},{"@type":"ImageObject","caption":"Figure  11.  Density  scatter  plot  comparison  between  vegetation  phenology  and  productivity  (VPP)  metrics  derived  from  long  time  series  inputs  and  short  time  series  inputs  for  the  2025  growing  season  1  over  Europe:  (a)  start  of  season  date  (SOSD),  (b)  end  of  season  date  (EOSD),  (c)  seasonal  amplitude  (AMPL),  and  (d)  total  productivity  (TPROD).  Hexagon  color  indicates  relative  point  density  normalized  to  the  maximum  density.  Dashed  black  lines  represent  the  1:1  relationship,  and  red  lines  indicate  robust  linear  regression  fitted  after  exclusion  of  extreme  outliers  using  percentile-based  filtering.  Reported  statistics  include  coefficient  of  determination  (R²),  bias,  RMSE,  MAE,  and  the  proportion  of  pixels  located  within  a  predefined  consistency  threshold  around  the  1:1  line.","url":"MRVPP_MRVPP_ATBD_v2-media/img-00fc8e231c1e7e3ed79e717cc61b37f8.png"},{"@type":"ImageObject","caption":"Figure  12.  Density  scatter  plot  comparison  between  vegetation  phenology  and  productivity  (VPP)  metrics  derived  from  long  time  series  inputs  and  short  time  series  inputs  for  the  2025  growing  season  2  over  Europe:  (a)  start  of  season  date  (SOSD),  (b)  end  of  season  date  (EOSD),  (c)  seasonal  amplitude  (AMPL),  and  (d)  total  productivity  (TPROD).  Hexagon  color  indicates  relative  point  density  normalized  to  the  maximum  density.  Dashed  black  lines  represent  the  1:1  relationship,  and  red  lines  indicate  robust  linear  regression  fitted  after  exclusion  of  extreme  outliers  using  percentile-based  filtering.  Reported  statistics  include  coefficient  of  determination  (R²),  bias  (VPP_short  -  VPP_long),  RMSE,  MAE,  and  the  proportion  of  pixels  located  within  a  predefined  consistency  threshold  around  the  1:1  line.","url":"MRVPP_MRVPP_ATBD_v2-media/img-b08a8132b99b9a13639476be6698a2ca.png"}]}
</script>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="mr-vpp-products-summary" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="mr-vpp-products-summary"><span class="header-section-number">1.1</span> MR-VPP products summary</h2>
<p>Copernicus is the European Union’s Earth Observation Programme, providing information services based on satellite observations and in situ (non-space) data. These services are <strong>freely and openly</strong> accessible through six thematic components: atmosphere monitoring, marine environment monitoring, land monitoring, climate change, emergency management, and security.</p>
<p>Within this framework, the <strong>Copernicus Land Monitoring Service (CLMS)</strong> delivers a suite of high-quality bio-geophysical products that describe the status and dynamics of the land surface across pan-European regions. These products support monitoring of vegetation, crop health, the water cycle, the energy budget, and the terrestrial cryosphere. CLMS ensures timely production and delivery, while maintaining consistent, long-term time series for continuous environmental analysis. CLMS is jointly implemented by the European Environment Agency (EEA) and the European Commission’s Joint Research Centre (JRC).</p>
<p><strong>Vegetation phenology</strong> describes the timing of recurring plant life cycle events throughout the growing season. With remote sensing, phenology is typically monitored using time series of vegetation indices. These indices capture the amount of green biomass and the intensity of photosynthetic activity, reflecting plant functional types and their seasonal dynamics.</p>
<p>As part of the pan-European component, CLMS produces and disseminates the <strong>Medium-Resolution Vegetation Phenology and Productivity (MR-VPP) product suite</strong> (Version 5.0). MR-VPP V5.0 is generated at 500 m spatial resolution from MODIS Collection 6.1 NBAR time series (<em>Terra</em> and <em>Aqua</em>) covering 26 February 2000 to 16 April 2026. The dataset includes annual VPP parameters and 5-day plant phenology index (PPI) outputs, along with quality flags. MR-VPP V5.0 is produced over the EEA39 area (32 EU member states, the UK, and six cooperating countries in the Western Balkans).</p>
<p>MR-VPP Version 5.0 Issue 2.0 extends the product coverage to the year 2025. The phenology retrieval for 2025 was generated using MODIS PPI input data spanning 1 January 2024 to 19 April 2026, ensuring complete temporal coverage for the target year while limiting the processing window. In addition, the full MODIS PPI archive from 24 February 2000 to 19 April 2026 was reprocessed to evaluate the consistency between phenology estimates derived from a limited temporal window and those obtained from the complete long-term record.</p>
<p>Unlike previous releases, this version is accompanied by an <strong>Algorithm Theoretical Basis Document (ATBD)</strong>. Earlier MR-VPP versions were only supported by evaluation reports, partly because the <strong>High-Resolution VPP (HR-VPP)</strong> product was developed immediately after MR-VPP, and an ATBD was prepared for HR-VPP. While HR-VPP and MR-VPP share core algorithms and theoretical foundations, HR-VPP introduced improvements in data handling and adopted a clearer naming scheme. Additional enhancements were implemented in the CLMS CGLOPS1 global Land Surface Phenology (LSP) product, based on PROBA-V and Sentinel-3 OLCI NBAR data. With suitable adaptations, these advances are now applied to MR-VPP to exploit the long MODIS time series (25+ years) and daily observation interval.</p>
<p>Both MR-VPP V5.0 and the previous V4.0 [AD03] rely on MODIS NBAR Collection 6.1 as input. However, V5.0 introduces several important improvements (Table 1), including daily rather than 5-day inputs, an extended time series, enhanced PPI calculation with improved artifact handling, updated QA flags, an upgraded TIMESAT version, harmonized output formats, and a naming scheme consistent with other CLMS LSP products.</p>
<div class="tbl-caption">
<p>Table 1. Key improvements in MR-VPP Version 5.0 compared with Version 4.0.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<tbody>
<tr class="odd">
<td style="background-color: #70ad47; color: #ffffff; font-weight: bold">Items</td>
<td style="background-color: #70ad47; color: #ffffff; font-weight: bold">Version 5.0 Issue 2.0</td>
<td style="background-color: #70ad47; color: #ffffff; font-weight: bold">Version 4.0</td>
<td style="background-color: #70ad47; color: #ffffff; font-weight: bold">Comments</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda"><strong>Input data interval</strong></td>
<td style="background-color: #e2efda">daily</td>
<td style="background-color: #e2efda">5-day</td>
<td style="background-color: #e2efda">Higher observation frequency reduces uncertainties</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda"><strong>Input data span</strong></td>
<td style="background-color: #e2efda">Jan 2024 – Apr 2026 (short TS) vs.<br>
Feb 2000 – Apr 2026 (long TS)</td>
<td style="background-color: #e2efda">2000 Feb – 2023 Dec</td>
<td style="background-color: #e2efda">Longer record improves interannual consistency; 2024 end-season estimates are more reliable with added 2025 data</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda"><strong>PPI calculation</strong></td>
<td style="background-color: #e2efda">Improved; excludes artifacts in bright desert/barren regions</td>
<td style="background-color: #e2efda">Artifacts persisted</td>
<td style="background-color: #e2efda">New checks avoid estimates of false seasonality in bright sandy areas</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda"><strong>PPI range</strong></td>
<td style="background-color: #e2efda">[-1, 5]</td>
<td style="background-color: #e2efda">[-1, 3]</td>
<td style="background-color: #e2efda">Expanded range captures broader vegetation density</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda"><strong>PPI quality flags</strong></td>
<td style="background-color: #e2efda">Based on QA of both red and NIR NBAR, align with CGLOPS1 LSP (Sentinel-3)</td>
<td style="background-color: #e2efda">Simple binary flag (good/bad)</td>
<td style="background-color: #e2efda">More accurate, supports weighted TIMESAT processing</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda"><strong>TIMESAT</strong></td>
<td style="background-color: #e2efda">Version 4.2 with Python API and enhanced data check and smoothing.</td>
<td style="background-color: #e2efda">Customized version 4.1.2</td>
<td style="background-color: #e2efda">New release validated globally by third parties in CLMS CGLOPS1 LSP project</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda"><strong>Output VPP format</strong></td>
<td style="background-color: #e2efda">Harmonized with other CLMS LSP products</td>
<td style="background-color: #e2efda">Legacy format</td>
<td style="background-color: #e2efda">Increases user consistency</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda"><strong>Naming scheme</strong></td>
<td style="background-color: #e2efda">Consistent with other CLMS LSP products</td>
<td style="background-color: #e2efda">Legacy scheme</td>
<td style="background-color: #e2efda">See Table 7 in Appendix 6.2 for naming correspondence between Version 5.0 and Version 4.0</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda"><strong>MR-VPP PPI</strong></td>
<td style="background-color: #e2efda">Raw PPI + QA flags at 5-day intervals</td>
<td style="background-color: #e2efda">Fitted PPI; limited data re-use</td>
<td style="background-color: #e2efda">Raw PPI + QA archived for consistency and to enable re-use</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda"><strong>Phenology retrieval temporal strategy</strong></td>
<td style="background-color: #e2efda">Short processing window fully covering target year, including one preceding year and ~3 months after target year</td>
<td style="background-color: #e2efda">Full multi-decadal time series preferred</td>
<td style="background-color: #e2efda">High consistency confirmed between short time series and long-term processing; supports efficient near-real-time operational updates</td>
</tr>
</tbody>
</table>
<p>This ATBD documents the theoretical foundation and algorithmic details of MR-VPP V5.0 production. The product suite provides 13 VPP parameters, derived for up to two growing seasons per year, including the dates of season start, peak, and end, as well as seasonal integrals, derivatives, amplitudes, and maximum values. These are estimated from smooth seasonal trajectories of the <strong>Plant Phenology Index (PPI)</strong>, which combines MODIS NBAR reflectance in red and near-infrared bands. PPI is sensitive to seasonal variations in photosynthetically active leaf area index (LAI). Because these dynamics are driven by solar radiation, temperature, and precipitation, the MR-VPP parameters provide essential indicators of climate impacts on vegetation.</p>
</section>
<section id="scope-and-objectives" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="scope-and-objectives"><span class="header-section-number">1.2</span> Scope and objectives</h2>
<p>The purpose of this document is to describe the physical and mathematical basis of the algorithm used to generate Version 5.0 of the CLMS MR-VPP product for the years 2000-2025 (26 years).</p>
<p>MR-VPP 500 m Version 5.0 is based on MODIS NBAR data (Collection 6.1) [AD05] and builds on the revised CGLOPS LSP processing chain (Version 2.0) [AD04]. A key improvement is the correction of artifacts in sparsely vegetated areas with bright soil background. In earlier versions, seasonal variations in the Plant Phenology Index (PPI) were incorrectly affected by fluctuations in the Difference Vegetation Index (DVI) of bright soil pixels—signals unrelated to vegetation phenology. These artifacts were particularly evident in Version 4.0 over northern Africa (outside the pan-European domain) but had previously been overlooked.</p>
<p>A further objective of Issue 2.0 is to assess the feasibility of generating reliable phenology products using temporally limited input datasets that fully cover the target year, together with one preceding year and the first months following the target year. This post-target-year extension is intended to provide sufficient temporal context for stabilizing end-of-season detection and reducing edge effects, while avoiding the need to reprocess the complete multi-decadal archive for each annual update. As MR-VPP is expected to transition toward Sentinel-3 OLCI-based continuation, with cross-calibration against the MODIS archivef, this evaluation is relevant for developing efficient annual LSP update strategies. In particular, it supports the assessment of near-real-time (NRT) production approaches for annual LSP metrics, where NRT refers to the annual LSP product for the most recent completed year because LSP metrics are produced at an annual time step. Computational efficiency and storage requirements are therefore critical operational considerations.</p>
<p>This ATBD provides a reference for the theoretical background, algorithmic details, and practical considerations underlying the generation and use of the MR-VPP Version 5.0 product.</p>
</section>
<section id="document-structure" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="document-structure"><span class="header-section-number">1.3</span> Document structure</h2>
<p>This document is structured as follows:</p>
<ul>
<li>Chapter 1 provides an introduction to the document.</li>
<li>Chapter 2 describes input data and vegetation index for MR-VPP.</li>
<li>Chapter 3 describes the retrieval methodology.</li>
<li>Chapter 4 describes Post processing and file naming.</li>
<li>Chapter 5 lists the references cited in this document.</li>
<li>Chapter 6 contains an appendix with additional information.</li>
</ul>
</section>
<section id="related-documents" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="related-documents"><span class="header-section-number">1.4</span> Related documents</h2>
<section id="applicable-documents" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="applicable-documents"><span class="header-section-number">1.4.1</span> Applicable documents</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 88%">
</colgroup>
<tbody>
<tr class="odd">
<td>[AD01]</td>
<td>FRAMEWORK SERVICE CONTRACT EEA/DIS/RO/23/007/LOT 1, 26-06-2024</td>
</tr>
<tr class="even">
<td>[AD02]</td>
<td>EEA.DIS.R0.23.007_RfS_SC3, 3rd specific contract under Framework Contract nr. EEA/DIS/R0/23/007/LOT 1, 02-04-2025</td>
</tr>
<tr class="odd">
<td>[AD03]</td>
<td>Medium Resolution Vegetation Phenology and Productivity (MR-VPP) Monitoring Report, v4.0, 13-05-2024, Framework contract No EEA/DIS/R0/22/009/Lot 1</td>
</tr>
<tr class="even">
<td>[AD04]</td>
<td>CGLOPS1_ATBD_LSP300m-V2.0: Algorithm Theoretical Basis Document of normalized Land Surface Phenology 300m, version 2.0</td>
</tr>
<tr class="odd">
<td>[AD05]</td>
<td>MODIS User Guide V006 and V006.1, MCD43A4 NBAR Product, https://www.umb.edu/spectralmass/modis-user-guide-v006-and-v0061/mcd43a4-nbar-product/</td>
</tr>
</tbody>
</table>
</section>
<section id="reference-documents" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="reference-documents"><span class="header-section-number">1.4.2</span> Reference documents</h3>
<p>All references throughout this document are described in Chapter 5.</p>
</section>
</section>
<section id="terminology" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="terminology"><span class="header-section-number">1.5</span> Terminology</h2>
<section id="terms" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="terms"><span class="header-section-number">1.5.1</span> Terms</h3>
<p><strong>Phenology</strong> is broadly defined as <em>“…the study of recurring plant and animal life cycle stages, especially their timing and relationships with weather and climate.”</em> (Schwartz, 2013), c.f. (Abbe, 1905; Lieth, 1974). In MR-VPP we define phenology more specifically as the timing of development of photosynthetically active leaf foliage. Plant phenology is driven by environment cues on internal physiological processes at molecular level that produce externally observable responses (Chmura et al., 2019; Singh et al., 2017). Some of these responses, such as budset or in-wintering, are difficult to observe, whereas the development of leaf area is visible both to human observers on the ground, and from satellite data. The development of leaf foliage can be described using green <strong>leaf area index (LAI)</strong>, which is a biophysical parameter defined as the one-sided leaf surface area over the corresponding ground area. <em>Phenological parameters (phenometrics)</em> describe specific stages on the seasonal growth curve (seasonal trajectory), e.g., the date of the start of the season, the length of the season, or the date of the end of the season.</p>
<p>Leaf area controls the development of plant biomass and the uptake of energy for conversion of light into carbon through photosynthesis, thus <strong>productivity</strong>. Productivity is a term denoting the growth of vegetation, often described as <em>gross primary productivity (GPP)</em>, which is the growth due to photosynthesis, or <em>net primary productivity (NPP</em> GPP minus the respiration). The absorption of solar energy by the plant canopy is often measured by FAPAR, fraction of absorbed photosynthetically active radiation. There is an asymptotic relationship between FAPAR and LAI leading to a saturation of FAPAR at high LAI. Therefore, FAPAR is a less useful descriptor than LAI of leaf foliage development at high vegetation density. For formulating phenology parameters across a large area, like the European continent, an index that relates closely to LAI is therefore advantageous.</p>
</section>
<section id="abbreviations-and-acronyms" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="abbreviations-and-acronyms"><span class="header-section-number">1.5.2</span> Abbreviations and acronyms</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 80%">
</colgroup>
<tbody>
<tr class="odd">
<td>AD</td>
<td>Applicable document</td>
</tr>
<tr class="even">
<td>AMPL</td>
<td>Seasonal amplitude</td>
</tr>
<tr class="odd">
<td>ATBD</td>
<td>Algorithm Theoretical Basis Document</td>
</tr>
<tr class="even">
<td>BRDF</td>
<td>Bi-directional Reflectance Distribution Function</td>
</tr>
<tr class="odd">
<td>CGLOPS</td>
<td>Copernicus Global Land Operations</td>
</tr>
<tr class="even">
<td>CLMS</td>
<td>Copernicus Land Monitoring Service</td>
</tr>
<tr class="odd">
<td>COG</td>
<td>Cloud Optimized GeoTIFF</td>
</tr>
<tr class="even">
<td>DL</td>
<td>Double-logistic fitting</td>
</tr>
<tr class="odd">
<td>DOY</td>
<td>Day of year</td>
</tr>
<tr class="even">
<td>DVI</td>
<td>Difference Vegetation Index</td>
</tr>
<tr class="odd">
<td>EEA</td>
<td>European Environment Agency</td>
</tr>
<tr class="even">
<td>EOS</td>
<td>End of season</td>
</tr>
<tr class="odd">
<td>EOSD</td>
<td>End of season date</td>
</tr>
<tr class="even">
<td>EOSV</td>
<td>Vegetation index value at EOSD</td>
</tr>
<tr class="odd">
<td>EPSG</td>
<td>European Petroleum Survey Group geodetic parameter dataset</td>
</tr>
<tr class="even">
<td>ESA</td>
<td>European Space Agency</td>
</tr>
<tr class="odd">
<td>EU</td>
<td>European Union</td>
</tr>
<tr class="even">
<td>EVI</td>
<td>Enhanced Vegetation Index</td>
</tr>
<tr class="odd">
<td>EVI2</td>
<td>Two-band Enhanced Vegetation Index</td>
</tr>
<tr class="even">
<td>FAPAR</td>
<td>Fraction of Absorbed Photosynthetically Active Radiation</td>
</tr>
<tr class="odd">
<td>GDAL</td>
<td>Geospatial Data Abstraction Library</td>
</tr>
<tr class="even">
<td>GIMMS</td>
<td>Global Inventory Modeling and Mapping Studies</td>
</tr>
<tr class="odd">
<td>GPP</td>
<td>Gross Primary Production</td>
</tr>
<tr class="even">
<td>HLS</td>
<td>Harmonized Landsat Sentinel-2</td>
</tr>
<tr class="odd">
<td>HPC</td>
<td>High-Performance Computing</td>
</tr>
<tr class="even">
<td>HR-VPP</td>
<td>CLMS High Resolution Vegetation Phenology and Productivity dataset</td>
</tr>
<tr class="odd">
<td>IGBP</td>
<td>International Geosphere-Biosphere Program</td>
</tr>
<tr class="even">
<td>JRC</td>
<td>Joint Research Center</td>
</tr>
<tr class="odd">
<td>LAI</td>
<td>Leaf Area Index</td>
</tr>
<tr class="even">
<td>LAEA</td>
<td>Lambert azimuthal equal-area projection</td>
</tr>
<tr class="odd">
<td>LENGTH</td>
<td>Length of season</td>
</tr>
<tr class="even">
<td>LSLOPE</td>
<td>Slope of the green-up period</td>
</tr>
<tr class="odd">
<td>LSP</td>
<td>Land Surface Phenology</td>
</tr>
<tr class="even">
<td>LUNARC</td>
<td>Lund University Centre for Scientific and Technical Computing</td>
</tr>
<tr class="odd">
<td>MAE</td>
<td>Mean Absolute Error</td>
</tr>
<tr class="even">
<td>MAXD</td>
<td>Day of the maximum of season</td>
</tr>
<tr class="odd">
<td>MAXV</td>
<td>Maximum value of the season at MAXD</td>
</tr>
<tr class="even">
<td>MCD43A2</td>
<td>MODIS BRDF-Albedo Quality product</td>
</tr>
<tr class="odd">
<td>MCD43A4</td>
<td>MODIS Nadir BRDF-Adjusted Reflectance product</td>
</tr>
<tr class="even">
<td>MDVI</td>
<td>Maximum DVI over a time period</td>
</tr>
<tr class="odd">
<td>MINV</td>
<td>Minimum value of season.</td>
</tr>
<tr class="even">
<td>MODIS</td>
<td>Moderate Resolution Imaging Spectroradiometer</td>
</tr>
<tr class="odd">
<td>MR-VPP</td>
<td>CLMS Medium Resolution Vegetation Phenology and Productivity dataset</td>
</tr>
<tr class="even">
<td>NAISS</td>
<td>National Academic Infrastructure for Supercomputing in Sweden</td>
</tr>
<tr class="odd">
<td>NASA</td>
<td>National Aeronautics and Space Administration of the USA</td>
</tr>
<tr class="even">
<td>NBAR</td>
<td>Nadir BRDF-Adjusted Reflectance</td>
</tr>
<tr class="odd">
<td>NDVI</td>
<td>Normalized Difference Vegetation Index</td>
</tr>
<tr class="even">
<td>NIR</td>
<td>Near-Infrared</td>
</tr>
<tr class="odd">
<td>NPP</td>
<td>Net Primary Productivity</td>
</tr>
<tr class="even">
<td>NRT</td>
<td>Near-real-time</td>
</tr>
<tr class="odd">
<td>OLCI</td>
<td>Ocean and Land Color Instrument</td>
</tr>
<tr class="even">
<td>PPI</td>
<td>Plant Phenology Index</td>
</tr>
<tr class="odd">
<td>PROBA-V</td>
<td>Project for On-Board Autonomy - Vegetation</td>
</tr>
<tr class="even">
<td>QA</td>
<td>Quality Assessment</td>
</tr>
<tr class="odd">
<td>RMSE</td>
<td>Root Mean Square Error</td>
</tr>
<tr class="even">
<td>RSLOPE</td>
<td>Slope of the green-down period</td>
</tr>
<tr class="odd">
<td>SC</td>
<td>Specific Contract</td>
</tr>
<tr class="even">
<td>SOS</td>
<td>Start of season</td>
</tr>
<tr class="odd">
<td>SOSD</td>
<td>Start of season date</td>
</tr>
<tr class="even">
<td>SOSV</td>
<td>Vegetation index value at SOSD</td>
</tr>
<tr class="odd">
<td>SP</td>
<td>Spline fitting</td>
</tr>
<tr class="even">
<td>SPROD</td>
<td>Seasonal productivity</td>
</tr>
<tr class="odd">
<td>TIMESAT</td>
<td>a program for analyzing time-series of satellite sensor data</td>
</tr>
<tr class="even">
<td>TOC</td>
<td>Top-of-Canopy</td>
</tr>
<tr class="odd">
<td>TPROD</td>
<td>Total productivity</td>
</tr>
<tr class="even">
<td>TS</td>
<td>Time series</td>
</tr>
<tr class="odd">
<td>ULUND</td>
<td>Lund University</td>
</tr>
<tr class="even">
<td>USA</td>
<td>United States of America</td>
</tr>
<tr class="odd">
<td>VI</td>
<td>Vegetation Index</td>
</tr>
<tr class="even">
<td>VIIRS</td>
<td>Visible Infrared Imaging Radiometer Suite</td>
</tr>
<tr class="odd">
<td>VITO</td>
<td>Flemish Institute for Technological Research</td>
</tr>
<tr class="even">
<td>VPP</td>
<td>Vegetation Phenology and Productivity</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="input-data-and-plant-phenology-index-for-mr-vpp" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Input data and plant phenology index for MR-VPP</h1>
<section id="input-data" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="input-data"><span class="header-section-number">2.1</span> Input data</h2>
<p>The MR-VPP product is developed from daily 500 m resolution MODIS Nadir Bidirectional Reflectance Distribution Function Adjusted Reflectance (NBAR; MCD43A4 v6.1) together with the MODIS BRDF-Albedo Quality (MCD43A2 v6.1), both obtained from NASA’s Level-1 and Atmosphere Archive &amp; Distribution System (LAADS) Distributed Active Archive Center (DAAC)[^1]. For the period 24 February 2000 to 19 April 2026, this amounts to about 9,200 images per tile for the full archive, and 1 January 2024 to 19 April 2026 for the short time series. [^1]: https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/61/</p>
<p>The NBAR data are corrected using Ross-Thick-Li-Sparse Reciprocal BRDF model to adjust TOC values as if they were collected from a nadir view at local solar noon time. Although generated daily, each NBAR value is based on a 16-day retrieval window, with the date corresponding to the center of the period (Strahler et al., 1999). This product combines observations from both the <em>Terra</em> and <em>Aqua</em> satellites, choosing the observation at clear sky conditions from each retrieval cycle.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-ed65a43813c9f8636ab49e9a99041236.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1. MODIS tile layout: 23 tiles covering the EEA-39 extent and Ukraine (h20v03).</figcaption>
</figure>
</div>
<p>In total, 23 MODIS tiles are required to cover the entire EEA-39 extent and Ukraine of tile h20v03 (Figure 1). Each tile consists of 2400×2400 pixels, and in total ~12 TB of data were downloaded to LUNARC’s COSMOS cluster hosted by Lund University, Sweden. LUNARC operates in partnership with NAISS, the Sweden’s largest research infrastructure for high-performance computing (HPC), providing AI, storage, cloud services, and expert support for advanced scientific research in Sweden.</p>
</section>
<section id="calculation-of-ppi" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="calculation-of-ppi"><span class="header-section-number">2.2</span> Calculation of PPI</h2>
<p>For estimation of phenology, we chose a spectral vegetation index that is responsive to photosynthetically active leaf area index: the plant phenology index (PPI, Jin &amp; Eklundh, 2014).</p>
<p>The formula of PPI (unit: m²·m⁻², Jin &amp; Eklundh, 2014) is:</p>
<p><span class="math display">\[PPI = -K \times \ln\left(\frac{MDVI - DVI}{MDVI - DVI_s}\right)\]</span> Eq. 1</p>
<p>where DVI is the difference vegetation index. DVI is a dimensionless index and is obtained by subtracting the red TOC reflectance from the near-infrared (NIR) TOC reflectance,</p>
<p><span class="math display">\[DVI = R_{NIR} - R_{RED}\]</span> Eq. 2</p>
<p><em>MDVI</em> is the temporal potential maximum DVI, which represents infinite leaf layers for a pixel with leaf traits that suit the environmental conditions of the location. <em>MDVI</em> is estimated from long-term MODIS NBAR data of over 25 years. The MDVI estimation from the maximum value of a long time series of DVI works well in densely vegetated areas due to the asymptotic nature of vegetation spectral reflectance (Tucker, 1977). However, in sparsely vegetated areas, the asymptotic MDVI level cannot be reached, resulting in a small MDVI value. In this case, the logarithm expression in Eq. 1 results in unrealistically large PPI values like dense vegetation. To address this issue, a lower boundary empirical value of 0.18 is assigned as the MDVI value for pixels below this threshold, providing an enhanced spatial consistency in VPP. <span class="math inline">\(DVI_s\)</span> is introduced in Eq.1 to minimize influences of soil background on vegetation signals, and meanwhile to capture sparse vegetation areas such as drylands. The steps for estimating <em>MDVI</em> and <span class="math inline">\(DVI_s\)</span> are <em>MDVI</em> = max(DVI), from the 25 years data. <em>MDVI</em> = 0.18 , for <em>MDVI</em> &lt; 0.18 . <span class="math inline">\(DVI_s\)</span> = min(0.09, <span class="math inline">\(MDVI_{scene}\)</span>/4) , and <span class="math inline">\(MDVI_{scene}\)</span> = max(<em>MDVI</em>) over a scene. The K factor in PPI is a gain factor given by</p>
<p><span class="math display">\[K = \frac{1}{4Q_E} \frac{1+MDVI}{1-MDVI}\]</span> Eq. 3</p>
<p>where <span class="math inline">\(Q_E\)</span> is the canopy leaf light extinction efficiency, the ratio of leaf cross-section area on the light beam to leaf geometric cross-section area, unit: m²·m⁻² (Hapke, 1993). <span class="math inline">\(Q_E\)</span> is related to leaf inclination angle, solar angle, and the diffuse fraction of solar radiation:</p>
<p><span class="math display">\[Q_E = d_c + (1-d_c) \cdot \frac{G}{\cos(\theta_i)}\]</span> Eq. 4</p>
<p>where G is a geometric function of leaf angular distribution, set to 0.5, and <span class="math inline">\(d_c\)</span> is an instantaneous diffuse fraction of solar radiation at 12:00 local solar noon of the day, which is used in MODIS NBAR data normalization. The diffuse fraction at solar zenith angle <span class="math inline">\(\theta_i\)</span> for clear sky of standard atmosphere conditions is used:</p>
<p><span class="math display">\[d_c = 0.0336 + \frac{0.0477}{\cos(\theta_i)}\]</span> Eq. 5</p>
<p>The range of PPI is restricted between -1 and 5 to reduce the noise sensitivity in high PPI values. Values below -1 are set to -1, and values above 5 are set to 5. We keep the negative PPI values over non-vegetated areas (water, snow, bare ground, etc.) for later potential use in exploring land surface properties other than vegetation. However, in the bare ground areas of bright sandy deserts, seasonal variations in PPI time series occur and are not related to vegetation phenology, which generates artifacts in MR-VPP Version 4.0 and the CGLOPS LSP Version 1.0. Therefore, we use the criteria of <span class="math inline">\(R_{RED} &gt; 0.35\)</span>, and <span class="math inline">\(DVI &gt; 0.05\)</span> to identify these bright pixels and assign a value of 0 to PPI. See Figure 9 in Appendix 6.1 for an example of the sum of the Total Production (TPROD) in Season 1 of 2018 generated using Version 5.0, compared with that using Version 4.0.</p>
<p>The calculation of PPI involves three main steps (Figure 2).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-9b74f7681b6cb6837197dad9dc3be062.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2. Processing flowchart for Plant Phenology Index (PPI) calculation</figcaption>
</figure>
</div>
</section>
<section id="calculation-of-ppi-quality-flag-qa-values-for-timesat-processing" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="calculation-of-ppi-quality-flag-qa-values-for-timesat-processing"><span class="header-section-number">2.3</span> Calculation of PPI Quality flag (QA) values for TIMESAT processing</h2>
<p>The PPI data quality is estimated from the NBAR red and NIR bands quality dataset MCD43A2, as a weighted quality of QA of red and NIR bands, with higher weight (0.9) assigned to NIR, and lower weight (0.1) to red. This is because the NIR band provides the majority of information of the vegetation canopy and the red band provides more limited information, due to the fact that NIR light easily can penetrate through a dense canopy and be reflected back to satellite sensors, while red light hardly penetrates through a dense canopy and is mainly reflected back with information from the canopy surface. PPI data quality flag values and weights for TIMESAT processing are listed in Table 2.</p>
<div class="tbl-caption">
<p>Table 2. PPI data quality flag QA values and weights for TIMESAT.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 38%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>QA</th>
<th>PPI quality</th>
<th>Weight for TIMESAT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-1</td>
<td>Good</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>Fair</td>
<td>0.6</td>
</tr>
<tr class="odd">
<td>3-253</td>
<td>Poor</td>
<td>0.1</td>
</tr>
<tr class="even">
<td>≥ 254</td>
<td>No-use</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>The output PPI dataset information is shown in Table 3. Note that PPI data are not planned for further storage or public access.</p>
<div class="tbl-caption">
<p>Table 3. PPI data format and data quality flag QA.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Name</strong></td>
<td><strong>Data type</strong></td>
<td><strong>Scale, offset</strong></td>
<td><strong>Data range</strong></td>
<td><strong>Fill value</strong></td>
<td><strong>Description</strong></td>
<td><strong>Unit</strong></td>
</tr>
<tr class="even">
<td>PPI</td>
<td>INT16</td>
<td>0.001,0</td>
<td>-1000~5000</td>
<td>32767</td>
<td>PPI data</td>
<td>m²·m⁻²</td>
</tr>
<tr class="odd">
<td rowspan="6" style="vertical-align: middle">QA</td>
<td rowspan="6" style="vertical-align: middle">UINT8</td>
<td rowspan="6" style="vertical-align: middle">-</td>
<td rowspan="6" style="vertical-align: middle">0~255</td>
<td>255: no observation</td>
<td rowspan="6" style="vertical-align: middle">Quality flag</td>
<td rowspan="6" style="vertical-align: middle">-</td>
</tr>
<tr class="even">
<td>254: invalid PPI due to<br>
MDVI&lt;0.09 or infinite PPI</td>
</tr>
<tr class="odd">
<td>253: bright soil pixels, with<br>
PPI forced to 0 when<br>
R<sub>RED</sub> &gt; 0.35, and<br>
DVI &gt; 0.05</td>
</tr>
<tr class="even">
<td>252: PPI&lt;-1, truncated to -1</td>
</tr>
<tr class="odd">
<td>251: PPI&gt;5, truncated to 5</td>
</tr>
<tr class="even">
<td>250: DVI&gt;MDVI, complex<br>
PPI value</td>
</tr>
</tbody>
</table>
</section>
<section id="specification-of-output-ppi-data" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="specification-of-output-ppi-data"><span class="header-section-number">2.4</span> Specification of output PPI data</h2>
<p>Table 3 shows specifications of the input PPI data used for phenology parameter estimation. While daily input data were applied for VPP estimation, the archive PPI time series were extracted at a nominal 5-day interval (the 1st, 6th, 11th, 16th, 21st, and 26th of each month) to reduce storage requirements, resulting in 72 dates per year. This 5-day interval is aligned with other CLMS dekadal products (1st, 11th, and 21st of each month), and can also be aggregated to a half-month interval (1st, and 16th of each month), facilitating comparison with other satellite data, e.g.&nbsp;GIMMS NDVI/LAI.</p>
</section>
</section>
<section id="the-vpp-retrieval-algorithm" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> The VPP retrieval Algorithm</h1>
<section id="outline" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="outline"><span class="header-section-number">3.1</span> Outline</h2>
<p>Calculation of MR-VPP products is based on the following steps: (1) Data preparation: downloading of MODIS NBAR data from NASA’s data archive center. (2) Generation of the plant phenology index (PPI) from NBAR at 500 m resolution and daily interval. (3) Processing with TIMESAT version 4.2 to derive smooth seasonal trajectories and phenology and productivity parameters (Figure 3).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-d83e527495e21e29642a0fa3fb6686a7.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3. Processing overview of VPP and PPI time series, illustrated as a flowchart.</figcaption>
</figure>
</div>
<p>For valid land pixels, PPI is computed at daily time step from NBAR. The maximum difference vegetation index (MDVI) values from the entire NBAR time series from 2000 to 2025 are used in the computation. We then process the PPI series in TIMESAT 4.2 to smooth the signal, derive the phenology/productivity metrics, and generate the corresponding QA flags (see Section 3.4).</p>
</section>
<section id="basic-underlying-assumptions" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="basic-underlying-assumptions"><span class="header-section-number">3.2</span> Basic underlying assumptions</h2>
<p>In this product, phenology is inferred from smoothed seasonal trajectories of vegetation indices that track canopy greening and browning. PPI is designed to follow changes in green (photosynthesizing) leaf area while limiting background effects from soil and snow. Accordingly, the seasonal PPI curves are treated as approximations of the canopy growth cycle — onset, peak, and senescence. There is no universally accepted rule for defining the curve or its key points; however, using a consistent procedure enables robust trend analyses and comparisons across years and regions, and supports interpretation of vegetation responses to phenological drivers (e.g., weather, climate, management, or disturbances).</p>
</section>
<section id="related-and-previous-applications" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="related-and-previous-applications"><span class="header-section-number">3.3</span> Related and previous applications</h2>
<p>The CLMS MR-VPP 5.0 is modelled on similar principles as developed for the CLMS <em>High Resolution Vegetation Phenology and Productivity (HR-VPP)²</em>, and CLMS CGLOPS land surface phenology V2.0³. However, MODIS provides a 25+ year observation record, and such a long-term series is critical for reliable phenology estimation. [^2]: https://land.copernicus.eu/en/products/vegetation?tab=vegetation_phenology_and_productivity_parameters [^3]: https://land.copernicus.eu/en/news/global-land-surface-phenology-2024-product-available</p>
<p>This is the updated version of MR-VPP V5.0 from V4.0 and other previous versions. These previous versions have demonstrated extreme climate impacts over Europe, for example, drought over two decades⁴ and vegetation responses (Jin et al., 2023). However, due to piecewise baseline estimates [AD03], the data amendment with partial processing of additional years only may reduce reliability of inter-annual comparisons. Moreover, VPP parameters estimated for bare areas with no vegetation but bright soil presented false seasonality. Similar artifacts were also observed in CGLOPS1 LSP Version 1.0 using PROBA-V and Sentinel-3 data. These artifacts are caused by seasonal variations in the DVI value of bright soil pixels (likely due to residual seasonal aerosol variations), which then propagate to PPI and subsequently to VPP estimates. Bright sand pixels can have a PPI value as high as sparse green vegetation (0.2~1.0). The seasonal changes of sand pixels are thus caused by variations unrelated to plant phenology. [^4]: https://www.eea.europa.eu/en/analysis/indicators/drought-impact-on-ecosystems-in-europe</p>
<p>In the new version (V5.0), we have the following updates to mark bright sand pixels:</p>
<ol type="1">
<li>Add thresholds on red reflectance and DVI to flag bright-sand pixels and force ‘no-vegetation’ status (PPI = 0, for <span class="math inline">\(R_{RED} &gt; 0.35\)</span>, and <span class="math inline">\(DVI &gt; 0.05\)</span>).</li>
<li>Introduced a PPI QA flag (QA=253) to track these changes, enabling statistical analysis of the number of such pixels later.</li>
</ol>
<section id="time-series-smoothing" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="time-series-smoothing"><span class="header-section-number">3.3.1</span> Time-series smoothing</h3>
<p>Many methods exist for smoothing time series and constructing seasonal trajectories. None is universally best (White et al., 2009). Below we summarize commonly used techniques.</p>
<p><strong>Double-logistic curve fitting</strong> has become a standard in vegetation phenology research because of its robustness to noisy observations (Fisher et al., 2006; Jönsson et al., 2018; Zhang et al., 2003). The method applies non-linear least-squares optimization to functions that capture the general seasonal profile of canopy development. Curve properties such as amplitude, width, and slope are governed by a small set of parameters, and input data points can be weighted by their quality flags. In the CLMS HR-VPP project, TIMESAT 4.1 employed double-logistic fitting to handle the irregular sampling of Sentinel-2 observations (Tian et al., 2021).</p>
<p><strong>Asymmetric Gaussian fitting</strong> (Jönsson &amp; Eklundh, 2002) shares similarities with the double-logistic approach in that both use non-linear least-squares optimization. However, the asymmetric Gaussian function involves five non-linear parameters compared to four in the double logistic, making it more data-demanding to achieve stable fitting. This optional method is implemented in TIMESAT 3.</p>
<p><strong>Fourier and sinusoidal (harmonic) functions</strong> represent another class of smoothing approaches (Menenti et al., 1993; Olsson &amp; Eklundh, 1994; Jönsson &amp; Eklundh, 2004; Roerink et al., 2000). These rely on combining sinusoidal terms to approximate seasonal signals. The order of the expansion sets the upper limit on the number of seasons detectable within a time series. Such methods are useful for identifying both the number and approximate timing of growing seasons in noisy data, however, lack accuracy when limiting the models to a few terms.</p>
<p>When input data are frequent and of high quality, several more flexible techniques can be applied. <strong>Savitzky-Golay filtering</strong> (Chen et al., 2004) smooths series by fitting low-order polynomials within a moving window. The choice of window size controls the trade-off between smoothing and fidelity to the data. While the method can yield excellent agreement with ground observations when carefully tuned, poor parameterization may degrade results (Cai et al., 2017). <strong>Smoothing splines</strong> (Craven &amp; Wahba, 1978) provide continuous daily curves with smooth derivatives, but as with Savitzky-Golay, selecting a globally appropriate smoothing parameter is challenging (Cai et al., 2017). <strong>Cubic splines</strong>, which fit piecewise cubic polynomials, offer smoother reconstructions than lower-order splines and effectively reduce artificial oscillations. This method is available in TIMESAT 4. Another option is the <strong>Whittaker smoother</strong> (Eilers, 2003), which, like splines, balances smoothness and flexibility, and has been shown to adapt well to rapid variations in time series (Atzberger &amp; Eilers, 2011).</p>
<p>Ultimately, the characteristics of the input data should guide the choice of method. Given the high temporal resolution of the MR-VPP inputs and following extensive evaluation, we selected <strong>cubic spline fitting</strong> as the preferred time-series smoothing technique for CLMS MR-VPP.</p>
</section>
<section id="output-product" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="output-product"><span class="header-section-number">3.3.2</span> Output product</h3>
<p>The CLMS MR-VPP parameters are listed in Table 4. All output parameters are computed per image pixel and reported to separate output files.</p>
<div class="tbl-caption">
<p>Table 4. List of the 13 MR-VPP parameters and the auxiliary quality flag (QA).</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 29%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd" style="background-color:#f2f2f2">
<td><strong>No.</strong></td>
<td><strong>Name</strong></td>
<td><strong>Data type</strong></td>
<td><strong>Scale, offset</strong></td>
<td><strong>Data range</strong></td>
<td><strong>Fill value</strong></td>
<td><strong>Description</strong></td>
<td><strong>Unit</strong></td>
</tr>
<tr class="even">
<td>1</td>
<td>SOSD</td>
<td>INT16</td>
<td>1, 0</td>
<td>[-365, 365]</td>
<td>-9999</td>
<td>Day of start-of-season</td>
<td rowspan="3" style="text-align: center; vertical-align: middle;">Day-Of-Year</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>2</td>
<td>EOSD</td>
<td>INT16</td>
<td>1, 0</td>
<td>[0, 730]</td>
<td>-9999</td>
<td>Day of end-of-season</td>
</tr>
<tr class="even">
<td>3</td>
<td>MAXD</td>
<td>INT16</td>
<td>1, 0</td>
<td>[0, 366]</td>
<td>-9999</td>
<td>Day of maximum-of-season</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>4</td>
<td>SOSV</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 5000]</td>
<td>-9999</td>
<td>Vegetation index value at SOSD</td>
<td rowspan="5" style="text-align: center; vertical-align: middle;">PPI unit<br>
m²·m⁻²</td>
</tr>
<tr class="even">
<td>5</td>
<td>EOSV</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 5000]</td>
<td>-9999</td>
<td>Vegetation index value at EOSD</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>6</td>
<td>MINV</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 5000]</td>
<td>-9999</td>
<td>Average vegetation index value of minima on left and right sides of each season</td>
</tr>
<tr class="even">
<td>7</td>
<td>MAXV</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 5000]</td>
<td>-9999</td>
<td>Vegetation index value at MAXD</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>8</td>
<td>AMPL</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 5000]</td>
<td>-9999</td>
<td>Season amplitude (MAXV – MINV)</td>
</tr>
<tr class="even">
<td>9</td>
<td>LENGTH</td>
<td>INT16</td>
<td>1, 0</td>
<td>[0, 730]</td>
<td>-9999</td>
<td>Length of Season (number of days between start and end)</td>
<td style="text-align: center;">day</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>10</td>
<td>LSLOPE</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 1000]</td>
<td>-9999</td>
<td>Slope of the green-up period</td>
<td rowspan="2" style="text-align: center; vertical-align: middle;">m²·m⁻²·day⁻¹</td>
</tr>
<tr class="even">
<td>11</td>
<td>RSLOPE</td>
<td>INT16</td>
<td>0.001, 0</td>
<td>[0, 1000]</td>
<td>-9999</td>
<td>Slope of the green-down period (absolute value of decreasing rate)</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>12</td>
<td>TPROD</td>
<td>INT16</td>
<td>1, 0</td>
<td>[0, 2000]</td>
<td>-9999</td>
<td>Total productivity. Growing season integral computed as the sum of all daily values between SOSD and EOSD.</td>
<td rowspan="2" style="text-align: center; vertical-align: middle;">m²·m⁻²·day</td>
</tr>
<tr class="even">
<td>13</td>
<td>SPROD</td>
<td>INT16</td>
<td>1, 0</td>
<td>[0, 2000]</td>
<td>-9999</td>
<td>Seasonal productivity. Growing season integral computed as sum of all daily values minus their base level value.</td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td colspan="2" style="text-align: center;"><strong>Aux QA</strong></td>
<td>UINT8</td>
<td>-</td>
<td>-</td>
<td>255</td>
<td>Quality flag</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
<p>The valid range of the Start-Of-Season Date (SOSD) is [-365, 365]. A negative SOSD value indicates that the peak of growing season is located in the current year and the start of the season is located in the previous year. Similarly, the valid range of the End-Of-Season Date (EOSD) is [0, 730]. Values of EOSD &gt; 365 indicate that the peak of growing season is in the current year, while the end of the season extends into the following year.</p>
<p>For reliable interpretation, VPP parameters should always be used in conjunction with their associated Quality Assurance (QA) flag (see Section 3.4.8). When only a single year of data is available, phenology metrics with values below 0 or above 425 (365 + 60) are considered unreliable (QA = 3, poor quality; see Table 5). When multiple years of data are used as input, these metrics may be reliable depending on the corresponding QA values.</p>
</section>
<section id="evaluation-of-short-time-series-processing-for-operational-phenology-retrieval" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="evaluation-of-short-time-series-processing-for-operational-phenology-retrieval"><span class="header-section-number">3.3.3</span> Evaluation of Short Time-Series Processing for Operational Phenology Retrieval</h3>
<p>Phenology retrieval generally benefits from long and temporally continuous input time series, which provide temporal context for seasonal curve fitting and reduce edge effects near the beginning and end of the analysed period. However, operational Land Surface Phenology (LSP) production also requires timely delivery and efficient use of computational and storage resources. Reprocessing complete multi-decadal archives for every annual update may therefore be inefficient, particularly for continental- to global-scale applications.</p>
<p>To assess whether a shorter processing window can provide reliable annual phenology estimates, MR-VPP Version 5.0 Issue 2.0 was generated for the year 2025 using MODIS PPI input data from 1 January 2024 to 19 April 2026. This window fully covers the target year, includes one preceding year, and extends into the first months following the target year to support end-of-season detection and reduce temporal boundary effects. The resulting 2025 VPP products were compared with independently generated products derived from the full MODIS PPI archive spanning 24 February 2000 to 19 April 2026.</p>
<p>The comparison showed strong overall consistency between the short time series and full-archive processing approaches, particularly for the primary growing season. Timing, magnitude, and productivity metrics showed high agreement, with only small systematic differences. The secondary growing season showed somewhat larger uncertainty, reflecting its more limited spatial extent and weaker seasonal signal in Europe. Overall, the evaluation indicates that a temporally buffered short time series approach can support efficient annual LSP update strategies, while full-archive processing remains preferable for retrospective consistency checks and non-time-critical reprocessing.</p>
<p>Detailed comparison methods, spatial examples, scatter plots, metric-level statistics, and QA analyses are provided in Appendix 6.3.</p>
</section>
</section>
<section id="detailed-algorithm-description" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="detailed-algorithm-description"><span class="header-section-number">3.4</span> Detailed algorithm description</h2>
<section id="extraction-of-phenology-and-productivity-parameters-using-timesat" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="extraction-of-phenology-and-productivity-parameters-using-timesat"><span class="header-section-number">3.4.1</span> Extraction of phenology and productivity parameters using TIMESAT</h3>
<p>An overview of TIMESAT version 4.2 processing is shown in Figure 4.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-584e4dfd6ae1178e149b1991921e7e93.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4. TIMESAT processing overview illustrated as a flowchart.</figcaption>
</figure>
</div>
</section>
<section id="pre-processing" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="pre-processing"><span class="header-section-number">3.4.2</span> Pre-processing</h3>
<p>TIMESAT receives PPI time-series data that may include some noise and temporal gaps. The pre-processing is the first processing step for the input data, containing several parts: determining the base level, setting data weights, adding control points to data gaps, and determining the coarse growing seasons. The pre-processing has four purposes: (1) to transfer the input data (PPI and QA data) to pixel-oriented time series for the later processing; (2) to fill large data gaps exceeding 91 continuous days with a predefined base level; (3) to preliminarily determine whether a time series needs to be excluded from processing; and (4) to make a preliminary analysis of seasonality (number of potential seasons) and to establish the rough timing of each coarse season.</p>
<p>The 91-day gap detection and filling mainly address the high-latitude winter seasons that are masked out in the BRDF data. We determine the base level as the 5th percentile of the acceptable quality PPI observations (weight &gt; 0) over the full period. The weights of PPI values in a time series are set based on QA data. Further, weights of PPI observations that are lower than the base level are set to 0. The base level is used for filling long term data gaps and assisting the cubic spline fitting. TIMESAT will detect whether there are enough good-quality data on the time series, see Section 3.4.7 for details. This step is to ensure the operation of fitting the cubic spline functions.</p>
</section>
<section id="ppi-fitting-to-daily-data" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="ppi-fitting-to-daily-data"><span class="header-section-number">3.4.3</span> PPI fitting to daily data</h3>
<p>We fit a cubic smoothing spline <span class="math inline">\(S_p(t)\)</span> (Craven &amp; Wahba, 1978) to the PPI time series by minimizing the value of the following criterion function <span class="math inline">\(C_p\)</span></p>
<p><span class="math display">\[C_p = \sum_{i=1}^{n} \lbrace w_i [y_i - S_p(t_i)]^2 \rbrace + p \int_{-\infty}^{+\infty} [S^{''}_p(t)]^2 dt\]</span> Eq. 7</p>
<p>where <span class="math inline">\(t_i, i = 1, ..., n\)</span> is time vector and <span class="math inline">\(y_i\)</span> are corresponding PPI values. Each point in the time series is associated with an input weight <span class="math inline">\(w_i\)</span>. The smoothing parameter p controls the shape of the spline, varying from an exactly interpolating spline (p = 0) to a straight line (p → ∞). The p value is set to 1,000, which can reduce the impact of noise while preserving sufficient local variation.</p>
</section>
<section id="extraction-of-phenology-and-productivity-parameters" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="extraction-of-phenology-and-productivity-parameters"><span class="header-section-number">3.4.4</span> Extraction of phenology and productivity parameters</h3>
<p>An initial pixel-wise estimate of the growing seasons’ start and stop dates (“coarse seasons”) is determined by applying a sinusoidal function fitting</p>
<p><span class="math display">\[f(t) = c_1 + c_2 \sin(\omega t) + c_3 \cos(\omega t) + c_4 \sin(2\omega t) + c_5 \cos(2\omega t)\]</span> Eq. 8</p>
<p>where ω = 2π/n, and n is the number of points, f(t) is the corresponding PPI value at time t. The coarse seasons are further used for defining potential seasons.</p>
<p>The derivation of VPP metrics from the daily PPI time series follows the approaches used in CGLOPS1 LSP product [AD04], and is similar to those applied in the MCD12Q2 and HLS phenology products (Bolton et al., 2020; Gray et al., 2019). TIMESAT takes the smoothed daily PPI, extracts the metrics, applies quality checks, and assigns seasons to calendar years (Figure 5). In total, thirteen metrics together with per-season quality information are produced for delivery (Table 4).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-95c01c5f9bd858e2d5cfeb660289d497.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5. TIMESAT module for extracting phenological parameters.</figcaption>
</figure>
</div>
</section>
<section id="defining-growing-season-thresholds" class="level3" data-number="3.4.5">
<h3 data-number="3.4.5" class="anchored" data-anchor-id="defining-growing-season-thresholds"><span class="header-section-number">3.4.5</span> Defining growing season thresholds</h3>
<p>TIMESAT locates SOSD and EOSD using relative-amplitude thresholds on the fitted seasonal curve. After SOS and EOS are set, the remaining VPP metrics are computed. For consistency with previous versions of MR-VPP and other related CLMS products, we use 25% for SOSD and 15% for EOSD.</p>
</section>
<section id="assigning-seasons-to-years" class="level3" data-number="3.4.6">
<h3 data-number="3.4.6" class="anchored" data-anchor-id="assigning-seasons-to-years"><span class="header-section-number">3.4.6</span> Assigning seasons to years</h3>
<p>Because some seasons cross calendar boundaries, we assign seasons to the year of their peak (e.g., a–A–b to 2018; c–C–d–D–e to 2019 in Figure 6). MR-VPP stores up to two seasons per year: the two with the largest peaks are kept and presented chronologically, so Season 1 can be the minor or the main season depending on timing.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-6bec814ea766febc6cde5d7bfd808050.png" class="img-fluid figure-img"></p>
<figcaption>Figure 6. Illustration of season identification based on coarse-season peaks (A-D) and corresponding loca minima (a-d). Red markers indicate season start and end points.</figcaption>
</figure>
</div>
</section>
<section id="defining-thresholds-for-omitting-seasons-and-regions" class="level3" data-number="3.4.7">
<h3 data-number="3.4.7" class="anchored" data-anchor-id="defining-thresholds-for-omitting-seasons-and-regions"><span class="header-section-number">3.4.7</span> Defining thresholds for omitting seasons and regions</h3>
<p>In three scenarios, the VPP are set to nodata-values (with QA=255) and the TIMESAT processing is skipped (BOX 1):</p>
<ol type="1">
<li><p>If the total number of valid observations is too low, less than 3 points per year on average throughout the entire time series. This primarily applies to areas lacking valid observations.</p></li>
<li><p>If the first-order PPI differences are minimal, less than 3 points per year on average with first-order differences greater than 1×10⁻⁶. This indicates weak seasonality, making it difficult to precisely determine phenological parameters, and mainly occurs with sustained evergreen vegetation.</p>
<p><strong>BOX 1 Pseudo script for omitting seasons and regions</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ot">! </span><span class="ex">Default.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">process</span> = True</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">Point_Threshold</span> = 3<span class="pp">*</span>number_of_years</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">Scenario</span> 1</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ot">! </span><span class="ex">total_npt:</span> total number of points</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="ot">! </span><span class="ex">y:</span> PPI time series of daily interval</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">count</span><span class="op">[</span>points with weight &gt; 0<span class="op">]</span> <span class="op">&lt;</span> Point_Threshold, <span class="ex">process</span> = False</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="ex">Scenario</span> 2</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">count</span><span class="op">[</span>diff(y) &gt; 1.d-6<span class="op">]</span> <span class="op">&lt;</span> Point_Threshold, <span class="ex">process</span> = False</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="ex">Scenario</span> 3</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">count</span><span class="op">[</span>y &gt; (0.02<span class="pp">*</span>peak_value)<span class="op">]</span> <span class="op">&lt;</span> Point_Threshold, <span class="ex">process</span> = False</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>If the number of points with PPI values above 2% of the peak value is less than 3 points per year on average. This primarily filters out inland water bodies with low PPI values occasionally exhibiting few extreme values possibly caused by noise.</p></li>
</ol>
</section>
<section id="vpp-qa" class="level3" data-number="3.4.8">
<h3 data-number="3.4.8" class="anchored" data-anchor-id="vpp-qa"><span class="header-section-number">3.4.8</span> VPP QA</h3>
<p>VPP Quality Assurance (QA) is assigned based on both the average of PPI-BRDF-weights (defined from the PPI QA in Table 2 and the total number of valid observations in each of the phenological phases: green-up, green peak, and green-down of the growing season. They are defined as the left 20% – left 80%, left 80% – right 80%, and right 80% – right 20% of the season amplitude respectively (Figure 7). The overall QA is determined based on the leverage of the quality of the three phases.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-b1a39741ad3489a9ede924eceb8b60ab.png" class="img-fluid figure-img"></p>
<figcaption>Figure 7. Illustration of VPP parameter quality assurance (QA) determination.</figcaption>
</figure>
</div>
<p>Eight-bit (1 byte) QA values are generated as specified in Figure 8, and the details of bit values and descriptions are listed in Table 5. The QA flag is written to one output file for each season.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-07c8b38d2e9c4aa2768a258a1f8e3986.png" class="img-fluid figure-img"></p>
<figcaption>Figure 8. Structure of the 8-bit quality flags used for phenology retrieval over a season.</figcaption>
</figure>
</div>
<div class="tbl-caption">
<p>Table 5. MR-VPP QA flags and descriptions of phenology quality.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 54%">
</colgroup>
<tbody>
<tr class="odd">
<td colspan="3" style="background-color: #70ad47; color: #ffffff; font-weight: bold">SOS/Peak/EOS quality (two-bit values)</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda"><strong>QA byte</strong></td>
<td style="background-color: #e2efda"><strong>Quality</strong></td>
<td style="background-color: #e2efda"><strong>Description</strong></td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda">0</td>
<td style="background-color: #e2efda">Best</td>
<td style="background-color: #e2efda">More than 2 valid observations and average best PPI quality</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda">1</td>
<td style="background-color: #e2efda">Good</td>
<td style="background-color: #e2efda">More than 2 valid observations and average good PPI quality</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda">2</td>
<td style="background-color: #e2efda">Fair</td>
<td style="background-color: #e2efda">More than 2 valid observations and average fair PPI quality</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda">3</td>
<td style="background-color: #e2efda">Poor</td>
<td style="background-color: #e2efda">Average poor PPI data quality, or<br>
fewer than 3 observations, or more than 24 observations*</td>
</tr>
<tr class="odd">
<td colspan="3" style="text-align: center; background-color: #70ad47; color: #ffffff; font-weight: bold;">Overall quality (two-bit values)</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda">0</td>
<td style="background-color: #e2efda">Best</td>
<td style="background-color: #e2efda">No poor quality in three phenology phases</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda">1</td>
<td style="background-color: #e2efda">Good</td>
<td style="background-color: #e2efda">Maximum one phase with poor quality</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda">2</td>
<td style="background-color: #e2efda">Fair</td>
<td style="background-color: #e2efda">Maximum two phases with poor quality</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda">3</td>
<td style="background-color: #e2efda">Poor</td>
<td style="background-color: #e2efda">All three phases with poor quality**</td>
</tr>
<tr class="even">
<td colspan="3" style="text-align: center; background-color: #70ad47; color: #ffffff; font-weight: bold;">Summary of QA (byte values)</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda">QA &lt;127</td>
<td style="background-color: #e2efda">Good</td>
<td style="background-color: #e2efda">Overall good quality, no more than one poor results in three phases</td>
</tr>
<tr class="even">
<td style="background-color: #e2efda">QA &gt;127</td>
<td style="background-color: #e2efda">Poor</td>
<td style="background-color: #e2efda">Overall poor quality, more than one poor results in three phases</td>
</tr>
<tr class="odd">
<td style="background-color: #e2efda">QA=255</td>
<td style="background-color: #e2efda">Failure</td>
<td style="background-color: #e2efda">No input, or no phenology estimation, or all poor estimates</td>
</tr>
</tbody>
</table>
<p><strong>Notes:</strong></p>
<p>* Includes three situations: 1) fewer than 3 valid observations, 2) phenology phase shorter than 10 days, and 3) phenology phase longer than 4 months.</p>
<p>** Overlaps QA=255 for situations of no inputs, or no phenology estimation. In any case, the VPP retrieval is considered a failure.</p>
</section>
</section>
<section id="limitations-of-the-algorithm" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="limitations-of-the-algorithm"><span class="header-section-number">3.5</span> Limitations of the algorithm</h2>
<p>While PPI is a physically based index responding to green leaf area index (LAI) variations, it is based on some simplified assumptions. The vegetation canopy is treated like a turbid medium. In forest, violation of this assumption may be significant. Another assumption is that all vegetation is modelled with spherical (uniform) leaf angular distribution (G function in Eq. 4 is 0.5), but this may be violated in cases of erectophile (e.g.&nbsp;cereals) or planophile (e.g.&nbsp;potatoes) crops. Also, the lower bound of the MDVI value is empirically set at 0.18 based on exploratory analysis of MDVI histograms. The soil reflectance is assumed not to change with time.</p>
<p>PPI is scaled between DVI of soil and a maximum DVI. These values represent pure soil and an infinitely thick canopy layer for a specific site. Random variations and noise in these values do not affect the value of PPI much during the start and the end of the season, but may affect the PPI values greatly during the peak growing season. The logarithmic expression in PPI makes high values sensitive to noise. Therefore, the index has been limited to 5.0 in the global context, and it is further being smoothed using TIMESAT.</p>
<p>In crop rotation systems, the assumption of fixed level of maximum DVI is violated, which could lead to underestimation of the seasonal trajectory for the sparser crop. It has been noted that PPI is less sensitive to sparse vegetation than e.g.&nbsp;NDVI. This may lead to underestimation of winter crops or cover crops before the onset of the main growth period in springtime.</p>
<p>In sparsely vegetated areas, reaching an MDVI value representing a sufficiently thick leaf layer is unattainable, making it impossible to estimate a correct MDVI value from the long period of DVI time series. Therefore, we opt to assign an empirical MDVI value of 0.18 to pixels with MDVI values below this threshold.</p>
<p>Although longer time series are generally preferred in phenology estimation because they improve smoothing stability and reduce temporal edge effects, the present evaluation demonstrates that a substantially shorter processing window can provide highly consistent annual phenology estimates when the temporal coverage adequately brackets the target year. Nevertheless, regions with highly irregular seasonality, persistent cloud contamination, or incomplete annual observations may remain more sensitive to temporal window length. Therefore, for future 2026 VPP near-real-time implementations, it is recommended that the 2025 VPP product be regenerated using input time series spanning January 2024 to April 2027, termed non-time-critical product, thereby ensuring at least one complete calendar year of observations both before and after 2025.</p>
<p>Data gaps in winter are filled by the base level value, which may hide some winter crops of low PPI from being detected. Although the smoothing spline can adapt to situations of irregular seasons, there is still no guarantee that all local variation will be detected.</p>
<p>The gap detection method could influence the coarse season detection due to data availability. An extreme case is when there are only few good observations with high-quality PPI values in a window larger than 91 days, leading to seasons being determined by these few data points. To address such cases, we assigned a poor quality (QA=“11”) for the corresponding phenology metrics determined by fewer than 3 valid data points. Caution should be taken when using phenology metrics with poor QA.</p>
<p>The retrieval of a second growing season is generally associated with greater uncertainty than the first growing season. Double-season phenological cycles occur only in relatively limited regions of Europe, primarily in intensive agricultural areas or regions with favorable climatic conditions for multiple crop cycles. Consequently, the number of valid observations supporting the second season is often lower, and the corresponding phenology metrics typically exhibit lower QA compared with the primary growing season.</p>
<p>In addition, the assignment of a growing season to a specific calendar year is based on the timing of the seasonal maximum (MAXD). A season is attributed to the year in which the peak of the fitted seasonal trajectory occurs. For growing seasons with maxima occurring close to the beginning or end of a calendar year, this assignment may become ambiguous, particularly in regions with winter crops or prolonged seasonal activity spanning two calendar years. As a result, caution is required when interpreting annual productivity metrics strictly within calendar-year boundaries, especially for analyses involving second growing seasons or cross-year seasonal dynamics.</p>
<p>Finally, since the outputs only allow a maximum of two seasons per year, some minor seasons may be missed if there are more than two cycles per year, which means that the outputs may not present all cycles, e.g., in the case of multiple moving events in grasslands.</p>
</section>
<section id="risk-of-failure-and-mitigation-measures" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="risk-of-failure-and-mitigation-measures"><span class="header-section-number">3.6</span> Risk of failure and mitigation measures</h2>
<p>The estimation of VPP critically depends on the availability and quality of the input data, as any loss of accuracy in these data may propagate into the output products. MODIS, onboard <em>Terra</em> (launched in December 1999) and <em>Aqua</em> (launched in May 2002), was originally designed for a nine-year mission but has continued to operate for over 20 years due to their excellent performance. Over the extended lifetime, orbit drift has been a significant issue. For example, <em>Terra</em>’s equatorial crossing time shifted from its nominal 10:30 a.m. to about 9:00 a.m., while <em>Aqua</em> drifted from 1:30 p.m. to progressively late in the afternoon, thereby altering illumination geometry at the time of sensing. However, MR-VPP uses the MODIS MCD43A4 NBAR product, in which reflectance is BRDF-normalized to nadir view at local solar noon using multi-date, multi-angular Terra and Aqua observations. This normalization substantially reduces the direct influence of orbit-drift-related changes in viewing geometry. Remaining risks are mainly indirect, including changes in observation availability, angular sampling, atmospheric conditions, cloud and snow screening, and BRDF inversion quality during the later MODIS record. These effects should be monitored using the MCD43 quality layers and product consistency checks. To enhance reliability, VIIRS NBAR data (available since 2012) can serve as an alternative to the MODIS equivalent. Looking ahead, the transition from MODIS/VIIRS to Sentinel-3 OLCI for MR-VPP is underway, with particular attention to harmonizing the spectral band properties of the sensors.</p>
</section>
</section>
<section id="post-processing-and-file-naming" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Post processing and file naming</h1>
<section id="post-processing" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="post-processing"><span class="header-section-number">4.1</span> Post processing</h2>
<p>The 23 tiles data were mosaicked into a single image per variable to cover the entire pan-European region. Nearest-neighbour sampling was used to reproject the original sinusoidal projection to the Lambert azimuthal equal-area projection (LAEA, EPSG: 3035). The outputs were saved in Cloud Optimized GeoTIFF (COG) format. A bash script using GDAL to mosaic and reproject the VPP parameters is shown in BOX2. Similar post-processing was applied to PPI time series.</p>
<p><strong>BOX 2 Mosaic 23 tiles and reproject into LAEA projection.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#!/usr/bin/env bash</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">set</span> <span class="at">-euo</span> pipefail</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="va">ROOT</span><span class="op">=</span><span class="st">"~/proj/HRVPP2/MRVPP_2024/LSP"</span>     <span class="co"># input tiles root</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="va">OUTDIR</span><span class="op">=</span><span class="st">"./MRVPP_13VPP_QA"</span>               <span class="co"># output folder</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="va">SEASONS</span><span class="op">=</span><span class="va">(</span><span class="st">"season1"</span> <span class="st">"season2"</span><span class="va">)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="va">YEARS</span><span class="op">=</span><span class="va">($(</span><span class="fu">seq</span> 2000 2024<span class="va">))</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="va">PARAMS</span><span class="op">=</span><span class="va">(</span><span class="st">"SOSD"</span> <span class="st">"SOSV"</span> <span class="st">"LSLOPE"</span> <span class="st">"EOSD"</span> <span class="st">"EOSV"</span> <span class="st">"RSLOPE"</span> <span class="st">"LENGTH"</span> <span class="st">"MINV"</span> <span class="st">"MAXD"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="st">"MAXV"</span> <span class="st">"AMPL"</span> <span class="st">"TPROD"</span> <span class="st">"SPROD"</span> <span class="st">"QA"</span><span class="va">)</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional NoData (uncomment &amp; set if known; otherwise VRT inherits per-tile NoData)</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Target projection</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="va">T_SRS</span><span class="op">=</span><span class="st">"EPSG:3035"</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># target sampling method</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="va">RESAMP</span><span class="op">=</span><span class="st">"near"</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># target resolution or TR = (500 500) for 500 m resolution output</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="va">TR</span><span class="op">=</span><span class="va">(</span>392 392<span class="va">)</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> season <span class="kw">in</span> <span class="st">"</span><span class="va">${SEASONS</span><span class="op">[@]</span><span class="va">}</span><span class="st">"</span><span class="kw">;</span> <span class="cf">do</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> year <span class="kw">in</span> <span class="st">"</span><span class="va">${YEARS</span><span class="op">[@]</span><span class="va">}</span><span class="st">"</span><span class="kw">;</span> <span class="cf">do</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> param <span class="kw">in</span> <span class="st">"</span><span class="va">${PARAMS</span><span class="op">[@]</span><span class="va">}</span><span class="st">"</span><span class="kw">;</span> <span class="cf">do</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>      <span class="va">listfile</span><span class="op">=</span><span class="st">"</span><span class="va">$(</span><span class="fu">mktemp</span> <span class="st">"/tmp/list_</span><span class="va">${param}</span><span class="st">_</span><span class="va">${year}</span><span class="st">_</span><span class="va">${season}</span><span class="st">_XXXX.txt"</span><span class="va">)</span><span class="st">"</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>      <span class="va">vrt</span><span class="op">=</span><span class="st">"</span><span class="va">${OUTDIR}</span><span class="st">/</span><span class="va">${param}</span><span class="st">_</span><span class="va">${year}</span><span class="st">_</span><span class="va">${season}</span><span class="st">.vrt"</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>      <span class="va">tif</span><span class="op">=</span><span class="st">"</span><span class="va">${OUTDIR}</span><span class="st">/</span><span class="va">${param}</span><span class="st">_</span><span class="va">${year}</span><span class="st">_</span><span class="va">${season}</span><span class="st">.tif"</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>      <span class="va">tif3035</span><span class="op">=</span><span class="st">"</span><span class="va">${OUTDIR}</span><span class="st">/</span><span class="va">${param}</span><span class="st">_</span><span class="va">${year}</span><span class="st">_</span><span class="va">${season}</span><span class="st">_cog.tif"</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>      <span class="co"># find tiles</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>      <span class="fu">find</span> <span class="st">"</span><span class="va">$ROOT</span><span class="st">"</span> <span class="at">-type</span> f <span class="at">-name</span> <span class="st">"*_</span><span class="va">${year}</span><span class="st">_</span><span class="va">${season}</span><span class="st">_</span><span class="va">${param}</span><span class="st">.tif"</span> <span class="kw">|</span> <span class="fu">sort</span> <span class="op">&gt;</span> <span class="st">"</span><span class="va">$listfile</span><span class="st">"</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>      <span class="va">n</span><span class="op">=</span><span class="va">$(</span><span class="fu">wc</span> <span class="at">-l</span> <span class="op">&lt;</span> <span class="st">"</span><span class="va">$listfile</span><span class="st">"</span> <span class="kw">||</span> <span class="bu">echo</span> 0<span class="va">)</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>      <span class="bu">echo</span> <span class="st">"[</span><span class="va">${param}</span><span class="st"> </span><span class="va">${year}</span><span class="st"> </span><span class="va">${season}</span><span class="st">] Found </span><span class="va">$n</span><span class="st"> tiles"</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> <span class="kw">[[</span> <span class="st">"</span><span class="va">$n</span><span class="st">"</span> <span class="ot">-eq</span> 0 <span class="kw">]];</span> <span class="cf">then</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        <span class="bu">echo</span> <span class="st">"[</span><span class="va">${param}</span><span class="st"> </span><span class="va">${year}</span><span class="st"> </span><span class="va">${season}</span><span class="st">] No tiles -&gt; skip"</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>        <span class="fu">rm</span> <span class="at">-f</span> <span class="st">"</span><span class="va">$listfile</span><span class="st">"</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>      <span class="cf">fi</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>      <span class="co"># build VRT (inherit or set NoData)</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> <span class="bu">[</span> <span class="ot">-n</span> <span class="st">"</span><span class="va">${NODATA</span><span class="op">:-</span><span class="va">}</span><span class="st">"</span> <span class="bu">]</span><span class="kw">;</span> <span class="cf">then</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>          <span class="ex">gdalbuildvrt</span> <span class="at">-srcnodata</span> <span class="st">"</span><span class="va">$NODATA</span><span class="st">"</span> <span class="at">-vrtnodata</span> <span class="st">"</span><span class="va">$NODATA</span><span class="st">"</span> <span class="dt">\</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>              <span class="at">-input_file_list</span> <span class="st">"</span><span class="va">$listfile</span><span class="st">"</span> <span class="st">"</span><span class="va">$vrt</span><span class="st">"</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>          <span class="ex">gdalbuildvrt</span> <span class="at">-input_file_list</span> <span class="st">"</span><span class="va">$listfile</span><span class="st">"</span> <span class="st">"</span><span class="va">$vrt</span><span class="st">"</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>      <span class="cf">fi</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>      <span class="co"># translate to compressed, tiled BigTIFF (same SRS as inputs)</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>      <span class="ex">gdal_translate</span> <span class="st">"</span><span class="va">$vrt</span><span class="st">"</span> <span class="st">"</span><span class="va">$tif</span><span class="st">"</span> <span class="at">-of</span> COG <span class="at">-co</span> TILED=YES <span class="at">-co</span> COMPRESS=LZW <span class="at">-co</span> BIGTIFF=YES</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>      <span class="co"># prepare nodata flags for warp (if defined)</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>      <span class="va">warp_nodata_args</span><span class="op">=</span><span class="va">()</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> <span class="bu">[</span> <span class="ot">-n</span> <span class="st">"</span><span class="va">${NODATA</span><span class="op">:-</span><span class="va">}</span><span class="st">"</span> <span class="bu">]</span><span class="kw">;</span> <span class="cf">then</span></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>          <span class="va">warp_nodata_args</span><span class="op">=</span><span class="va">(</span>-srcnodata <span class="st">"</span><span class="va">$NODATA</span><span class="st">"</span> -dstnodata <span class="st">"</span><span class="va">$NODATA</span><span class="st">"</span><span class="va">)</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>      <span class="cf">fi</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>      <span class="co"># reproject to EPSG:3035 (LAEA); -multi + all CPUs for speed</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>      <span class="ex">gdalwarp</span> <span class="at">-t_srs</span> <span class="st">"</span><span class="va">$T_SRS</span><span class="st">"</span> <span class="at">-r</span> <span class="st">"</span><span class="va">$RESAMP</span><span class="st">"</span> <span class="at">-tr</span> <span class="st">"</span><span class="va">${TR</span><span class="op">[@]</span><span class="va">}</span><span class="st">"</span> <span class="at">-multi</span> <span class="at">-wo</span> NUM_THREADS=ALL_CPUS <span class="dt">\</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>          <span class="st">"</span><span class="va">${warp_nodata_args</span><span class="op">[@]</span><span class="va">}</span><span class="st">"</span> <span class="dt">\</span></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>          <span class="at">-co</span> TILED=YES <span class="at">-co</span> COMPRESS=LZW <span class="at">-co</span> BIGTIFF=YES <span class="dt">\</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>          <span class="st">"</span><span class="va">$tif</span><span class="st">"</span> <span class="st">"</span><span class="va">$tif3035</span><span class="st">"</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rm</span> <span class="at">-f</span> <span class="st">"</span><span class="va">$tif</span><span class="st">"</span></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rm</span> <span class="at">-f</span> <span class="st">"</span><span class="va">$listfile</span><span class="st">"</span> <span class="st">"</span><span class="va">$vrt</span><span class="st">"</span></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>      <span class="bu">echo</span> <span class="st">"[</span><span class="va">${param}</span><span class="st"> </span><span class="va">${year}</span><span class="st"> </span><span class="va">${season}</span><span class="st">] -&gt; </span><span class="va">$tif3035</span><span class="st">"</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>    <span class="cf">done</span></span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>  <span class="cf">done</span></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a><span class="cf">done</span></span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="bu">echo</span> <span class="st">"All done. EPSG:3035 outputs in: </span><span class="va">$OUTDIR</span><span class="st">"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="file-naming" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="file-naming"><span class="header-section-number">4.2</span> File naming</h2>
<p>The naming of delivered files is given in Table 6.</p>
<div class="tbl-caption">
<p>Table 6. Filename specifications for PPI and MR-VPP V5.0.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 46%">
<col style="width: 21%">
</colgroup>
<tbody>
<tr class="odd">
<td style="background-color: #c5e0b4; font-weight: bold">Data</td>
<td style="background-color: #c5e0b4; font-weight: bold">Filename</td>
<td style="background-color: #c5e0b4; font-weight: bold">Description</td>
</tr>
<tr class="even">
<td rowspan="13" style="text-align: center; background-color: #c5e0b4; vertical-align: middle;"><strong>MR-VPP<br>
13 VPP<br>
metrics</strong></td>
<td><code>SOSD_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Day of start-of-season</td>
</tr>
<tr class="odd">
<td><code>EOSD_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Day of end-of-season</td>
</tr>
<tr class="even">
<td><code>MAXD_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Day of maximum-of-season</td>
</tr>
<tr class="odd">
<td><code>SOSV_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Vegetation index value at SOSD</td>
</tr>
<tr class="even">
<td><code>EOSV_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Vegetation index value at EOSD</td>
</tr>
<tr class="odd">
<td><code>MINV_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Average vegetation index value of<br>
minima on left and right sides of<br>
each season</td>
</tr>
<tr class="even">
<td><code>MAXV_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Vegetation index value at MAXD</td>
</tr>
<tr class="odd">
<td><code>AMPL_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Season amplitude (MAXV - MINV)</td>
</tr>
<tr class="even">
<td><code>LENGTH_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Length of Season (number of days<br>
between start and end)</td>
</tr>
<tr class="odd">
<td><code>LSLOPE_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Slope of the green-up period</td>
</tr>
<tr class="even">
<td><code>RSLOPE_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Slope of the green-down period<br>
(absolute value of decreasing rate)</td>
</tr>
<tr class="odd">
<td><code>TPROD_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Total productivity. Growing season<br>
integral computed as the sum of all<br>
daily values between SOSD and EOSD.</td>
</tr>
<tr class="even">
<td><code>SPROD_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>Seasonal productivity. Growing season<br>
integral computed as sum of all daily<br>
values minus their base level value.</td>
</tr>
<tr class="odd">
<td style="text-align: center; background-color: #a9d18e;"><strong>Aux</strong></td>
<td><code>QA_YYYY_&lt;s1 or s2&gt;_cog.tif</code></td>
<td>VPP Quality flag</td>
</tr>
<tr class="even">
<td rowspan="2" style="text-align: center; background-color: #92d050; vertical-align: middle;"><strong>MR-VPP<br>
PPI<br>
Time<br>
series</strong></td>
<td><code>PPI.YYYY.MM.DD_laea_cog.tif</code></td>
<td>PPI calculation</td>
</tr>
<tr class="odd">
<td><code>QA.YYYY.MM.DD_laea_cog.tif</code></td>
<td>PPI data quality</td>
</tr>
</tbody>
</table>
<p>Note: YYYY for year, e.g.&nbsp;2000, 2001, …, 2024, 2025.</p>
</section>
</section>
<section id="references" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> References</h1>
<ul>
<li>Abbe, C. (1905). <em>A first report on the relations between climates and crops</em>. Government Printing Office.</li>
<li>Atzberger, C., &amp; Eilers, P. H. C. (2011). A time series for monitoring vegetation activity and phenology at 10-daily time steps covering large parts of South America. <em>International Journal of Digital Earth, 4</em>(5), 365-386. https://doi.org/10.1080/17538947.2010.505664</li>
<li>Bolton, D. K., Gray, J. M., Melaas, E. K., Moon, M., Eklundh, L., &amp; Friedl, M. A. (2020). Continental-scale land surface phenology from harmonized Landsat 8 and Sentinel-2 imagery. <em>Remote Sensing of Environment, 240</em>, 111685. https://doi.org/10.1016/j.rse.2020.111685</li>
<li>Cai, Z., Jönsson, P., Jin, H., &amp; Eklundh, L. (2017). Performance of Smoothing Methods for Reconstructing NDVI Time-Series and Estimating Vegetation Phenology from MODIS Data. <em>Remote Sensing, 9</em>(12), 1271. https://doi.org/10.3390/rs9121271</li>
<li>Chen, J., Jönsson, P., Tamura, M., Gu, Z. H., Matsushita, B., &amp; Eklundh, L. (2004). A simple method for reconstructing a high-quality NDVI time-series data set based on the Savitzky-Golay filter. <em>Remote Sensing of Environment, 91</em>(3-4), 332-344. https://doi.org/10.1016/j.rse.2004.03.014</li>
<li>Chmura, H. E., Kharouba, H. M., Ashander, J., Ehlman, S. M., Rivest, E. B., &amp; Yang, L. H. (2019). The mechanisms of phenology: the patterns and processes of phenological shifts. <em>Ecological Monographs, 89</em>(1), e01337. https://doi.org/10.1002/ecm.1337</li>
<li>Craven, P., &amp; Wahba, G. (1978). Smoothing noisy data with spline functions. <em>Numerische Mathematik, 31</em>(4), 377-403. https://doi.org/10.1007/BF01404567</li>
<li>Eilers, P. H. C. (2003). A Perfect Smoother. <em>Analytical Chemistry, 75</em>(14), 3631-3636. https://doi.org/10.1021/ac034173t</li>
<li>Fisher, J. I., Mustard, J. F., &amp; Vadeboncoeur, M. A. (2006). Green leaf phenology at Landsat resolution: Scaling from the field to the satellite. <em>Remote Sensing of Environment, 100</em>(2), 265-279. https://doi.org/10.1016/j.rse.2005.10.022</li>
<li>Gray, J., Sulla-Menashe, D., &amp; Friedl, M. A. (2019). <em>User guide to collection 6 modis land cover dynamics (MCD12Q2) product</em>.</li>
<li>Hapke, B. (1993). <em>Theory of reflectance and emittance spectroscopy</em>. Cambridge University Press.</li>
<li>Jin, H., &amp; Eklundh, L. (2014). A physically based vegetation index for improved monitoring of plant phenology. <em>Remote Sensing of Environment, 152</em>(0), 512-525. https://doi.org/10.1016/j.rse.2014.07.010</li>
<li>Jin, H., Vicente-Serrano, S. M., Tian, F., Cai, Z., Conradt, T., Boincean, B., Murphy, C., Farizo, B. A., Grainger, S., López-Moreno, J. I., &amp; Eklundh, L. (2023). Higher vegetation sensitivity to meteorological drought in autumn than spring across European biomes. <em>Communications Earth &amp; Environment, 4</em>(1), 299. https://doi.org/10.1038/s43247-023-00960-w</li>
<li>Jönsson, P., Cai, Z., Melaas, E., Friedl, M., &amp; Eklundh, L. (2018). A Method for Robust Estimation of Vegetation Seasonality from Landsat and Sentinel-2 Time Series Data. <em>Remote Sensing, 10</em>(4), 635. http://www.mdpi.com/2072-4292/10/4/635</li>
<li>Jönsson, P., &amp; Eklundh, L. (2002). Seasonality extraction by function fitting to time-series of satellite sensor data. <em>IEEE Transactions on Geoscience and Remote Sensing, 40</em>(8), 1824-1832. https://doi.org/10.1109/Tgrs.2002.802519</li>
<li>Jönsson, P., &amp; Eklundh, L. (2004). TIMESAT – a program for analyzing time-series of satellite sensor data. <em>Computers &amp; Geosciences, 30</em>(8), 833-845.</li>
<li>Lieth, H. (1974). <em>Phenology and Seasonality Modeling (Ecological Studies-Analysis and Synthesis Series, Vol 8)</em>. Springer-Verlag</li>
<li>Menenti, M., Azzali, S., Verhoef, W., &amp; van Swol, R. (1993). Mapping agroecological zones and time lag in vegetation growth by means of Fourier analysis of time series of NDVI images. <em>Advances in Space Research, 13</em>, 233-237.</li>
<li>Olsson, L., &amp; Eklundh, L. (1994). Fourier-Series for Analysis of Temporal Sequences of Satellite Sensor Imagery. <em>International Journal of Remote Sensing, 15</em>(18), 3735-3741.</li>
<li>Roerink, G. J., Menenti, M., &amp; Verhoef, W. (2000). Reconstructing cloudfree NDVI composites using Fourier analysis of time series. <em>International Journal of Remote Sensing, 21</em>(9), 1911-1917. http://www.informaworld.com/10.1080/014311600209814</li>
<li>Schwartz, M. D. (2013). <em>Phenology: An Integrative Environmental Science (2nd ed.)</em>. Springer Science+Business Media B.V.</li>
<li>Singh, R. K., Svystun, T., AlDahmash, B., Jönsson, A. M., &amp; Bhalerao, R. P. (2017). Photoperiod- and temperature-mediated control of phenology in trees – a molecular perspective. <em>New Phytologist, 213</em>(2), 511-524. https://doi.org/10.1111/nph.14346</li>
<li>Strahler, A. H., Lucht, W., Schaaf, C. B., Tsang, T., Gao, F., Li, X., Muller, J.-P., Lewis, P., &amp; Barnsley, M. J. (1999). <em>MODIS BRDF/Albedo Product: Algorithm Theoretical Basis Document, Version5.0</em>. Retrieved from https://lpdaac.usgs.gov/products/modis_products_table/mcd43a4</li>
<li>Tian, F., Cai, Z., Jin, H., Hufkens, K., Scheifinger, H., Tagesson, T., Smets, B., Van Hoolst, R., Bonte, K., Ivits, E., Tong, X., Ardö, J., &amp; Eklundh, L. (2021). Calibrating vegetation phenology from Sentinel-2 using eddy covariance, PhenoCam, and PEP725 networks across Europe. <em>Remote Sensing of Environment, 260</em>, 112456. https://doi.org/10.1016/j.rse.2021.112456</li>
<li>Tucker, C. J. (1977). Asymptotic nature of grass canopy spectral reflectance. <em>Applied Optics, 16</em>(5), 1151-1156. https://doi.org/10.1364/AO.16.001151</li>
<li>White, M. A., De Beurs, K. M., Didan, K., Inouye, D. W., Richardson, A. D., Jensen, O. P., O’Keefe, J., Zhang, G., Nemani, R. R., Van Leeuwen, W. J. D., Brown, J. F., De Wit, A., Schaepman, M., Lin, X., Dettinger, M., Bailey, A. S., Kimball, J., Schwartz, M. D., Baldocchi, D. D., . . . Lauenroth, W. K. (2009). Intercomparison, interpretation, and assessment of spring phenology in North America estimated from remote sensing for 1982-2006. <em>Global Change Biology, 15</em>(10), 2335-2359. https://doi.org/10.1111/j.1365-2486.2009.01910.x</li>
<li>Zhang, X., Friedl, M. A., Schaaf, C. B., Strahler, A. H., Hodges, J. C. F., Gao, F., Reed, B. C., &amp; Huete, A. (2003). Monitoring vegetation phenology using MODIS. <em>Remote Sensing of Environment, 84</em>(3), 471-475. http://www.sciencedirect.com/science/article/B6V6V-478RS7T-1/2/19c385401eecea8964bca155ac01eb71</li>
</ul>
</section>
<section id="appendix" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Appendix</h1>
<section id="comparison-of-tprod-using-version-5.0-and-4.0" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="comparison-of-tprod-using-version-5.0-and-4.0"><span class="header-section-number">6.1</span> Comparison of TPROD using Version 5.0 and 4.0</h2>
<p>Figure 9 shows maps of the total productivity (TPROD) of season 1 in 2018. The spatial patterns of TPROD closely correlate between the two versions. The highest TPROD values are found in the European southern Alpine forests, followed by progressively lower values in temperate forests and croplands of continental Europe, then in the boreal forests of Northern Europe, and lowest in the northern alpine and sub-Arctic regions. Artificially high TPROD values in barren desert areas of northern Africa, present in V4.0, are effectively removed in V5.0.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-9b6bf208da4a290a31d1d20e7cd36dd9.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9. Pan-European TPROD (Season 1, 2018) from MR-VPP Versions 4.0 and 5.0, showing correction of artifacts in desert/barren areas, in particular in N. Africa: (a) MR-VPP version 4.0, (b) MR-VPP version 5.0.</figcaption>
</figure>
</div>
</section>
<section id="comparison-of-mr-vpp-naming-scheme-in-version-5.0-and-4.0" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="comparison-of-mr-vpp-naming-scheme-in-version-5.0-and-4.0"><span class="header-section-number">6.2</span> Comparison of MR-VPP naming scheme in Version 5.0 and 4.0</h2>
<p>MR-VPP 5.0 adopts the VPP naming scheme aligned with other CLMS LSP products, including HR-VPP and CGLOPS1 LSP based on Sentinel-3 and PROBA-V data. This scheme is simpler and clearer. Table 7 provides a <strong>naming correspondence table</strong>, comparing the file-naming conventions of MR-VPP Version 5.0 and Version 4.0.</p>
<div class="tbl-caption">
<p>Table 7. Naming correspondence between MR-VPP Version 5.0 (13 parameters) and Version 4.0.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 59%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" style="background-color: #c5e0b4; font-weight: bold; vertical-align: middle">No.</td>
<td style="background-color: #c5e0b4; font-weight: bold">Name</td>
<td style="background-color: #c5e0b4; font-weight: bold">Old Name (in filename)</td>
</tr>
<tr class="even">
<td style="text-align: center; background-color: #c5e0b4; font-weight: bold;">Ver 5.0</td>
<td style="text-align: center; background-color: #c5e0b4; font-weight: bold;">Ver 4.0</td>
</tr>
<tr class="odd">
<td>1</td>
<td>SOSD</td>
<td>dsos</td>
</tr>
<tr class="even">
<td>2</td>
<td>EOSD</td>
<td>deos</td>
</tr>
<tr class="odd">
<td>3</td>
<td>MAXD</td>
<td>pos</td>
</tr>
<tr class="even">
<td>4</td>
<td>SOSV</td>
<td>sos_value</td>
</tr>
<tr class="odd">
<td>5</td>
<td>EOSV</td>
<td>eos_value</td>
</tr>
<tr class="even">
<td>6</td>
<td>MINV</td>
<td>base_level</td>
</tr>
<tr class="odd">
<td>7</td>
<td>MAXV</td>
<td>largest_value</td>
</tr>
<tr class="even">
<td>8</td>
<td>AMPL</td>
<td>seasonal_amplitude</td>
</tr>
<tr class="odd">
<td>9</td>
<td>LENGTH</td>
<td>los</td>
</tr>
<tr class="even">
<td>10</td>
<td>LSLOPE</td>
<td>increase_rate</td>
</tr>
<tr class="odd">
<td>11</td>
<td>RSLOPE</td>
<td>decrease_rate</td>
</tr>
<tr class="even">
<td>12</td>
<td>TPROD</td>
<td>LINT</td>
</tr>
<tr class="odd">
<td>13</td>
<td>SPROD</td>
<td>SINT</td>
</tr>
<tr class="even">
<td>Aux</td>
<td>QA</td>
<td>-</td>
</tr>
</tbody>
</table>
</section>
<section id="detailed-comparison-of-2025-mr-vpp-v5.0-issue-2.0-results-from-short-and-long-input-time-series" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="detailed-comparison-of-2025-mr-vpp-v5.0-issue-2.0-results-from-short-and-long-input-time-series"><span class="header-section-number">6.3</span> Detailed Comparison of 2025 MR-VPP V5.0 Issue 2.0 Results from Short and Long Input Time Series</h2>
<p>The comparison was based on paired-pixel analysis between spatially aligned VPP raster products generated from the short time series and full-archive input time series. The short time series processing used MODIS PPI data from 1 January 2024 to 19 April 2026, while the full-archive processing used the complete MODIS PPI record from 24 February 2000 to 19 April 2026. Valid pairs were identified after excluding no-data values. For QA analysis, only vegetated land-cover classes were considered, using MODIS IGBP classes 1–14 and excluding water, snow and ice, barren or sparsely vegetated areas, and unknown classes. Statistics were calculated for each VPP metric and season, including R², bias, RMSE, MAE, the proportion of pixels close to the 1:1 line, and the number of valid paired pixels.</p>
<p>Spatial comparison maps (Figure 10) demonstrate strong agreement between the long and short time series processing approaches across Europe for representative timing, magnitude, and productivity metrics. The large-scale spatial distributions of SOSD, EOSD, AMPL, and TPROD are visually highly consistent between the two implementations, with only minor localized differences observed in some heterogeneous landscapes and weak-signal regions. The density scatter plots for season 1 (Figure 11) further confirm this high consistency, with the vast majority of pixels tightly concentrated along the 1:1 relationship for all representative metrics. Robust regression slopes were close to unity and the regression lines were nearly indistinguishable from the 1:1 line, particularly for AMPL and TPROD. Comparisons for season 2 (Figure 12) exhibited slightly larger dispersion, especially for EOSD and other timing-related metrics, reflecting the intrinsically weaker, spatially fragmented, and more irregular nature of secondary seasonal cycles in Europe. Nevertheless, the dominant spatial and ecological patterns remained highly consistent between the two processing approaches.</p>
<p>Comparison of the 13 VPP metrics derived from long time series inputs and short time series inputs for the 2025 growing seasons demonstrates overall strong consistency between the two processing approaches (Table 8). For the primary growing season (season 1), all metrics showed very high agreement, with coefficients of determination (R²) ranging from 0.97 to 1.00, very small systematic biases, and low RMSE and MAE values relative to the dynamic range of each metric. Temporal metrics such as SOSD, MAXD, and EOSD differed by only a few days on average (RMSE: 3.35–7.90 days), while vegetation magnitude and productivity metrics exhibited near-identical results (R² ≈ 1.00). More than 98% of valid pixels for all season 1 metrics were located within the predefined consistency threshold around the 1:1 line, indicating that the short time series processing reproduces the long time series results with very high fidelity over the main European growing season.</p>
<p>The secondary growing season (season 2) exhibited slightly lower agreement and substantially fewer valid observations (approximately 6.6 × 10⁴ valid paired pixels compared to 4.4 × 10⁷ in season 1), reflecting the more limited spatial extent and weaker seasonal signal associated with secondary vegetation cycles in Europe. Nevertheless, most season 2 metrics still maintained high consistency (R² generally 0.97–1.00 for vegetation magnitude, slope, and productivity metrics), although timing-related metrics such as EOSD and LENGTH showed somewhat larger deviations (R² = 0.82–0.92; RMSE ≈ 32 days). These larger discrepancies are likely associated with increased uncertainty in detecting weak, irregular, or temporally fragmented secondary seasonal cycles. Overall, the analysis indicates that the short time series processing approach produces highly comparable VPP results to the long time series approach for the majority of metrics and environmental conditions, while some reduction in robustness may occur for weak secondary-season phenological signals.</p>
<p>A small systematic negative bias was observed for several timing-related metrics (SOSD, EOSD, and MAXD), indicating that the near-real-time short time series processing tended to retrieve slightly earlier seasonal dates than the long time series processing. This behavior is likely associated with reduced temporal context and stronger edge effects in the shorter input records used for NRT production. However, the magnitude of the bias was very small (&lt;0.2 days on average) and operationally negligible at continental scale. Since the 2025 VPP products are generated using a temporally limited update window similar to annual NRT LSP production, the products are expected to be updated during subsequent annual reprocessing cycles when additional observations from complete calendar years before and after the target year become available. The inclusion of extended temporal context is expected to further stabilize seasonal curve fitting and reduce edge-related uncertainties.</p>
<p>Quality assessment (QA) comparison between the long and short time series processing approaches indicates highly similar overall QA characteristics for the 2025 VPP products (Table 9). For season 1, approximately 96.5% of valid vegetated pixels were classified as good quality (QA &lt; 127) in both processing approaches, while poor-quality and failed retrievals represented only a small fraction of pixels. The proportion of pixels showing QA improvement in the long time series processing relative to the short time series processing was very small (approximately 0.29%), indicating that the short-input processing reproduced the QA characteristics of the long-input processing with high consistency. Season 2 exhibited somewhat lower overall QA performance, reflecting the intrinsically weaker and spatially limited nature of secondary seasonal signals in Europe; nevertheless, good-quality retrievals still dominated (~91–93% of valid pixels).</p>
<p>Although the long time series processing occasionally generated slightly more valid VPP outputs than the short time series processing, this should not necessarily be interpreted as superior retrieval performance. In situations where observations are sparse within the target temporal window, the absence of phenology retrievals in the short time series processing may correctly reflect insufficient observational support for robust phenology estimation. Under such conditions, increasing retrieval completeness through extended temporal context may risk generating phenological metrics with reduced reliability or interpretability. Therefore, VPP output completeness alone should not be considered the primary criterion for evaluating processing performance; the consistency, robustness, and physical interpretability of the retrieved seasonal signals are more important considerations.</p>
<div class="quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-4e7996f2eab8c321fb188c0c010123ef.png" class="img-fluid"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: center;">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-2c5e4c7e031a5a7b445d1d6e2fae3030.png" class="img-fluid"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-7cf817c6c6a0fb7dfba709884fbdfc62.png" class="img-fluid figure-img"></p>
<figcaption>Figure 10. Comparison of representative vegetation phenology and productivity (VPP) metrics derived using long time series inputs and short time series inputs for the 2025 growing season over Europe. Panels show spatial distributions of (a, b) start of season date (SOSD), (c, d) end of season date (EOSD), (e, f) seasonal amplitude (AMPL), and (g, h) total productivity (TPROD) generated from the long time series (2000-2026) and short time series (2024-2026) processing approaches.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-00fc8e231c1e7e3ed79e717cc61b37f8.png" class="img-fluid figure-img"></p>
<figcaption>Figure 11. Density scatter plot comparison between vegetation phenology and productivity (VPP) metrics derived from long time series inputs and short time series inputs for the 2025 growing season 1 over Europe: (a) start of season date (SOSD), (b) end of season date (EOSD), (c) seasonal amplitude (AMPL), and (d) total productivity (TPROD). Hexagon color indicates relative point density normalized to the maximum density. Dashed black lines represent the 1:1 relationship, and red lines indicate robust linear regression fitted after exclusion of extreme outliers using percentile-based filtering. Reported statistics include coefficient of determination (R²), bias, RMSE, MAE, and the proportion of pixels located within a predefined consistency threshold around the 1:1 line.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MRVPP_MRVPP_ATBD_v2-media/img-b08a8132b99b9a13639476be6698a2ca.png" class="img-fluid figure-img"></p>
<figcaption>Figure 12. Density scatter plot comparison between vegetation phenology and productivity (VPP) metrics derived from long time series inputs and short time series inputs for the 2025 growing season 2 over Europe: (a) start of season date (SOSD), (b) end of season date (EOSD), (c) seasonal amplitude (AMPL), and (d) total productivity (TPROD). Hexagon color indicates relative point density normalized to the maximum density. Dashed black lines represent the 1:1 relationship, and red lines indicate robust linear regression fitted after exclusion of extreme outliers using percentile-based filtering. Reported statistics include coefficient of determination (R²), bias (VPP_short - VPP_long), RMSE, MAE, and the proportion of pixels located within a predefined consistency threshold around the 1:1 line.</figcaption>
</figure>
</div>
<div class="tbl-caption">
<p>Table 8. Statistical comparison of 13 vegetation phenology and productivity (VPP) metrics derived from long time series inputs and short time series inputs for the 2025 growing seasons over Europe.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 11%">
</colgroup>
<tbody>
<tr class="odd" style="background-color:#ddebf7">
<td><strong>VPP Metric</strong></td>
<td><strong>Season</strong></td>
<td><strong>R<sup>2</sup></strong></td>
<td><strong>Bias</strong></td>
<td><strong>RMSE</strong></td>
<td><strong>MAE</strong></td>
<td><strong>% points on 1:1 line</strong></td>
<td><strong>1:1 line threshold</strong></td>
<td><strong>Valid pairs N</strong></td>
</tr>
<tr class="even">
<td>SOSD (days)</td>
<td>1</td>
<td>0.99</td>
<td>-0.01</td>
<td>3.35</td>
<td>0.16</td>
<td>99.54</td>
<td>3.25</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>EOSD (days)</td>
<td>1</td>
<td>0.98</td>
<td>-0.17</td>
<td>7.90</td>
<td>0.52</td>
<td>99.14</td>
<td>4.41</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="even">
<td>MAXD (days)</td>
<td>1</td>
<td>0.99</td>
<td>-0.03</td>
<td>3.56</td>
<td>0.15</td>
<td>99.66</td>
<td>2.64</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>SOSV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>1</td>
<td>1.00</td>
<td>0.17</td>
<td>6.17</td>
<td>0.47</td>
<td>99.21</td>
<td>14.10</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="even">
<td>EOSV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>1</td>
<td>1.00</td>
<td>0.19</td>
<td>5.66</td>
<td>0.50</td>
<td>98.85</td>
<td>9.02</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>MINV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>1</td>
<td>0.99</td>
<td>0.20</td>
<td>4.55</td>
<td>0.40</td>
<td>98.28</td>
<td>3.82</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="even">
<td>MAXV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>1</td>
<td>1.00</td>
<td>0.14</td>
<td>18.48</td>
<td>0.76</td>
<td>99.74</td>
<td>55.74</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>AMPL (×10<sup>-3</sup> m²·m⁻²)</td>
<td>1</td>
<td>1.00</td>
<td>-0.04</td>
<td>19.37</td>
<td>1.19</td>
<td>99.60</td>
<td>55.62</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="even">
<td>LENGTH (days)</td>
<td>1</td>
<td>0.97</td>
<td>-0.07</td>
<td>9.40</td>
<td>0.75</td>
<td>98.74</td>
<td>4.17</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>LSLOPE<br>
(×10<sup>-3</sup> m²·m⁻²·day⁻¹)</td>
<td>1</td>
<td>1.00</td>
<td>0.00</td>
<td>1.21</td>
<td>0.05</td>
<td>99.57</td>
<td>1.47</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="even">
<td>RSLOPE<br>
(×10<sup>-3</sup> m²·m⁻²·day⁻¹)</td>
<td>1</td>
<td>0.99</td>
<td>0.01</td>
<td>1.30</td>
<td>0.06</td>
<td>99.51</td>
<td>1.48</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>TPROD<br>
(m²·m⁻²·day)</td>
<td>1</td>
<td>1.00</td>
<td>-0.01</td>
<td>3.29</td>
<td>0.21</td>
<td>99.45</td>
<td>4.26</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="even">
<td>SPROD<br>
(m²·m⁻²·day)</td>
<td>1</td>
<td>1.00</td>
<td>-0.02</td>
<td>3.11</td>
<td>0.24</td>
<td>99.10</td>
<td>4.07</td>
<td>4.4×10<sup>7</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>SOSD (days)</td>
<td>2</td>
<td>0.99</td>
<td>0.02</td>
<td>6.08</td>
<td>0.53</td>
<td>96.91</td>
<td>2.80</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="even">
<td>EOSD (days)</td>
<td>2</td>
<td>0.92</td>
<td>5.08</td>
<td>31.76</td>
<td>7.29</td>
<td>93.30</td>
<td>5.61</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>MAXD (days)</td>
<td>2</td>
<td>0.99</td>
<td>-0.45</td>
<td>7.25</td>
<td>1.75</td>
<td>87.90</td>
<td>2.46</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="even">
<td>SOSV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>2</td>
<td>1.00</td>
<td>1.80</td>
<td>12.93</td>
<td>2.33</td>
<td>96.43</td>
<td>15.67</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>EOSV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>2</td>
<td>0.99</td>
<td>-1.00</td>
<td>18.27</td>
<td>3.80</td>
<td>93.18</td>
<td>10.37</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="even">
<td>MINV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>2</td>
<td>0.98</td>
<td>-1.29</td>
<td>10.19</td>
<td>1.62</td>
<td>95.79</td>
<td>6.25</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>MAXV (×10<sup>-3</sup> m²·m⁻²)</td>
<td>2</td>
<td>1.00</td>
<td>7.66</td>
<td>50.09</td>
<td>8.70</td>
<td>96.72</td>
<td>62.07</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="even">
<td>AMPL (×10<sup>-3</sup> m²·m⁻²)</td>
<td>2</td>
<td>1.00</td>
<td>9.01</td>
<td>51.49</td>
<td>10.30</td>
<td>95.78</td>
<td>61.75</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>LENGTH (days)</td>
<td>2</td>
<td>0.82</td>
<td>5.04</td>
<td>31.89</td>
<td>7.55</td>
<td>91.19</td>
<td>4.16</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="even">
<td>LSLOPE<br>
(×10<sup>-3</sup> m²·m⁻²·day⁻¹)</td>
<td>2</td>
<td>1.00</td>
<td>0.09</td>
<td>1.40</td>
<td>0.17</td>
<td>97.61</td>
<td>1.90</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>RSLOPE<br>
(×10<sup>-3</sup> m²·m⁻²·day⁻¹)</td>
<td>2</td>
<td>0.97</td>
<td>-0.13</td>
<td>3.39</td>
<td>0.59</td>
<td>94.72</td>
<td>1.53</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="even">
<td>TPROD<br>
(m²·m⁻²·day)</td>
<td>2</td>
<td>0.97</td>
<td>1.46</td>
<td>10.65</td>
<td>1.95</td>
<td>95.50</td>
<td>4.02</td>
<td>6.6×10<sup>4</sup></td>
</tr>
<tr class="odd" style="background-color:#f2f2f2">
<td>SPROD<br>
(m²·m⁻²·day)</td>
<td>2</td>
<td>0.97</td>
<td>1.45</td>
<td>9.44</td>
<td>1.79</td>
<td>94.72</td>
<td>3.30</td>
<td>6.6×10<sup>4</sup></td>
</tr>
</tbody>
</table>
<p>Note: Reported statistics include coefficient of determination (R²), bias (VPP_short - VPP_long), root mean square error (RMSE), mean absolute error (MAE), percentage of pixels located within a predefined consistency threshold (hexagon size in Figure 11 scatter plots) around the 1:1 line, the corresponding threshold value, and the number of valid paired pixels. Statistics were computed using robust paired-pixel analysis after exclusion of extreme outliers using percentile-based filtering. Season 2 results are based on substantially fewer valid pixels due to the limited spatial extent and weaker signal of secondary growing seasons in Europe.</p>
<div class="tbl-caption">
<p>Table 9. Summary of quality assessment (QA) comparison between vegetation phenology and productivity (VPP) products generated using long time series (TS) and short time series inputs for the 2025 growing seasons over Europe. Statistics are calculated for vegetated land-cover classes only (IGBP classes 1–14).</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Season</th>
<th>Valid vegetated paired pixels (LC 1–14)</th>
<th>Good QA (%) long time series</th>
<th>Good QA (%) short time series</th>
<th>QA improvement (%)</th>
<th>QA degradation (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Season 1</td>
<td>4.4×10⁷</td>
<td>96.47</td>
<td>96.32</td>
<td>0.29</td>
<td>0.14</td>
</tr>
<tr class="even">
<td>Season 2</td>
<td>6.6×10⁴</td>
<td>91.34</td>
<td>90.96</td>
<td>0.03</td>
<td>0.10</td>
</tr>
</tbody>
</table>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div>EUPL (&gt;= 1.2)</div></div></section></div></main> <!-- /main -->
<!-- Mobile-only "Contents" button that reveals the section TOC, which the
     full-width HTML layout hides on small screens. Styling is in
     theme/styles.css (.toc-mobile-btn / body.toc-mobile-open). -->
<script>
(function () {
  var toc = document.getElementById('TOC');
  if (!toc) return; // no section TOC on this page (e.g. listings) -> no button

  var btn = document.createElement('button');
  btn.type = 'button';
  btn.className = 'toc-mobile-btn';
  btn.setAttribute('aria-label', 'Toggle table of contents');
  btn.innerHTML = '☰ Contents';
  btn.addEventListener('click', function () {
    document.body.classList.toggle('toc-mobile-open');
  });
  document.body.appendChild(btn);

  // Tapping a TOC link closes the panel.
  toc.addEventListener('click', function (e) {
    if (e.target.closest('a')) document.body.classList.remove('toc-mobile-open');
  });
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/library\.land\.copernicus\.eu");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>2026 EEA. All rights reserved.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>