<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2020-04-17">
<meta name="keywords" content="Snow Cover Extent (SCE), Fractional Snow Cover (FSC), Northern Hemisphere, Sentinel-3 SLSTR data, S-NPP VIIRS data, Normalised Difference Snow Index (NDSI), SCAmod algorithm, Transmissivity map, Product User Manual (PUM), Thematic accuracy assessment, Daily snow products, Cryosphere monitoring">
<meta name="description" content="This Product User Manual provides essential information for utilising the Northern Hemisphere Snow Cover Extent (SCE) product, a core component of the Copernicus Global Land Service. It details the daily fractional snow cover (FSC) mapping across the Northern Hemisphere at 0.01-degree resolution, derived from S-NPP VIIRS and Sentinel-3 SLSTR optical satellite data. The document outlines the retrieval methodology, which integrates the Normalised Difference Snow Index and the SCAmod algorithm, alongside product characteristics, coding conventions, and validation results, supporting diverse applications in cryosphere monitoring and climate science.">

<title>PRODUCT USER MANUAL Snow Cover Extent Collection 1 km Northern Hemisphere – Technical Library</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3e4b792c78aaba79123027d3b782d07b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "Search ...",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "ScholarlyArticle",
    "headline": "PRODUCT USER MANUAL Snow Cover Extent Collection 1 km Northern Hemisphere",
    "description": "This Product User Manual provides essential information for utilising the Northern Hemisphere Snow Cover Extent (SCE) product, a core component of the Copernicus Global Land Service. It details the daily fractional snow cover (FSC) mapping across the Northern Hemisphere at 0.01-degree resolution, derived from S-NPP VIIRS and Sentinel-3 SLSTR optical satellite data. The document outlines the retrieval methodology, which integrates the Normalised Difference Snow Index and the SCAmod algorithm, alongside product characteristics, coding conventions, and validation results, supporting diverse applications in cryosphere monitoring and climate science.",
    "datePublished": "April 17, 2020",
    "author": {
      "@type": "Person",
      "name": "?meta:author"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Copernicus Land Monitoring Service",
      "logo": {
        "@type": "ImageObject",
        "url": "https://land.copernicus.eu/static/media/ccl-icon-land-text-2.e04af716.svg"
      }
    },
    "keywords": "Snow Cover Extent (SCE)

Fractional Snow Cover (FSC)

Northern Hemisphere

Sentinel-3 SLSTR data

S-NPP VIIRS data

Normalised Difference Snow Index (NDSI)

SCAmod algorithm

Transmissivity map

Product User Manual (PUM)

Thematic accuracy assessment

Daily snow products

Cryosphere monitoring
",
    "articleSection": "General",
    "isAccessibleForFree": "true",
    "license": "",
    "speakable": {
      "@type": "SpeakableSpecification",
      "cssSelector": "article p"
    }
  }
</script>


<link rel="stylesheet" href="../_meta/theme/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Technical Library</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Index</h2>
   
  <ul>
  <li><a href="#document-release-sheet" id="toc-document-release-sheet" class="nav-link active" data-scroll-target="#document-release-sheet"><span class="header-section-number">0.1</span> Document Release Sheet</a></li>
  <li><a href="#change-record" id="toc-change-record" class="nav-link" data-scroll-target="#change-record"><span class="header-section-number">0.2</span> Change Record</a></li>
  <li><a href="#list-of-acronyms" id="toc-list-of-acronyms" class="nav-link" data-scroll-target="#list-of-acronyms"><span class="header-section-number">0.3</span> List of Acronyms</a></li>
  <li><a href="#background-of-the-document" id="toc-background-of-the-document" class="nav-link" data-scroll-target="#background-of-the-document"><span class="header-section-number">1</span> Background of the document</a>
  <ul class="collapse">
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link" data-scroll-target="#executive-summary"><span class="header-section-number">1.1</span> Executive Summary</a></li>
  <li><a href="#scope-and-objectives" id="toc-scope-and-objectives" class="nav-link" data-scroll-target="#scope-and-objectives"><span class="header-section-number">1.2</span> Scope and Objectives</a></li>
  <li><a href="#content-of-the-document" id="toc-content-of-the-document" class="nav-link" data-scroll-target="#content-of-the-document"><span class="header-section-number">1.3</span> Content of the document</a></li>
  <li><a href="#related-documents" id="toc-related-documents" class="nav-link" data-scroll-target="#related-documents"><span class="header-section-number">1.4</span> Related documents</a>
  <ul class="collapse">
  <li><a href="#applicable-documents" id="toc-applicable-documents" class="nav-link" data-scroll-target="#applicable-documents"><span class="header-section-number">1.4.1</span> Applicable documents</a></li>
  <li><a href="#input" id="toc-input" class="nav-link" data-scroll-target="#input"><span class="header-section-number">1.4.2</span> Input</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output"><span class="header-section-number">1.4.3</span> Output</a></li>
  <li><a href="#external-documents" id="toc-external-documents" class="nav-link" data-scroll-target="#external-documents"><span class="header-section-number">1.4.4</span> External documents</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#review-of-users-requirements" id="toc-review-of-users-requirements" class="nav-link" data-scroll-target="#review-of-users-requirements"><span class="header-section-number">2</span> Review of Users Requirements</a></li>
  <li><a href="#algorithm" id="toc-algorithm" class="nav-link" data-scroll-target="#algorithm"><span class="header-section-number">3</span> Algorithm</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview"><span class="header-section-number">3.1</span> Overview</a></li>
  <li><a href="#the-retrieval-methodology" id="toc-the-retrieval-methodology" class="nav-link" data-scroll-target="#the-retrieval-methodology"><span class="header-section-number">3.2</span> The retrieval Methodology</a></li>
  <li><a href="#limitations-of-the-product" id="toc-limitations-of-the-product" class="nav-link" data-scroll-target="#limitations-of-the-product"><span class="header-section-number">3.3</span> Limitations of the Product</a></li>
  <li><a href="#differences-with-the-previous-version" id="toc-differences-with-the-previous-version" class="nav-link" data-scroll-target="#differences-with-the-previous-version"><span class="header-section-number">3.4</span> Differences with the previous version</a></li>
  </ul></li>
  <li><a href="#product-description" id="toc-product-description" class="nav-link" data-scroll-target="#product-description"><span class="header-section-number">4</span> Product Description</a>
  <ul class="collapse">
  <li><a href="#file-naming" id="toc-file-naming" class="nav-link" data-scroll-target="#file-naming"><span class="header-section-number">4.1</span> File Naming</a></li>
  <li><a href="#file-format" id="toc-file-format" class="nav-link" data-scroll-target="#file-format"><span class="header-section-number">4.2</span> File Format</a></li>
  <li><a href="#product-content" id="toc-product-content" class="nav-link" data-scroll-target="#product-content"><span class="header-section-number">4.3</span> Product Content</a>
  <ul class="collapse">
  <li><a href="#data-file" id="toc-data-file" class="nav-link" data-scroll-target="#data-file"><span class="header-section-number">4.3.1</span> Data File</a></li>
  <li><a href="#quicklook" id="toc-quicklook" class="nav-link" data-scroll-target="#quicklook"><span class="header-section-number">4.3.2</span> Quicklook</a></li>
  </ul></li>
  <li><a href="#product-characteristics" id="toc-product-characteristics" class="nav-link" data-scroll-target="#product-characteristics"><span class="header-section-number">4.4</span> Product Characteristics</a>
  <ul class="collapse">
  <li><a href="#projection-and-grid-information" id="toc-projection-and-grid-information" class="nav-link" data-scroll-target="#projection-and-grid-information"><span class="header-section-number">4.4.1</span> Projection and Grid Information</a></li>
  <li><a href="#spatial-information" id="toc-spatial-information" class="nav-link" data-scroll-target="#spatial-information"><span class="header-section-number">4.4.2</span> Spatial Information</a></li>
  <li><a href="#temporal-information" id="toc-temporal-information" class="nav-link" data-scroll-target="#temporal-information"><span class="header-section-number">4.4.3</span> Temporal Information</a></li>
  <li><a href="#data-policies" id="toc-data-policies" class="nav-link" data-scroll-target="#data-policies"><span class="header-section-number">4.4.4</span> Data Policies</a></li>
  <li><a href="#contacts" id="toc-contacts" class="nav-link" data-scroll-target="#contacts"><span class="header-section-number">4.4.5</span> Contacts</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation"><span class="header-section-number">5</span> Validation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="products_Product_user_manual_-_Snow_Cover_Extent_Northern_Hemisphere_version_1.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">
<script>
  document.addEventListener("DOMContentLoaded", function () {
    // Add Version to the title's metadata
    //
    const titleMetaEl = document.querySelector(".quarto-title-meta");
    const wrapperDiv = document.createElement("div");
    wrapperDiv.innerHTML = `
        <div class="quarto-title-meta-heading">Version</div>
        <div class="quarto-title-meta-contents">
          <p>Issue 11.05</p>
        </div>
      `;
    titleMetaEl.appendChild(wrapperDiv);
  });
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PRODUCT USER MANUAL Snow Cover Extent Collection 1 km Northern Hemisphere</h1>
<p class="subtitle lead">Copernicus Global Land Operations ‘Cryosphere and Water’ ‘CGLOPS-2’</p>
</div>

<div>
  <div class="description">
    This Product User Manual provides essential information for utilising the Northern Hemisphere Snow Cover Extent (SCE) product, a core component of the Copernicus Global Land Service. It details the daily fractional snow cover (FSC) mapping across the Northern Hemisphere at 0.01-degree resolution, derived from S-NPP VIIRS and Sentinel-3 SLSTR optical satellite data. The document outlines the retrieval methodology, which integrates the Normalised Difference Snow Index and the SCAmod algorithm, alongside product characteristics, coding conventions, and validation results, supporting diverse applications in cryosphere monitoring and climate science.
  </div>
</div>


<div class="quarto-title-meta column-page-left">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 17, 2020</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>Snow Cover Extent (SCE), Fractional Snow Cover (FSC), Northern Hemisphere, Sentinel-3 SLSTR data, S-NPP VIIRS data, Normalised Difference Snow Index (NDSI), SCAmod algorithm, Transmissivity map, Product User Manual (PUM), Thematic accuracy assessment, Daily snow products, Cryosphere monitoring</p>
  </div>
</div>

</header>


<p><br>
<strong>Contact:</strong></p>
<div data-custom-style="LeftAlign">
<p>European Environment Agency (EEA)<br>
Kongens Nytorv 6<br>
1050 Copenhagen K<br>
Denmark<br>
<a href="https://land.copernicus.eu/"><strong>https://land.copernicus.eu/</strong></a></p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 62%">
<col style="width: 15%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td colspan="4" style="font-weight: bold">Dissemination Level</td>
</tr>
<tr class="even">
<td>PU</td>
<td>Public</td>
<td>(X)</td>
<td></td>
</tr>
<tr class="odd">
<td>PP</td>
<td>Restricted to other programme participants (including the Commission Services)</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>RE</td>
<td>Restricted to a group specified by the consortium (including the Commission Services)</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>CO</td>
<td>Confidential, only for members of the consortium (including the Commission Services)</td>
<td></td>
<td>X</td>
</tr>
</tbody>
</table>
<section id="document-release-sheet" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="document-release-sheet"><span class="header-section-number">0.1</span> Document Release Sheet</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 46%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<tbody>
<tr class="odd">
<td>Book captain:</td>
<td>Gabriele Schwaizer</td>
<td>Sign</td>
<td>Date</td>
</tr>
<tr class="even">
<td>Approval:</td>
<td>Roselyne Lacaze</td>
<td>Sign</td>
<td>Date</td>
</tr>
<tr class="odd">
<td>Endorsement:</td>
<td>Mark Dowell</td>
<td>Sign</td>
<td>Date</td>
</tr>
<tr class="even">
<td>Distribution:</td>
<td>Current version: Confidential, only for<br>
members of the consortium<br>
<br>
Final version: Public</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="change-record" class="level2" data-number="0.2">
<h2 data-number="0.2" class="anchored" data-anchor-id="change-record"><span class="header-section-number">0.2</span> Change Record</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 22%">
<col style="width: 14%">
<col style="width: 36%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Issue/Rev</th>
<th>Date</th>
<th>Page(s)</th>
<th>Description of Change</th>
<th>Release</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>03.11.0217</td>
<td>All</td>
<td>First Issue</td>
<td>I1.01</td>
</tr>
<tr class="even">
<td></td>
<td>30.04.2018</td>
<td>All</td>
<td>Final version of the document</td>
<td>I1.01</td>
</tr>
<tr class="odd">
<td></td>
<td>11.09.2018</td>
<td>16</td>
<td>Update of metadata</td>
<td>I1.02</td>
</tr>
<tr class="even">
<td></td>
<td>06.11.2019</td>
<td>All</td>
<td>Update of document</td>
<td>I1.03</td>
</tr>
<tr class="odd">
<td></td>
<td>10.04.2020</td>
<td>All</td>
<td>Update of document after external review</td>
<td>I1.04</td>
</tr>
<tr class="even">
<td></td>
<td>17.04.2020</td>
<td>All</td>
<td>Including SLSTR relevant information</td>
<td>I1.05</td>
</tr>
</tbody>
</table>
</section>
<section id="list-of-acronyms" class="level2" data-number="0.3">
<h2 data-number="0.3" class="anchored" data-anchor-id="list-of-acronyms"><span class="header-section-number">0.3</span> List of Acronyms</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 74%">
</colgroup>
<tbody>
<tr class="odd">
<td style="background-color: #d9ead3; font-weight: bold">ABBREV.</td>
<td style="background-color: #d9ead3; font-weight: bold">MEANING</td>
</tr>
<tr class="even">
<td>ATBD</td>
<td>Algorithm Theoretical Basis Document</td>
</tr>
<tr class="odd">
<td>CCI</td>
<td>Climate Change Initiative</td>
</tr>
<tr class="even">
<td>ESA</td>
<td>European Space Agency</td>
</tr>
<tr class="odd">
<td>ETM+</td>
<td>Enhanced Thematic Mapper plus</td>
</tr>
<tr class="even">
<td>EU</td>
<td>European Union</td>
</tr>
<tr class="odd">
<td>FP7</td>
<td>7th Framework Program of the European Community for research, technological development and demonstration activities</td>
</tr>
<tr class="even">
<td>FSC</td>
<td>Fractional Snow Cover</td>
</tr>
<tr class="odd">
<td>IFOV</td>
<td>Instantaneous Field Of View</td>
</tr>
<tr class="even">
<td>MODIS</td>
<td>Moderate Resolution Imaging Spectroradiometer</td>
</tr>
<tr class="odd">
<td>MSI</td>
<td>Multi-Spectral Instrument</td>
</tr>
<tr class="even">
<td>NASA</td>
<td>National Aeronautics and Space Administration</td>
</tr>
<tr class="odd">
<td>NDSI</td>
<td>Normalized Difference Snow Index</td>
</tr>
<tr class="even">
<td>NDVI</td>
<td>Normalized Difference Vegetation Index</td>
</tr>
<tr class="odd">
<td>NH</td>
<td>Northern Hemisphere</td>
</tr>
<tr class="even">
<td>NIR</td>
<td>Near Infrared</td>
</tr>
<tr class="odd">
<td>NRT</td>
<td>Near-Real Time</td>
</tr>
<tr class="even">
<td>OLI</td>
<td>Operational Land Imager</td>
</tr>
<tr class="odd">
<td>QA4EO</td>
<td>Quality Assessment for Earth Observation</td>
</tr>
<tr class="even">
<td>PUM</td>
<td>Product User Manual</td>
</tr>
<tr class="odd">
<td>QAR</td>
<td>Quality Assessment Report</td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>Root Mean Square Error</td>
</tr>
<tr class="odd">
<td>S3</td>
<td>Sentinel-3</td>
</tr>
<tr class="even">
<td>SCE</td>
<td>Snow Cover Extent</td>
</tr>
<tr class="odd">
<td>SLSTR</td>
<td>Sea and Land Surface Temperature Radiometer</td>
</tr>
<tr class="even">
<td>SnowPEx</td>
<td>Satellite Snow Product Intercomparison and Validation Exercise</td>
</tr>
<tr class="odd">
<td>S-NPP</td>
<td>Suomi- National Polar-Orbiting Partnership</td>
</tr>
<tr class="even">
<td>SRTM</td>
<td>Shuttle Radar Topography Mission</td>
</tr>
<tr class="odd">
<td>SWIR</td>
<td>Shortwave Infrared</td>
</tr>
<tr class="even">
<td>TIR</td>
<td>Thermal Infrared</td>
</tr>
<tr class="odd">
<td>TIRS</td>
<td>Thermal Infrared Sensor</td>
</tr>
<tr class="even">
<td>TM</td>
<td>Thematic Mapper</td>
</tr>
<tr class="odd">
<td>VHR</td>
<td>Very High Resolution</td>
</tr>
<tr class="even">
<td>VIIRS</td>
<td>Visible Infrared Imaging Radiometer Suite</td>
</tr>
<tr class="odd">
<td>VIS</td>
<td>Visible</td>
</tr>
</tbody>
</table>
</section>
<section id="background-of-the-document" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Background of the document</h1>
<section id="executive-summary" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="executive-summary"><span class="header-section-number">1.1</span> Executive Summary</h2>
<p>The Global Land (GL) Component in the framework of Copernicus is earmarked as a component of the Land service to operate “a multi-purpose service component” that will provide a series of bio-geophysical products on the status and evolution of land surface at global scale. Production and delivery of the parameters are to take place in a timely manner and are complemented by the constitution of long term time series.</p>
<p>The Copernicus Global Land Service contains a Snow Cover Extent (SCE) Near Real Time (NRT) product extending Northern Hemisphere (NH) at 0.01 degree resolution. The SCE product provides information on the Fraction of Snow Cover (FSC) per pixel in percentage (0% – 100%). The SCE is derived from medium resolution optical satellite data.</p>
<p>The service is based on data from the Suomi Near-Polar-orbiting Partnership (S-NPP) Visible Infrared Imaging Radiometer Suite (VIIRS) and of Sentinel-3 (S3) Sea and Land Surface Temperature Radiometer (SLSTR) data. The NRT snow products provided as pre-operational service since January 2018 are based on S-NPP VIIRS data. From the winter season 2020/21 onwards, starting with 1st October 2020, the NRT service is planned to be based on the S3 SLSTR data. It is planned to continue the S-NPP VIIRS based service as backup.</p>
<p>The spectral capabilities of the sensor are used in combination with a digital elevation model, a transmissivity map describing the transmissivity of forest canopy, and surface classification maps to detect the fraction of snow cover per pixel in percentage. The usage of the transmissivity map allows also in forested areas to detect the snow on the ground.</p>
<p>The Product User Manual (PUM) is a self-contained document which gathers all necessary information to use the NH SCE product at 0.01 degree resolution on an efficient and reliable way.</p>
</section>
<section id="scope-and-objectives" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="scope-and-objectives"><span class="header-section-number">1.2</span> Scope and Objectives</h2>
<p>The Product User Manual (PUM) is the primary document that users should read before handling the products. It gives an overview of the product characteristics, in terms of algorithm, technical characteristics, and main validation results.</p>
</section>
<section id="content-of-the-document" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="content-of-the-document"><span class="header-section-number">1.3</span> Content of the document</h2>
<p>This document is structured as follows:</p>
<ul>
<li>Chapter 2 recalls the users’ requirements, and the expected performance</li>
<li>Chapter 3 summarizes the retrieval methodology</li>
<li>Chapter 4 describes the technical properties of the product</li>
<li>Chapter 5 summarizes the results of the quality assessment</li>
</ul>
</section>
<section id="related-documents" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="related-documents"><span class="header-section-number">1.4</span> Related documents</h2>
<section id="applicable-documents" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="applicable-documents"><span class="header-section-number">1.4.1</span> Applicable documents</h3>
<p>AD1: IGOS, 2007: Cryosphere Theme Report 2007. WMO/TD-No 1405. 100 pp.</p>
<p>AD2: GCOS, 2006: Systematic observation requirements for satellite-based products for climate. WMO/TD Report No.&nbsp;1338, September 2006.</p>
<p>AD3: GCOS – 200.2016. The Global Observing System for Climate: Implementation Needs. (GOOS-214). http://unfccc.int/files/science/workstreams/systematic_observation/application/pdf/gcos_ip_10oct2016.pdf</p>
<p>AD4: WMO OSCAR Observing Systems Capability Analysis and Review Tool; https://www.wmo-sat.info/oscar/observingrequirements</p>
<p>AD5: Annex I – Technical Specifications JRC/IPR/2015/H.5/0026/OC to Contract Notice 2015/S 151-277962 of 7<sup>th</sup> August 2015</p>
<p>AD6: Appendix 1 – Copernicus Global Land Component Product and Service Detailed Technical requirements to Technical Annex to Contract Notice 2015/S 151-277962 of 7<sup>th</sup> August 2015</p>
</section>
<section id="input" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="input"><span class="header-section-number">1.4.2</span> Input</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Document ID</th>
<th>Descriptor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CGLOPS2_SSD</td>
<td>Service Specifications of the Global Component of the Copernicus Land Service.</td>
</tr>
<tr class="even">
<td>CGLOPS2_ATBD_SCE-NHEMI-1km_V1</td>
<td>Algorithm Theoretical Basis Document of the SCE-NHEMI-1km_V1 product</td>
</tr>
<tr class="odd">
<td>CGLOPS2_QAR_SCE-NHEMI-1km_V1</td>
<td>Report describing the results of the scientific quality assessment of the SCE-NHEMI-1km_V1 product</td>
</tr>
<tr class="even">
<td>CGLOPS2_PRD_SCE-NHEMI-1km_V1</td>
<td>Product Requirements Document of the SCE-NHEMI-1km_V1 product</td>
</tr>
<tr class="odd">
<td>CGLOPS2_PSD_SCE-NHEMI-1km_V1</td>
<td>Product Specification Document of the SCE-NHEMI-1km_V1 product</td>
</tr>
<tr class="even">
<td>CGLOPS2_PUM_SCE500-CEURO-500m_V1</td>
<td>Product User Manual of the SCE500-CEURO-500m_V1 product</td>
</tr>
<tr class="odd">
<td>CGLOPS2_PUM_SCE-NHEMI-1km-V1</td>
<td>Product User Manual (final version) describing how to use the SCE-NHEMI-1km V1 product from S-NPP VIIRS data.</td>
</tr>
</tbody>
</table>
</section>
<section id="output" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="output"><span class="header-section-number">1.4.3</span> Output</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th>Document ID</th>
<th>Descriptor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CGLOPS2_PUM_SCE-NHEMI-1km-V1</td>
<td>Product User Manual (final version) describing how to use the SCE-NHEMI-1km V1 product from S3 SLSTR or S-NPP VIIRS data.</td>
</tr>
</tbody>
</table>
</section>
<section id="external-documents" class="level3" data-number="1.4.4">
<h3 data-number="1.4.4" class="anchored" data-anchor-id="external-documents"><span class="header-section-number">1.4.4</span> External documents</h3>
<p>ED1: CryoLand URD 2012. CryoLand User Requirement Document, URD , Final version. 31.05.2012. http://cryoland.enveo.at/docs/publications/CryoLand_No262925_D06.1_URD.pdf</p>
<p>ED2: Malnes, E., Buanes, A., Nagler, T., Bippus, G., Gustafsson, D., Schiller, C., Metsämäki, S., Pulliainen, J., Luojus, K., Larsen, H.E., Solberg, R., Diamandi, A., Wiesmann, A. (2015). User requirements for the snow and land ice services – CryoLand. The Cryosphere, 9, 1191–1202, doi:10.5194/tc-9-1191-2015.</p>
<p>ED3: Malenovský, Z., H. Rott, J. Cihlar, M. E Schaepman, G. García-Santos, R. Fernandes and M. Berger. 2012. Sentinels for Science: Potential of Sentinel-1, -2, and -3 missions for scientific observations of ocean, cryosphere, and land. Remote Sensing of Environment, vol.&nbsp;120, pp 91-101.</p>
</section>
</section>
</section>
<section id="review-of-users-requirements" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Review of Users Requirements</h1>
<p>According to the applicable documents [AD1] to [AD4], and the external documents [ED1] to [ED3], the users’ requirements relevant for the Northern Hemisphere Snow Cover Extent product are:</p>
<ul>
<li>Definition: Northern Hemisphere (NH) Snow Cover Extent (SCE)</li>
<li>Geometric properties:
<ul>
<li>Spatial resolution: Minimum: 4 km, Target: 500 m, 100 m in complex terrain</li>
<li>Grid / Projection: Geographic coordinates (latitude/longitude), WGS84 datum, WGS84 ellipsoid</li>
</ul></li>
<li>Geographical coverage:
<ul>
<li>Northern Hemisphere (84°N / 180°W – 25°N/180°E): land areas</li>
<li>Target: Global land areas</li>
</ul></li>
<li>Accuracy requirements:
<ul>
<li>Geometric accuracy: Minimum: 1/3 IFOV, Target: IFOV 1 km (100 m in complex terrain)</li>
<li>Thematic accuracy: Minimum: 15 %, Target: 5 %</li>
</ul></li>
<li>Temporal requirements:
<ul>
<li>Time period: Full year</li>
<li>Temporal frequency: Minimum: Daily, Target: 12 hours</li>
</ul></li>
<li>Delivery time:
<ul>
<li>Minimum: 24 hours after image acquisition, Target: 12 hours after image acquisition</li>
</ul></li>
</ul>
</section>
<section id="algorithm" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Algorithm</h1>
<section id="overview" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">3.1</span> Overview</h2>
<p>The SCE product is generated daily in near-real time for the NH land areas, including Greenland, based on medium resolution optical satellite data. The snow maps since January 2018 are generated from S-NPP VIIRS data. The NRT service based on S3 SLSTR data is planned to start with the beginning of the next winter season according to the hydrological year, on 1<sup>st</sup> October 2020. The production from S-NPP VIIRS data is planned to be continued then as backup service. The NH SCE product provides information on the Fraction of Snow Cover (FSC) on ground (also in forested areas) per pixel in percentage (0% – 100%), and is extending from 84°N/180°W to 25°N/180°E with a pixel size of 0.01° x 0.01° (approx. 1 km x 1 km). The product is provided within 1 day after the raw image acquisition.</p>
</section>
<section id="the-retrieval-methodology" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="the-retrieval-methodology"><span class="header-section-number">3.2</span> The retrieval Methodology</h2>
<p>The generation of the NH SCE product is based on a two-step approach: a pre-classification is performed using the Normalized Difference Snow Index (NDSI) which is based on the different reflectivity of snow and other surfaces in the visible and mid-infrared wavelengths (Hall et al.&nbsp;2002), combined with a threshold applied on the brightness temperature from a thermal infrared band. The NDSI is also used as basic map for cloud screening. On all pixels identified as potentially snow covered from the pre-classification, the SCAmod (Metsämäki et al.&nbsp;2005, 2012) algorithm is applied to classify fractional snow cover for the NH land areas. Further information is given in the CGLOPS2_ATBD_SCE-NHEMI-1km_V1.</p>
</section>
<section id="limitations-of-the-product" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="limitations-of-the-product"><span class="header-section-number">3.3</span> Limitations of the Product</h2>
<p>The SCAmod algorithm is very sensitive to the transmissivity map used as input. As the transmissivity map is derived from GlobCover data, boreal forests in Scandinavia and forests in southern latitudes or in other regions have similar transmissivity values in this map. This can partly result in misclassifications of snow.</p>
<p>In case of snow free ground but cold temperatures at night, which usually can occur from autumn till spring, surface hoar or hoar frost built up during night can remain until the satellite acquisition time late in the morning. Such areas often have very similar spectral signatures as snow covered areas and can thus be misclassified as snow.</p>
<p>During the polar night, a snow classification is not possible in the northern latitudes. All pixels with solar zenith angle greater than 80° are classified as “polar night”.</p>
<p>Very large sensor viewing zenith angles can introduce major errors in the snow classification or the cloud screening. Thus, pixels with sensor viewing zenith angles greater than 80° are excluded from the processing.</p>
</section>
<section id="differences-with-the-previous-version" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="differences-with-the-previous-version"><span class="header-section-number">3.4</span> Differences with the previous version</h2>
<p>This is the first version of the product.</p>
</section>
</section>
<section id="product-description" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Product Description</h1>
<section id="file-naming" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="file-naming"><span class="header-section-number">4.1</span> File Naming</h2>
<p>The Snow Cover Extent (SCE)-Northern Hemisphere (NHEMI)-1km product follows the naming standard:</p>
<p><code>c_gls_SCE_&lt;YYYYMMDDHHmm&gt;_&lt;AREA&gt;_&lt;SENSOR&gt;_V&lt;VERSION&gt;</code></p>
<p>e.g.</p>
<p><code>c_gls_SCE_202010010000_NHEMI_SLSTR_V1.0.1.nc</code></p>
<p>where:</p>
<ul>
<li><code>&lt;YYYYMMDDHHmm&gt;</code> gives the temporal location of the file. YYYY, MM, DD, HH and mm denote the year, the month, the day, the hour and the minutes respectively. The products are daily composites, so the time “0000” is used for the “HHmm” in the file name. Detailed start and end times are provided in the metadata (Table 4.3).</li>
<li><code>&lt;AREA&gt;</code> gives the spatial coverage of the file. In our case, <code>&lt;AREA&gt;</code> is NHEMI, short name for Northern Hemisphere.</li>
<li><code>&lt;SENSOR&gt;</code> gives the name of the sensors used to retrieve the product, with VIIRS referring to Suomi NPP Visible Infrared Imaging Radiometer Suite, and SLSTR to Sentinel-3 Sea and Land Surface Temperature Radiometer</li>
<li><code>&lt;VERSION&gt;</code> shows the processing line version used to generate these SCE_NRT_1km products. The version denoted as M.m.r (e.g.&nbsp;1.0.1), with ‘M’ representing the major version (e.g.&nbsp;V1), ‘m’ the minor version (starting from 0) and ‘r’ the production run number (starting from 1) (Table 4.1).</li>
</ul>
<div class="tbl-caption">
<p>Table 4.1: Explanation in version numbering and recommendations for using efficiently the products.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 36%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Versions</th>
<th>Differences</th>
<th>Recommendations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Major</td>
<td>Significant change to the algorithm.</td>
<td>Do not mix various major versions in the same applications, unless it is otherwise stated.</td>
</tr>
<tr class="even">
<td>Minor</td>
<td>Minor changes in the algorithm</td>
<td>Can be mixed in the same applications, but require attention or modest modifications</td>
</tr>
<tr class="odd">
<td>Run</td>
<td>Fixes to bugs and minor issues. Later run automatically replaces former</td>
<td>Consider it as a drop-in replacement</td>
</tr>
</tbody>
</table>
</section>
<section id="file-format" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="file-format"><span class="header-section-number">4.2</span> File Format</h2>
<p>The SCE-NHEMI-1km products are delivered as Network Common Data Form version 4 (netCDF4) file with metadata attributes compliant with version 1.7 of the Climate &amp; Forecast conventions (CF V1.7) containing the following layer:</p>
<ul>
<li><code>SCE</code>: Snow Cover Extent value</li>
</ul>
<p>The coverage of the file corresponds to the spatial extent of the NH defined for cryospheric parameters (84°N/180°W – 25°N/180°E).</p>
</section>
<section id="product-content" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="product-content"><span class="header-section-number">4.3</span> Product Content</h2>
<section id="data-file" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="data-file"><span class="header-section-number">4.3.1</span> Data File</h3>
<p>The SCE NHEMI product, including the product coding, is a heritage of the SCE CEURO500 product (CGLOPS2_PUM_SCE500-CEURO-500m_V1) developed originally within the EU FP7 project CryoLand. We decided to continue basically with the same coding definitions also for the SCE NHEMI products (Table 4.2) to support known implementations of key users using the SCE products as input for their operational systems. Information on the water type (sea, lake, river) is only available for the Pan-European domain from the Copernicus CORINE Land Cover data set. For the NH SCE products, the water bodies are based on the ESA CCI Land Cover data set of the year 2015. All pixels classified as water are masked in the NH SCE product with the same code, independent of the water type.</p>
<div class="tbl-caption">
<p>Table 4.2: Description of the product coding provided for SCE-NHEMI-1km product.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 26%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Code value</th>
<th>Class</th>
<th>Comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Outside area of interest</td>
<td>Outside of NH</td>
</tr>
<tr class="even">
<td>20</td>
<td>Sea mask</td>
<td>Water mask</td>
</tr>
<tr class="odd">
<td>30</td>
<td>Cloud mask</td>
<td>Generated by Single Cloud Detection Approach 2.0 (Metsämäki et al.&nbsp;2015)</td>
</tr>
<tr class="even">
<td>251</td>
<td>Polar night</td>
<td>If solar zenith angle for pixel &gt; 80°</td>
</tr>
<tr class="odd">
<td>254</td>
<td>Input data error</td>
<td></td>
</tr>
<tr class="even">
<td>255</td>
<td>No data</td>
<td>No data within the extent of NH</td>
</tr>
<tr class="odd">
<td>100 - 200</td>
<td>Snow Cover Extent</td>
<td>For interpretation of the SCE in percent scaled between 0% and 100% use the following conversion: <code>SCE = CODE – 100</code></td>
</tr>
</tbody>
</table>
<p>The netCDF files contain a number of netCDF metadata attributes</p>
<ul>
<li>on the file-level (Table 4.3 and Table 4.4);</li>
<li>on the layer-level (Table 4.5);</li>
<li>at the level of the standard dimension variables for latitude (‘lat’) and longitude (‘lon’), holding one value per row or column respectively (Table 4.6);</li>
<li>at the level of the grid mapping (spatial reference system) variable (‘crs’) (Table 4.7).</li>
</ul>
<div class="tbl-caption">
<p>Table 4.3: Description of netCDF file attributes, Global Land extensions.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 58%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Attribute name</strong></td>
<td><strong>Description</strong></td>
<td><strong>Data Type</strong></td>
<td><strong>Example(s)</strong></td>
</tr>
<tr class="even">
<td>Conventions</td>
<td>Version of the CF-Conventions used</td>
<td>String</td>
<td>CF-1.7</td>
</tr>
<tr class="odd">
<td>title</td>
<td>A description of the contents of the file</td>
<td>String</td>
<td>Fractional Snow Cover, northern hemisphere, Sentinel-3 SLSTR (0.01deg., 2020-10-01)</td>
</tr>
<tr class="even">
<td>institution</td>
<td>The name of the institution that produced the product</td>
<td>String</td>
<td>ENVEO IT GmbH</td>
</tr>
<tr class="odd">
<td>source</td>
<td>The method of production of the original data</td>
<td>String</td>
<td>Derived from EO satellite imagery</td>
</tr>
<tr class="even">
<td>history</td>
<td>A global attribute for an audit trail. One line, including date in ISO-8601 format, for each invocation of a program that has modified the dataset.</td>
<td>String</td>
<td>2020-10-01 Processing line SCE</td>
</tr>
<tr class="odd">
<td>references</td>
<td>Published or web based references that describe the data or methods used to produce it.</td>
<td>String</td>
<td>http://land.copernicus.eu/global/products/sce</td>
</tr>
<tr class="even">
<td>archive_facility</td>
<td>Specifies the name of the institution that archives the product</td>
<td>String</td>
<td>CLS</td>
</tr>
<tr class="odd">
<td>product_version</td>
<td>Version of the product (VM.m.r)</td>
<td>String</td>
<td>V1.0.1</td>
</tr>
<tr class="even">
<td>time_coverage_start</td>
<td>Start date and time of the total coverage of the data for the product.</td>
<td>String</td>
<td>2020-10-01T00:55:26.4Z</td>
</tr>
<tr class="odd">
<td>time_coverage_end</td>
<td>End date and time of the total coverage of the data for the product.</td>
<td>String</td>
<td>2020-10-01T19:49:10.2Z</td>
</tr>
<tr class="even">
<td>platform</td>
<td>Name(s) of the orbiting platform(s)</td>
<td>String</td>
<td>Suomi_NPP, Sentinel-3</td>
</tr>
<tr class="odd">
<td>sensor</td>
<td>Name(s) of the sensor(s) used</td>
<td>String</td>
<td>VIIRS, SLSTR</td>
</tr>
<tr class="even">
<td>identifier</td>
<td>Unique identifier for the product</td>
<td>String</td>
<td>urn:cgls:global:sce_v1_0.01degree:SCE_202010010000_NHEMI_SLSTR_V1.0.1</td>
</tr>
<tr class="odd">
<td>parent_identifier</td>
<td>Identifier of the product collection (time series) for the product in Copernicus Global Land Service metadata catalogue.</td>
<td>String</td>
<td>urn:cgls:global:sce_v1_0.01degree</td>
</tr>
<tr class="even">
<td>long_name</td>
<td>Extended product name</td>
<td>String</td>
<td>Snow Cover Extent</td>
</tr>
<tr class="odd">
<td>orbit_type</td>
<td>Orbit type of the orbiting platform(s)</td>
<td>String</td>
<td>LEO</td>
</tr>
<tr class="even">
<td>processing_level</td>
<td>Product processing level</td>
<td>String</td>
<td>L3</td>
</tr>
<tr class="odd">
<td>processing_mode</td>
<td>Processing mode used when generating the product (Near-Real Time, Consolidated or Reprocessing)</td>
<td>String</td>
<td>Near Real Time</td>
</tr>
<tr class="even">
<td>copyright</td>
<td>Text to be used by users when referring to the data source of this product in publications (copyright notice)</td>
<td>String</td>
<td>Copernicus Service information 2019</td>
</tr>
</tbody>
</table>
<div class="tbl-caption">
<p>Table 4.4: Description of file-level netCDF file attributes, extensions for self-standing products.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 5%">
<col style="width: 57%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Attribute name</strong></td>
<td><strong>Description</strong></td>
<td><strong>Data Type</strong></td>
<td><strong>Example(s)</strong></td>
</tr>
<tr class="even">
<td>comment</td>
<td>Miscellaneous information about the data or methods used to product it.<br>
When no separate XML is provided, copy its 'Abstract' element. Otherwise, leave empty.</td>
<td>String</td>
<td>The SCE product provides daily information on fractional snow cover (0-100%) per pixel for the northern hemisphere with about 1 km pixel size. The product is based on medium resolution optical satellite data. In forested areas, the product provides information on snow on ground. SCE information is useful for applications related inter alia to climatology, meteorology, hydrology or environmental monitoring. The following auxiliary data sets are used for product generation: Land Cover Map 2015 from ESA Land Cover CCI, GMTED2010, Transmissivity V2.0.</td>
</tr>
<tr class="odd">
<td>contacts</td>
<td>Contacts for the various parties involved in the production of the data. Includes contacts for : Copernicus GL helpdesk, product originator, principal investigator, owner, distributor and custodian</td>
<td>String</td>
<td>Helpdesk:<br>
http://land.copernicus.eu/global/contactpage<br>
<br>
Accountable contact: European Commission DG Joint Research Centre copernicuslandproducts@jrc.ec.europa.eu<br>
<br>
Owner contact: European Commission DG Internal Market, Industry, Entrepreneurship and SMEs ENTR-COPERNICUS-ASSETS@ec.europa.eu<br>
<br>
Production contact: Finnish Meteorological Institute kari.luojus@fmi.fi<br>
<br>
Scientific contacts: SYKE sari.metsamaki@environment.fi<br>
<br>
kirsikka.heinila@environment.fi<br>
<br>
ENVEO IT GmbH thomas.nagler@enveo.at gabriele.schwaizer@enveo.at</td>
</tr>
<tr class="even">
<td>Inspire_theme</td>
<td>INSPIRE theme for the product</td>
<td>String</td>
<td>Orthoimagery</td>
</tr>
<tr class="odd">
<td>gemet_keywords</td>
<td>A mandatory sequence of keywords taken form the GEMET thesaurus that can be used to describe the product</td>
<td>String</td>
<td>snow; climate; seasonal variation; hydrology; environmental data; environmental monitoring; monitoring; remote sensing</td>
</tr>
<tr class="even">
<td>gcmd_keywords</td>
<td>An optional sequence of keywords taken from NASA's GCMD (http://gcmd.nasa.gov/) that can be used to describe the product</td>
<td>String</td>
<td>SNOW COVER</td>
</tr>
<tr class="odd">
<td>iso19115_topic_categories</td>
<td>A sequence of ISO19115 topic categories that can be used to describe the product</td>
<td>String</td>
<td>ClimatologyMeteorologyAtmosphere; environment</td>
</tr>
<tr class="even">
<td>credit</td>
<td>Product copyright and attribution information</td>
<td>String</td>
<td>See Section 4.4.4.</td>
</tr>
<tr class="odd">
<td>purpose</td>
<td></td>
<td>String</td>
<td>This product is first designed to fit the requirements of the Global Land component of Land Service of Copernicus. It can be also useful for all applications related to the environment monitoring.</td>
</tr>
</tbody>
</table>
<div class="tbl-caption">
<p>Table 4.5: Description of netCDF layer attributes.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 13%">
<col style="width: 39%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Attribute</strong></td>
<td><strong>Description</strong></td>
<td><strong>Data Type</strong></td>
<td><strong>Example(s)</strong></td>
</tr>
<tr class="even">
<td>CLASS</td>
<td>Dataset type</td>
<td>String</td>
<td>DATA</td>
</tr>
<tr class="odd">
<td>standard_name</td>
<td>A standardized name that references a description of a variable's content in CF-Convention's standard names table. Note that each standard_name has a corresponding unit (from Unidata's udunits).</td>
<td>String</td>
<td>surface_snow_area_fraction</td>
</tr>
<tr class="even">
<td>long_name</td>
<td>A descriptive name that indicates a variable's content. This name is not standardized. Required when a standard name is not available.</td>
<td>String</td>
<td>Fractional Snow Cover</td>
</tr>
<tr class="odd">
<td>units</td>
<td>Units of a the variable's content, taken from Unidata's udunits library.</td>
<td>String</td>
<td>percent</td>
</tr>
<tr class="even">
<td>valid_range</td>
<td>Smallest and largest values for the variable.<br>
<br>
Missing data is to be represented by one or several values outside of this range.</td>
<td>Same as data variable</td>
<td>100,200</td>
</tr>
<tr class="odd">
<td>_FillValue</td>
<td>Single value used to represent missing or undefined data and to pre-fill memory space in case a non-written part of data is read back.<br>
<br>
Value must be outside of valid_range.</td>
<td>Same as data variable</td>
<td>255</td>
</tr>
<tr class="even">
<td>missing_value</td>
<td>Single value used to represent missing or undefined data, for applications following older versions of the standards.<br>
<br>
Value must be outside of valid_range.</td>
<td>Same as data variable</td>
<td>255</td>
</tr>
<tr class="odd">
<td>grid_mapping</td>
<td>Reference to the grid mapping variable</td>
<td>String</td>
<td>crs</td>
</tr>
<tr class="even">
<td>ancillary_variables*</td>
<td>Optional identification of other closely related layers in the same file.</td>
<td>String</td>
<td>Land Cover CCI Surface Classification 2015, GMTED2010, Transmissivity V2.0</td>
</tr>
<tr class="odd">
<td>flag_values</td>
<td>Provides a list of the flag values. Used in conjunction with flag_meanings.</td>
<td>Same as data variable</td>
<td>0, 20, 30, 251, 254</td>
</tr>
<tr class="even">
<td>flag_meanings</td>
<td>Descriptive words or phrases for each flag value.</td>
<td>String</td>
<td>Outside_Area_of_Interest Sea Cloud Polar_Night Input_Data_Error</td>
</tr>
</tbody>
</table>
<p>*) Will be added from 1st October 2020 onwards.</p>
<div class="tbl-caption">
<p>Table 4.6: Description of netCDF attributes for coordinate dimensions (latitudes and longitudes).</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 35%">
<col style="width: 13%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Attribute</strong></td>
<td><strong>Description</strong></td>
<td><strong>Data Type</strong></td>
<td><strong>Example(s)</strong></td>
</tr>
<tr class="even">
<td>CLASS</td>
<td>Dataset type</td>
<td>String</td>
<td>DIMENSION_SCALE</td>
</tr>
<tr class="odd">
<td>DIMENSION_LABELS</td>
<td>Label used in netCDF4 library</td>
<td>String</td>
<td>lon</td>
</tr>
<tr class="even">
<td>NAME</td>
<td>Short name</td>
<td>String</td>
<td>lon</td>
</tr>
<tr class="odd">
<td>standard_name</td>
<td>A standardized name that references a description of a variable's content in CF-Convention's standard names table. Note that each standard_name has corresponding unit (from Unidata's udunits).</td>
<td>String</td>
<td>longitude</td>
</tr>
<tr class="even">
<td>long_name</td>
<td>A descriptive name that indicates a variable's content. This name is not standardized. Required when a standard name is not available.</td>
<td>String</td>
<td>longitude</td>
</tr>
<tr class="odd">
<td>units</td>
<td>Units of the variable's content, taken from Unidata's udunits library.</td>
<td>String</td>
<td>degrees_east</td>
</tr>
<tr class="even">
<td>axis</td>
<td>Identifies latitude, longitude, vertical, or time axes.</td>
<td>String</td>
<td>X</td>
</tr>
</tbody>
</table>
<div class="tbl-caption">
<p>Table 4.7: Description of netCDF attributes for the grid mapping variable.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 73%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Attribute</strong></td>
<td><strong>Description</strong></td>
<td><strong>Data Type</strong></td>
<td><strong>Example(s)</strong></td>
</tr>
<tr class="even">
<td>GeoTransform</td>
<td>Six coefficients for the affine transformation from pixel/line space to coordinate space, as defined in GDAL's GeoTransform</td>
<td>String</td>
<td>-180 0.01 0 84 0 -0.01</td>
</tr>
<tr class="odd">
<td>longitude_of_prime_meridian</td>
<td>Projection center line</td>
<td>Double</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>semi_major_axis</td>
<td>Radius of Earth used for projection (m)</td>
<td>Double</td>
<td>6378137</td>
</tr>
<tr class="odd">
<td>grid_mapping_name</td>
<td>Name used to identify the grid mapping</td>
<td>String</td>
<td>latitude_longitude</td>
</tr>
<tr class="even">
<td>inverse_flattening</td>
<td>Used to specify the inverse flattening (1/f) of the ellipsoidal figure associated with the geodetic datum and used to approximate the shape of the Earth</td>
<td>Float</td>
<td>298.257223563</td>
</tr>
<tr class="odd">
<td>spatial_ref</td>
<td>Spatial reference system in OGC's Well-Known Text (WKT) format</td>
<td>String</td>
<td>GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]]</td>
</tr>
</tbody>
</table>
</section>
<section id="quicklook" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="quicklook"><span class="header-section-number">4.3.2</span> Quicklook</h3>
<p>A daily quicklook is provided as a GEOTIFF file.</p>
</section>
</section>
<section id="product-characteristics" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="product-characteristics"><span class="header-section-number">4.4</span> Product Characteristics</h2>
<section id="projection-and-grid-information" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="projection-and-grid-information"><span class="header-section-number">4.4.1</span> Projection and Grid Information</h3>
<p>The product is projected in a regular latitude/longitude grid with the ellipsoid WGS 1984 (Terrestrial radius=6378km, EPSG: 4326). The resolution of the grid is 0.01 degree. Coordinate reference is the upper left corner of the pixel. The origin is the upper left corner of the upper left pixel.</p>
</section>
<section id="spatial-information" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="spatial-information"><span class="header-section-number">4.4.2</span> Spatial Information</h3>
<p>The NH SCE product is provided from longitude 180°W to 180°E and latitude 25°N to 84°N.</p>
</section>
<section id="temporal-information" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="temporal-information"><span class="header-section-number">4.4.3</span> Temporal Information</h3>
<p>The SCE-NHEMI-1km is a daily product provided throughout the whole year. The NRT product generation from S-NPP VIIRS data started in January 2018. The NRT product generation from S3 SLSTR data in planned to start in October 2020.</p>
</section>
<section id="data-policies" class="level3" data-number="4.4.4">
<h3 data-number="4.4.4" class="anchored" data-anchor-id="data-policies"><span class="header-section-number">4.4.4</span> Data Policies</h3>
<p>Any use of the SCE-NHEMI-1km product implies the obligation to include in any publication or communication using these products the following citation:</p>
<p>“The product was generated by the land service of Copernicus, the Earth Observation program of the European Commission. The research leading to the current version of the product has received funding from various European Commission Research and Technical Development programs. The product is based on [SATINFO].”</p>
<p>The field [SATINFO] depends on the satellite data used for the product generation and can be one of the following:</p>
<ul>
<li>Sentinel-3 SLSTR 500 m / 1 km data (©Copernicus/ESA)</li>
<li>Suomi-NPP VIIRS 750 m data (© NOAA)</li>
</ul>
<p>The user accepts to inform Copernicus about the outcome of the use of the above-mentioned products and to send a copy of any publications that use these products to the following address gabriele.schwaizer@enveo.at.</p>
</section>
<section id="contacts" class="level3" data-number="4.4.5">
<h3 data-number="4.4.5" class="anchored" data-anchor-id="contacts"><span class="header-section-number">4.4.5</span> Contacts</h3>
<p>Accountable contact: European Commission Directorate-General Joint Research Centre</p>
<p>Email address: copernicuslandproducts@jrc.ec.europa.eu</p>
<p>Scientific, Production and Distribution contact: ENVEO IT GmbH, Austria</p>
<p>Email address: gabriele.schwaizer@enveo.at (primary contact)</p>
<p>sce.globland@enveo.at (ftp-server issues, file availability, and issues with file format)</p>
</section>
</section>
</section>
<section id="validation" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Validation</h1>
<p>The validation of the NH SCE products from S-NPP VIIRS data has been performed with more than 200 selected Landsat scenes acquired in between January 2018 and April 2019, and with more than 200’000 in-situ measurements of snow depth available for the periods January – June 2018 and October 2018 – June 2019. The validation of the NH SCE products from S3 SLSTR data has been performed with about 100 selected Landsat scenes acquired between November 2018 and May 2019, and with more than 60’000 in-situ measurements of snow depth available for the period January - May 2019.</p>
<p>For the generation of reference snow maps from Landsat data, three different snow algorithms (Dozier and Painter 2004, Klein, Hall, and Riggs 1998, Salomonson and Appel 2004, 2006) are applied on each Landsat scene. The SCE product has been validated on a pixel-by-pixel comparison using statistical measures to describe the performance of the product (CGLOPS2_QAR_SCE-NHEMI-1km_V1), following the validation protocols developed and agreed by the international snow community within the ESA QA4EO Satellite Snow Product Intercomparison and Evaluation Exercise (SnowPEx).</p>
<p>The mean resulting unbiased Root Mean Square Error (RMSE) derived from the validation of the SCE product with all reference snow maps is about 13%, independently of the applied snow algorithm for the generation of the reference snow map and the sensor used for the NH SCE product generation. The mean Bias derived for validation with Landsat snow maps is in slightly negative, about -3% for S-NPP VIIRS based NH SCE products, and about -4% for S3 SLSTR based NH SCE products.</p>
<p>Additional to the overall performance, the NH SCE products were analysed separately for different surface and terrain classes, considering forested / non-forested areas as well as mountains / plains and combinations of these classes. For all forested classes, only Landsat based reference snow maps generated with snow algorithms resulting in the same thematic information as the SCE product, namely snow on ground, are used for the validation. For non-forested classes, all algorithms used for the reference snow map generation are considered.</p>
<p>In forested areas, the resulting mean unbiased RMSE is about 14% for NH SCE products from both sensors. The mean Bias is about -2% for NH SCE products from S-NPP VIIRS data, while the mean Bias for NH SCE products from S3 SLSTR data is slightly more negative, about -5%.</p>
<p>In non-forested areas the mean unbiased RMSE for NH SCE products from S-NPP VIIRS data is slightly lower, about 12%, with a slightly more negative mean Bias values of about -4%. For NH SCE products from S3 SLSTR data, the mean unbiased RMSE for non-forested areas is only 9%, and the mean Bias value for this class is only -2%. The slightly negative bias values indicate an underestimation of snow by the NH SCE product from both sensors compared to the reference snow maps from Landsat imagery.</p>
<p>Additionally, the agreement of the fraction of snow cover of the SCE product with the aggregated fractional snow cover from the selected Landsat scenes is assessed. In case of fractional snow cover ≤75%, the NH SCE products rather overestimate the reference snow cover, while for areas largely covered by snow (76% - 100%), the NH SCE products tend to slightly underestimate the reference snow cover derived from Landsat data. This pattern is observed independent of the sensor used for the NH SCE product generation.</p>
<p>Although the range of the resulting statistics can be large for some validation cases, the overall results indicate that the product performance is meeting the user requirements of &lt;15% thematic accuracy for all surface classes, independent of the satellite sensor used for the product generation.</p>
<p>The range of the resulting statistics can be large depending on the surface class and the terrain, as also indicated by the mean results shown in Table 5.1 for S-NPP VIIRS based NH SCE products, and in Table 5.2 for S3 SLSTR based NH SCE products.</p>
<div class="tbl-caption">
<p>Table 5.1: Summary of statistical measures resulting from the validation of the NH SCE product from S-NPP VIIRS data with selected Landsat scenes covering various classes. Reference snow algorithms: S = Salomonson &amp; Appel, 2006; K = Klein et al., 1998; D = Dozier and Painter, 2004.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" style="font-weight: bold; vertical-align: middle">Surface class</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle">Snow algorithm</td>
<td colspan="3" style="font-weight: bold">Unbiased RMSE</td>
<td colspan="3" style="font-weight: bold">Bias</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle">Mean Correlation Coefficient</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle"># pixels used for validation</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle"># LC08 scenes</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Min</td>
<td style="text-align: center; font-weight: bold;">Mean</td>
<td style="text-align: center; font-weight: bold;">Max</td>
<td style="text-align: center; font-weight: bold;">Min</td>
<td style="text-align: center; font-weight: bold;">Mean</td>
<td style="text-align: center; font-weight: bold;">Max</td>
</tr>
<tr class="odd">
<td rowspan="2" style="vertical-align: middle">Total area</td>
<td>K</td>
<td style="text-align: right;">0,04</td>
<td style="text-align: right;">12,45</td>
<td style="text-align: right;">38,89</td>
<td style="text-align: right;">-48,16</td>
<td style="text-align: right;">-4,08</td>
<td style="text-align: right;">14,49</td>
<td style="text-align: right;">0,45</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">8876240</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">209</td>
</tr>
<tr class="even">
<td>D</td>
<td style="text-align: right;">0,03</td>
<td style="text-align: right;">12,93</td>
<td style="text-align: right;">36,64</td>
<td style="text-align: right;">-23,24</td>
<td style="text-align: right;">-1,18</td>
<td style="text-align: right;">23,96</td>
<td style="text-align: right;">0,47</td>
</tr>
<tr class="odd">
<td rowspan="3" style="vertical-align: middle">Total non-forested area</td>
<td>S</td>
<td style="text-align: right;">0,04</td>
<td style="text-align: right;">11,30</td>
<td style="text-align: right;">35,22</td>
<td style="text-align: right;">-30,21</td>
<td style="text-align: right;">-1,97</td>
<td style="text-align: right;">7,50</td>
<td style="text-align: right;">0,53</td>
<td rowspan="3" style="text-align: right; vertical-align: middle;">5311230</td>
<td rowspan="3" style="text-align: right; vertical-align: middle;">209</td>
</tr>
<tr class="even">
<td>K</td>
<td style="text-align: right;">0,04</td>
<td style="text-align: right;">11,86</td>
<td style="text-align: right;">36,95</td>
<td style="text-align: right;">-39,95</td>
<td style="text-align: right;">-5,25</td>
<td style="text-align: right;">2,65</td>
<td style="text-align: right;">0,44</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">0,03</td>
<td style="text-align: right;">11,63</td>
<td style="text-align: right;">36,64</td>
<td style="text-align: right;">-39,14</td>
<td style="text-align: right;">-3,83</td>
<td style="text-align: right;">5,09</td>
<td style="text-align: right;">0,48</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Total forested area</td>
<td>K</td>
<td style="text-align: right;">0,00</td>
<td style="text-align: right;">13,95</td>
<td style="text-align: right;">39,40</td>
<td style="text-align: right;">-50,24</td>
<td style="text-align: right;">-4,27</td>
<td style="text-align: right;">25,00</td>
<td style="text-align: right;">0,37</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">3565010</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">200</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">0,00</td>
<td style="text-align: right;">14,66</td>
<td style="text-align: right;">36,37</td>
<td style="text-align: right;">-26,03</td>
<td style="text-align: right;">0,63</td>
<td style="text-align: right;">40,00</td>
<td style="text-align: right;">0,39</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Total plains</td>
<td>K</td>
<td style="text-align: right;">0,00</td>
<td style="text-align: right;">10,06</td>
<td style="text-align: right;">37,53</td>
<td style="text-align: right;">-48,16</td>
<td style="text-align: right;">-3,92</td>
<td style="text-align: right;">15,53</td>
<td style="text-align: right;">0,38</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">5519657</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">208</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">0,00</td>
<td style="text-align: right;">10,56</td>
<td style="text-align: right;">36,64</td>
<td style="text-align: right;">-31,00</td>
<td style="text-align: right;">-1,28</td>
<td style="text-align: right;">23,57</td>
<td style="text-align: right;">0,40</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Total mountains</td>
<td>K</td>
<td style="text-align: right;">0,99</td>
<td style="text-align: right;">13,21</td>
<td style="text-align: right;">35,18</td>
<td style="text-align: right;">-57,27</td>
<td style="text-align: right;">-3,14</td>
<td style="text-align: right;">15,37</td>
<td style="text-align: right;">0,52</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">3356583</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">119</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">0,99</td>
<td style="text-align: right;">12,99</td>
<td style="text-align: right;">29,74</td>
<td style="text-align: right;">-20,02</td>
<td style="text-align: right;">-1,22</td>
<td style="text-align: right;">24,96</td>
<td style="text-align: right;">0,53</td>
</tr>
</tbody>
</table>
<div class="tbl-caption">
<p>Table 5.2: Summary of statistical measures resulting from the validation of the NH SCE product from S3 SLSTR data with selected Landsat scenes covering various classes. Reference snow algorithms: S = Salomonson &amp; Appel, 2006; K = Klein et al., 1998; D = Dozier and Painter, 2004.</p>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td rowspan="2" style="font-weight: bold; vertical-align: middle">Surface class</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle">Snow algorithm</td>
<td colspan="3" style="font-weight: bold">Unbiased RMSE</td>
<td colspan="3" style="font-weight: bold">Bias</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle">Mean Correlation Coefficient</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle"># pixels used for validation</td>
<td rowspan="2" style="font-weight: bold; vertical-align: middle"># LC08 scenes</td>
</tr>
<tr class="even">
<td style="text-align: center; font-weight: bold;">Min</td>
<td style="text-align: center; font-weight: bold;">Mean</td>
<td style="text-align: center; font-weight: bold;">Max</td>
<td style="text-align: center; font-weight: bold;">Min</td>
<td style="text-align: center; font-weight: bold;">Mean</td>
<td style="text-align: center; font-weight: bold;">Max</td>
</tr>
<tr class="odd">
<td rowspan="2" style="vertical-align: middle">Total area</td>
<td>K</td>
<td style="text-align: right;">0,19</td>
<td style="text-align: right;">12,96</td>
<td style="text-align: right;">42,28</td>
<td style="text-align: right;">-38,98</td>
<td style="text-align: right;">-4,77</td>
<td style="text-align: right;">4,19</td>
<td style="text-align: right;">0,43</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">5641820</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">100</td>
</tr>
<tr class="even">
<td>D</td>
<td style="text-align: right;">0,19</td>
<td style="text-align: right;">13,10</td>
<td style="text-align: right;">43,86</td>
<td style="text-align: right;">-38,09</td>
<td style="text-align: right;">-3,25</td>
<td style="text-align: right;">15,39</td>
<td style="text-align: right;">0,42</td>
</tr>
<tr class="odd">
<td rowspan="3" style="vertical-align: middle">Total non-forested area</td>
<td>S</td>
<td style="text-align: right;">0,66</td>
<td style="text-align: right;">9,05</td>
<td style="text-align: right;">23,32</td>
<td style="text-align: right;">-21,09</td>
<td style="text-align: right;">0,29</td>
<td style="text-align: right;">13,65</td>
<td style="text-align: right;">0,53</td>
<td rowspan="3" style="text-align: right; vertical-align: middle;">3322154</td>
<td rowspan="3" style="text-align: right; vertical-align: middle;">100</td>
</tr>
<tr class="even">
<td>K</td>
<td style="text-align: right;">0,17</td>
<td style="text-align: right;">9,32</td>
<td style="text-align: right;">25,02</td>
<td style="text-align: right;">-31,31</td>
<td style="text-align: right;">-3,22</td>
<td style="text-align: right;">2,97</td>
<td style="text-align: right;">0,44</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">0,17</td>
<td style="text-align: right;">9,10</td>
<td style="text-align: right;">24,71</td>
<td style="text-align: right;">-29,99</td>
<td style="text-align: right;">-2,22</td>
<td style="text-align: right;">9,46</td>
<td style="text-align: right;">0,48</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Total forested area</td>
<td>K</td>
<td style="text-align: right;">0,04</td>
<td style="text-align: right;">14,24</td>
<td style="text-align: right;">44,80</td>
<td style="text-align: right;">-39,66</td>
<td style="text-align: right;">-5,67</td>
<td style="text-align: right;">46,50</td>
<td style="text-align: right;">0,38</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">2319666</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">97</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">0,03</td>
<td style="text-align: right;">14,46</td>
<td style="text-align: right;">46,34</td>
<td style="text-align: right;">-38,77</td>
<td style="text-align: right;">-3,53</td>
<td style="text-align: right;">54,00</td>
<td style="text-align: right;">0,38</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Total plains</td>
<td>K</td>
<td style="text-align: right;">1,03</td>
<td style="text-align: right;">11,11</td>
<td style="text-align: right;">40,48</td>
<td style="text-align: right;">-17,33</td>
<td style="text-align: right;">-1,90</td>
<td style="text-align: right;">4,39</td>
<td style="text-align: right;">0,46</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">3256109</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">100</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">1,03</td>
<td style="text-align: right;">11,25</td>
<td style="text-align: right;">42,62</td>
<td style="text-align: right;">-20,91</td>
<td style="text-align: right;">-1,45</td>
<td style="text-align: right;">11,49</td>
<td style="text-align: right;">0,45</td>
</tr>
<tr class="even">
<td rowspan="2" style="vertical-align: middle">Total mountains</td>
<td>K</td>
<td style="text-align: right;">1,03</td>
<td style="text-align: right;">11,11</td>
<td style="text-align: right;">40,48</td>
<td style="text-align: right;">-17,33</td>
<td style="text-align: right;">-1,90</td>
<td style="text-align: right;">4,39</td>
<td style="text-align: right;">0,46</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">2385711</td>
<td rowspan="2" style="text-align: right; vertical-align: middle;">60</td>
</tr>
<tr class="odd">
<td>D</td>
<td style="text-align: right;">1,03</td>
<td style="text-align: right;">11,25</td>
<td style="text-align: right;">42,62</td>
<td style="text-align: right;">-20,91</td>
<td style="text-align: right;">-1,45</td>
<td style="text-align: right;">11,49</td>
<td style="text-align: right;">0,45</td>
</tr>
</tbody>
</table>
<p>Further, the NH SCE products were validated with in-situ snow depth measurements. For this validation, both, the SCE and the in-situ products were translated into binary snow information. Two options were investigated to compare binary snow information from the NH SCE products from S-NPP VIIRS data and in-situ measurements: FSC &gt; 15% and SD &gt; 2cm, and FSC &gt; 10% and SD &gt; 1cm. For the S3 SLSTR based NH SCE products, the validation was performed using FSC &gt; 15% and SD &gt; 2cm, as well as FSC &gt; 15% and SD &gt; 1cm.</p>
<p>For the in-situ measurements, the applied snow depth thresholds were used assuming that the total surrounding area covering the associated pixel in the SCE product is snow covered. The comparison of these snow covered, and snow free pixel information resulted for the S-NPP VIIRS based NH SCE products in an overall accuracy of 92%, with the omission and commission errors &lt;10%. For S3 SLSTR based NH SCE products, an overall accuracy of 87% and omission and commission errors &lt;15% were achieved.</p>
<p>The overall validation results indicate that the NH SCE product matches the minimum thematic accuracy requirements of &lt;15% FSC defined by the users.</p>
</section>
<section id="references" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> References</h1>
<p>Dozier, J., and T. H. Painter. 2004. “Multispectral and Hyperspectral Remote Sensing of Alpine Snow Properties.” Annual Review of Earth and Planetary Sciences 32: 465 – 494.</p>
<p>Hall, D. K., G. A. Riggs, V. V. Salomonson, N. DiGiromamo, and K. J. Bayr. 2002. “MODIS Snow-Cover Products.” Remote Sensing of Environment 83: 181–94.</p>
<p>Klein, Andrew G, Dorothy K Hall, and George A Riggs. 1998. “Improving Snow Cover Mapping in Forests through the Use of a Canopy Reflectance Model.” Hydrological Processes 12: 1723– 44.</p>
<p>Metsämäki, S., S. Anttila, M. Huttunen, and J. Vepsäläinen. 2005. “A Feasible Method for Fractional Snow Cover Mapping in Boreal Zone Based on a Reflectance Model.” Remote Sensing of Environment 95 (1): 77–95.</p>
<p>Metsämäki, S., O.-P. Mattila, J. Pulliainen, K. Niemi, K. Luojus, and K. Böttcher. 2012. “An Optical Reflectance Model-Based Method for Fractional Snow Cover Mapping Applicable to Continental Scale.” Remote Sensing of Environment 123 (August). Elsevier Inc.: 508-21. doi:10.1016/j.rse.2012.04.010.</p>
<p>Metsämäki, S., J. Pulliainen, M. Salminen, K. Luojus, A. Wiesmann, R. Solberg, K. Böttcher, M. Hiltunen, and E. Ripper. 2015. “Introduction to GlobSnow Snow Extent Products with Considerations for Accuracy Assessment.” Remote Sensing of Environment 156. Elsevier Inc.: 96-108. doi:10.1016/j.rse.2014.09.018.</p>
<p>Salomonson, V.V., and I. Appel. 2006. “Development of the Aqua MODIS NDSI Fractional Snow Cover Algorithm and Validation Results.” IEEE Transactions on Geoscience and Remote Sensing 44 (7): 1747–56. doi:10.1109/TGRS.2006.876029.</p>
<p>Salomonson, V.V, and I Appel. 2004. “Estimating Fractional Snow Cover from MODIS Using the Normalized Difference Snow Index.” Remote Sensing of Environment 89 (3): 351–60. doi:10.1016/j.rse.2003.10.016.</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div>EUPL (&gt;= 1.2)</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/library\.land\.copernicus\.eu");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>2026 EEA. All rights reserved.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>